speced/respec

js/core/dfn.js
js/core/link-to-dfn.js
js/core/templates/webidl-contiguous/attribute.html
js/core/templates/webidl-contiguous/callback.html
js/core/templates/webidl-contiguous/comment.html
js/core/templates/webidl-contiguous/const.html
js/core/templates/webidl-contiguous/dict-member.html
js/core/templates/webidl-contiguous/dictionary.html
js/core/templates/webidl-contiguous/enum-item.html
js/core/templates/webidl-contiguous/enum.html
js/core/templates/webidl-contiguous/exception.html
js/core/templates/webidl-contiguous/extended-attribute.html
js/core/templates/webidl-contiguous/field.html
js/core/templates/webidl-contiguous/implements.html
js/core/templates/webidl-contiguous/interface.html
js/core/templates/webidl-contiguous/method.html
js/core/templates/webidl-contiguous/param.html
js/core/templates/webidl-contiguous/serializer.html
js/core/templates/webidl-contiguous/typedef.html
js/core/webidl-contiguous.js
js/core/webidl-oldschool.js
js/profile-w3c-common.js
js/webidl2.js
tests/SpecRunner.html
tests/phantom-runner.html
tests/spec/core/webidl-contiguous-spec.js
tests/spec/core/webidl-contiguous.html

@darobin
Resolves #334, which also has more discussion of the idea.

Add the ability to process contiguous WebIDL blocks

---

package.json
tools/respec2html.js

This properly installs respec2html as a CLI tool.

Binary install

---

js/core/css/examples-webspecs.css
js/core/examples.js
js/w3c/headers.js

These are some small tweaks that fix a few small problems with ReSpec when used for WebSpecs.

Webspec issues

---

js/w3c/templates/headers.html

see http://www.w3.org/2005/07/pubrules?uimode=filter#copyright

pubrules expects a period not a comma in w3c copyright

---

js/core/webidl-oldschool.js
tests/spec/core/webidl.html

Update the [readonly] maplike description. See #361 for the discussion.

Maplike update

---

js/core/webidl-oldschool.js
tests/spec/core/webidl.html

Reported in #361.
- There were HTML markup errors.
- Auto-generated method description was wrong.

Fix maplike errors.

---

js/core/biblio.js

re-reverting to labs.w3.org

---

js/core/templates/webidl-contiguous/comment.html
js/core/templates/webidl-contiguous/enum-item.html
js/core/templates/webidl-contiguous/enum.html
js/core/templates/webidl-contiguous/extended-attribute.html
js/core/templates/webidl-contiguous/line-comment.html
js/core/templates/webidl-contiguous/multiline-comment.html
js/core/webidl-contiguous.js
tests/spec/core/webidl-contiguous-spec.js
tests/spec/core/webidl-contiguous.html

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/w3c/respec/426)

Propagate comments and whitespace through the contiguous IDL processor.

---

README.md
tests/headless.js
tests/phantom-runner.html
tests/phantom.js

e.g. node ./tests/headless.js webidl will only run tests whose spec name contains "webidl"

allow to filter tests run based on spec name

---

js/core/css/issues-notes.css
js/core/issues-notes.js
js/w3c/aria.js
tests/spec/core/issues-notes-spec.js

Creates an Editor's Note that is styled like a Note.
Addresses issue #436

Added support for class ednote

---

js/core/templates/webidl-contiguous/extended-attribute.html
js/core/webidl-contiguous.js
js/webidl2.js
tests/spec/core/webidl-contiguous-spec.js
tests/spec/core/webidl-contiguous.html

/cc @jyasskin
Don't merge until darobin/webidl2.js#29 is approved and merged.

Add support for WebIDL RHS identifier list.

---

js/core/css/issues-notes.css
js/core/issues-notes.js
js/github.js

Adresses some but not all of the issues brought up in #241.
Needs tests, but those will need to rely on a mock server for requests.
Also needs doc.
Help welcomed. :)

Including body and title of GitHub issues.

---

js/core/issues-notes.js

Add an Issue summary

---

js/core/webidl-contiguous.js
tests/spec/core/webidl-contiguous-spec.js
tests/spec/core/webidl-contiguous.html

Fix Contiguous WebIDL support for callbacks with multiple args.

---

js/w3c/headers.js
js/w3c/templates/sotd.html

For #462 
Do not merge and deploy before September 1, 2015

Process 2015 is coming

---

examples/basic.html

I use this file for development a lot, so wanted some contiguous webidl in there.

added contiguous webidl

---

README.md

this text is no longer relevant

Removed outdated version text (closes #327)

---

js/core/include-config.js
js/core/override-configuration.js
js/w3c/headers.js
tests/spec/w3c/headers-spec.js

Implements #507; see more detailed description there.

Extra name entries

---

js/core/webidl-oldschool.js

Avoid double commas bug in WebIDL oldschool

---

js/w3c/headers.js

Introduced in 21efc4e521d30b90752cbb99919af176c1e3d2b1 when switching from $.each to forEach
Another case were #501 would have helped :)

Fix bug in editor name check

---

js/core/utils.js

Allows to keep source valid HTML

Accet data-for and data-link-for as equivalents to for and link-for

---

tools/respec2html.js

Helps debugging failures due to overall timeout

Set timeout for XHR requests in respec2html.js

---

js/core/webidl-contiguous.js

Avoid duplicating ids on multiple partials

---

js/w3c/fixup.js

Change fixup.js location

---

js/w3c/style.js

in order to comply with pubrules as per @plehegar

Moved fixup.js to end

---

js/profile-w3c-common.js

* includes the UI/*js files as if they were plugins.

Make sure UI plugins are added (close #590)

---

.travis.yml
karma.conf.js

* disabling firefox, which is working fine...

Try to figure out why Chrome keeps failing

---

js/core/base-runner.js
js/profile-w3c-common.js
tools/builder.js

This should fix the loading issue with Promise polyfill.

Added dependencies on Promise.

---

js/core/biblio.js
js/core/data-include.js
js/github.js
js/profile-w3c-common.js
karma.conf.js
package.json
tools/builder.js

Sending for testing ... this includes #623.

Use fetch instead of ajax

---

js/core/ui.js
js/ui/save-html.js

This is part 1 of enabling nightmarejs. It gives certain elements IDs so we can target them more easily from nightmarejs. It also allows us to test live specs before fully migrating.

Feat (ui.js,save-html.js): Give UI elements ids

---

tools/respec2html.js
tools/respecDocWriter.js

@dontcallmedom WDTY? 
```JS
const fetchAndWrite = require("./tools/respecDocWriter.js").fetchAndWrite;
const src = "https://w3c.github.io/manifest/";
const out = "path/to/out"; // or null for stdout
const whenToHalt = {
haltOnError: true,
haltOnWarn: true,
};
const timeout = 10000;
fetchAndWrite(src, out, whenToHalt, timeout).then(() => console.log("done") );
```

WIP(respec2html): Externalize fetch and write

---

tools/respecDocWriter.js

Feat(respecDocWriter): resolve fetchAndWrite promise with HTML

---

tests/headless.js
tools/respec2html.js
tools/respecDocWriter.js

* halt on 404
* don't output when out is the emtpy string

Feat(respecDocWriter): improvements (closes #706)

---

package.json

* Enables the ability to test on Safari Tech Preview if available on the system.

Feat(package): run tests in Safari Tech Preview

---

tests/spec/core/webidl-contiguous-spec.js
tests/spec/core/webidl-contiguous.html

Just to ensure it is supported.

Simple test to exercise FrozenArray

---

tests/spec/core/markdown-spec.js
tests/spec/w3c/headers-spec.js

Spotted a couple of false positives

Fix bad tests

---

js/core/style.js

Depends on #766 and helps with #326.
Here we opportunistically insert style elements, avoid a bit of FOUC.

Fix(style): reduce ReSpec FOUC (relates to #326)

---

js/ui/save-html.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/respec/794)

Fix(save-html) Space after ( when saving(closes #786)

---

js/core/link-to-dfn.js
js/core/location-hash.js
js/core/pubsubhub.js
js/w3c/conformance.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/respec/795)

Fix(legacy): Add messages for Aria/WebPayment specs (closes #793)

---

js/ui/save-html.js
js/w3c/style.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/respec/797)

Bug 791 charset

---

js/core/ui.js
js/core/utils.js
tests/spec/core/utils-spec.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/respec/799)

Fix(ui,utils): firstElementChild not in Edge (closes #798)

---

js/core/highlight.js
tests/spec/core/highlight-spec.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/respec/811)

Dont hightlight idl

---

js/core/override-configuration.js
tests/spec/core/override-configuration-spec.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/respec/816)

Fix(override-configuration):decode URL params correctly (closes #807)

---

js/core/jquery-enhanced.js

Now points to wiki.  Also does not use @ in front of title - it was
redundant.  Should address #869

Changed warning pointer for use of @title.

---

js/core/css/respec2.css

fix(respec2.css): th code inherit color (closes #877)

---

js/core/data-include.js
package.json
tests/spec/core/data-include-spec.js
tests/spec/core/includer.html

Refactored code and more tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/respec/1004)

Unjquery data-include

---

js/core/default-root-attr.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/respec/1006)

refactor(default-root-attr): unjquery, run sync

---

js/core/dfn.js
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/respec/1007)

refactor(core/dfn): unjquery as much as possible

---

js/core/webidl-contiguous.js

Search in lowercase for overloaded operations

---

js/ui/save-html.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/respec/762)

Feat(save-html): remove XHTML 1.0 save support

---

src/core/highlight.js
worker/respec-worker.js

Accidentally tried to send an object that is sometimes not "structured-cloneable"

Fix highlight

---

js/core/css/respec2.css

cf [`https://labs.w3.org/echidna/api/status?id=c6ba4368-f490-434e-aa84-a5b4da0cc912`](https://labs.w3.org/echidna/api/status?id=c6ba4368-f490-434e-aa84-a5b4da0cc912)

Fix a CSS property

---

js/w3c/headers.js
js/w3c/templates/sotd.html

For #1039 
Must be deployed between March 1 and March 31.

Use Process 2017

---

.travis.yml

Hopefully reduces intermittent fails.

test(.travis.yml): try tests up to 3 times

---

js/core/css/respec2.css

fix(core/css/respec2): use native wavy red line for errors

---

CODE_OF_CONDUCT.md
README.md

More secure links

---

examples/starter.html

Use Process 2017 in the starter spec

---

js/w3c/templates/cgbg-sotd.html
js/w3c/templates/sotd.html
src/core/structure.js
src/w3c/headers.js
tests/spec/w3c/headers-spec.js

fix(core/headers): SoTD doesn't respect sections

---

js/profile-w3c-common.js
package.json
tools/copydeps.js

Supported across all browsers now 🎉 .

refactor: remove fetch poly

---

js/profile-w3c-common.js

Reverts the smaller dom ready ... not working right 😭

Revert dom ready

---

tests/spec/core/override-configuration-spec.js

Firefox 54 seems to run into a strage race condition with this tests,
so I'm merging into the previous test

refactor(override-configuration-spec): merge tests

---

js/core/templates/webidl-contiguous/method.html
src/core/webidl.js
tests/spec/core/webidl-spec.js
tests/spec/core/webidl.html

feat(core/webidl): autolink toJSON to IDL spec

---

src/ui/dfn-list.js
src/ui/search-specref.js

Fix a couple of bugs found by @WebReflection.

Fix bad usage of hyperHTML

---

js/core/css/respec2.css

fix(core/css/respec2): less ugly test box

---

js/profile-w3c-common.js
src/core/aria.js
tests/spec/core/aria-spec.js

Avoid race conditions

---

js/profile-w3c-common.js
src/core/seo.js
src/w3c/seo.js
tests/spec/SpecHelper.js
tests/spec/core/seo-spec.js
tests/testFiles.json

This takes the first paragraph of the abstract and inserts it in the head of the document as a meta description element.

Feat: add core seo module

---

src/core/data-cite.js
tests/spec/core/data-cite-spec.js

Allow to specific path to a subpage in reference citations

---

src/ui/save-html.js

fix(ui/save-html): move meta charset to top

---

package.json

fix(package): update hyperhtml to version 2.1.2

---

examples/basic.html
examples/starter.html
js/w3c/templates/sotd.html
src/w3c/defaults.js
src/w3c/headers.js
tests/spec/w3c/defaults-spec.js

This only takes care of the link (ie doesn't take into account new Amended statuses)
See also
https://github.com/w3c/modern-tooling/issues/71

New link to the Process 2018

---

src/w3c/headers.js

Fix a typo in src/w3c/headers.js

---

.travis.yml

Now Travis is also happy on my fork :smile: https://travis-ci.org/saschanaz/respec/builds/337874951
Fixes #1462

workaround: use sudo required on travis

---

.travis.yml
tests/headless.js
tools/respec2html.js
tools/respecDocWriter.js

This introduces sandbox-disabling option for some limited environments. See https://github.com/w3c/spec-generator/pull/64
cc: @marcoscaceres @deniak

feat: support --disable-sandbox on respec2html

---

js/w3c/templates/sotd.html
src/w3c/defaults.js
src/w3c/headers.js
tests/spec/w3c/defaults-spec.js

feat(w3c): remove processVersion option

---

package-lock.json
package.json

updates to puppeteer and marked

chore(package): updates puppeteer + marked

---

tools/respec2html.js

fix(tools/respec2html): resolve src to file URL

---

tools/release.js
tools/respecDocWriter.js

This fixes some Codacy warnings.

refactor(tools/release, tools/respecDocWriter): use double quotes

---

src/core/aria.js
src/core/best-practices.js
src/core/data-tests.js
tools/release.js

refactor(core/best-practices): replace jQuery

---

src/core/inlines.js

Probably a good thing to do before doing #1520.

refactor(core/inlines): use ES2015+/remove jQuery

---

src/core/base-runner.js
src/core/best-practices.js
src/w3c/abstract.js
src/w3c/headers.js
src/w3c/informative.js

refactor(w3c/informative): remove jQuery

---

src/core/structure.js
tests/spec/core/structure-spec.js

Fixes : #1545 
Since title is always present.

Link back to top to title of spec

---

src/core/issues-notes.js

w3c/respec#1502
Converting code to async await as stated in https://github.com/w3c/respec/issues/1502#issuecomment-368250097

refactor(core/issues-notes): use async/await + simplify

---

karma.conf.js
src/core/issues-notes.js
tests/data/issues/1540
tests/data/issues/1540.json
tests/data/issues/1548
tests/spec/core/issues-notes-spec.js

fix(core/issues-notes): closed issue should be removed from spec

---

js/core/css/issues-notes.css
js/ui/ui.css
src/core/issues-notes.js
tests/data/issues/1540
tests/spec/core/issues-notes-spec.js

fixes #674 
Preview of changes:

feat: show github issue's labels

---

src/core/webidl.js
tests/spec/core/webidl-spec.js
tests/spec/core/webidl.html

fix(core/webidl): indent stringifiers

---

src/core/caniuse.js
tests/spec/core/caniuse-spec.js
tests/spec/core/include-config-spec.js

I'm not sure about the way I wrote tests. Please review.

Remove irrelevant config for caniuse feature

---

src/w3c/headers.js

fix(w3c/headers): typo

---

tests/spec/w3c/headers-spec.js

refactor(headers-spec): variable name typo

---

js/core/css/var.css
src/core/highlight-vars.js
tests/spec/core/highlight-vars-spec.js

Update var highlight colors, as discussed in https://github.com/w3c/tr-design/issues/152

Update var highlight colors

---

src/core/location-hash.js

On [payment request](https://w3c.github.io/payment-request/), processing time for `core/location-hash` is around 110ms. Improves to 0.3ms.
Edit: Also adds support for IE 9 :laughing:

perf(core/location-hash) improve performance

---

src/core/biblio.js
src/core/inlines.js
tests/spec/core/biblio-spec.js
tests/spec/core/data-cite-spec.js
tests/spec/core/inlines-spec.js

fix(core/biblio):  auto normalize references

---

src/core/inlines.js
src/core/jquery-enhanced.js
src/core/utils.js
tests/spec/core/inlines-spec.js
tests/spec/core/utils-spec.js

As a part of https://github.com/w3c/respec/issues/1699

refactor(core/jquery-enhanced): migrate $.allTextNodes to vanilla js

---

js/core/templates/webidl-contiguous/iterable-like.html
js/core/templates/webidl-contiguous/iterable.html
js/core/templates/webidl-contiguous/maplike.html
js/core/templates/webidl-contiguous/method.html
src/core/webidl.js
tests/spec/core/webidl-spec.js
tests/spec/core/webidl.html

Fixes #1704
Fixes #1705 
Fixes #1707

Support setlike and bodyless stringifier

---

package-lock.json
src/core/webidl.js
tests/spec/core/webidl-spec.js
tests/spec/core/webidl.html

It's causing double spaces in some specs.

fix(core/webidl): prevent duplicated whitespace after comma

---

src/w3c/headers.js
tests/spec/w3c/headers-spec.js

fix: allow multiple logos when unofficial

---

src/core/webidl.js

* fixes #1674
Fixes the above.

fix(core/webidl): improve display of errors

---

src/core/data-cite.js
src/core/link-to-dfn.js
tests/spec/core/xref-spec.js

Part of https://github.com/w3c/respec/issues/1662

feat(core/xref): support external dfn

---

src/core/webidl.js
tests/spec/core/webidl-spec.js
tests/spec/core/webidl.html

fix(core/webidl): extra space between optional and identifier

---

src/core/biblio.js

fix(core/biblio): prevent SpecRef request if there are no refs

---

js/core/templates/webidl-contiguous/param.html
src/core/webidl.js
tests/spec/core/webidl-spec.js
tests/spec/core/webidl.html

fix(core/webidl): include optional's trivia

---

js/core/css/webidl.css
src/core/webidl-index.js
tests/spec/core/idl-index-spec.js

Add spaces between IDL

---

src/core/xref.js
tests/data/xref.json
tests/spec/core/xref-spec.js

As part of https://github.com/w3c/respec/issues/1662

feat(core/xref): add normative, informative references

---

.eslintrc.json
src/core/data-cite.js
src/core/examples.js
src/core/issues-notes.js
src/core/link-to-dfn.js
src/core/ui.js
src/core/utils.js
src/core/webidl.js
src/ui/about-respec.js
src/w3c/headers.js
src/w3c/permalinks.js
src/w3c/style.js
tests/.eslintrc.yml

Why are those two eslintrc files in different formats, one in JSON and one in YAML?

refactor: use const and arrow functions

---

karma.conf.js
src/w3c/templates/show-people.js
tests/spec/w3c/headers-spec.js

fix(templates/show-people): allow HTML for company field

---

js/core/templates/webidl-contiguous/iterable-like.html
js/core/templates/webidl-contiguous/typedef.html
src/core/webidl.js
tests/spec/core/webidl-spec.js
tests/spec/core/webidl.html

fix(core/webidl): find interface dfn in section

---

tools/copydeps.js

Mark deps/domReady as deprecated

---

src/core/github.js
src/core/issues-notes.js

fix(core/github): Support conf.github without trailing slash

---

src/core/jquery-enhanced.js
src/core/utils.js

As a part of https://github.com/w3c/respec/issues/1699

refactor(core/jquery-enhanced): migrate $renameElement to vanilla js

---

src/core/utils.js
tests/spec/core/jquery-enhanced-spec.js
tests/spec/core/utils-spec.js

fix(core/utils): generate ids without diacritical marks

---

js/core/templates/webidl-contiguous/enum-item.html
src/core/webidl.js
tests/spec/core/webidl-spec.js
tests/spec/core/webidl.html

fix(webIDL): unambiguously link emum values

---

js/core/css/respec2.css
src/core/id-headers.js
src/w3c/defaults.js
tests/spec/core/id-headers-spec.js
tests/spec/w3c/defaults-spec.js

feat(core/id-headers): add section links

---

src/core/link-to-dfn.js
src/core/webidl.js
tests/spec/core/webidl-spec.js
tests/spec/core/webidl.html

fix(core/webidl): fully qualified names not coded

---

src/core/post-process.js
src/core/pre-process.js
src/core/pubsubhub.js

feat(core/pubsubhub): show error if callback fails

---

src/core/data-cite.js
src/core/inlines.js
src/core/utils.js
tests/spec/core/data-cite-spec.js
tests/spec/core/inlines-spec.js

Adds contextual citation to `data-cite` by reusing the inline contextual citation.

feat(core/data-cite): support contextual citing

---

src/core/data-cite.js
tests/spec/core/data-cite-spec.js

fix(core/data-cite): always resolve path relative to reference URL

---

src/core/figures.js

fix(core/figures): prevent setting dimensions to 0

---

src/w3c/templates/sotd.js

fix(templates/sotd): use issueBase for github issues URL

---

tools/respec2html.js
tools/respecDocWriter.js

Allows quick access to debugging tools in ReSpec2html.

feat(respec2html): allow debugging by showing devtools

---

js/core/css/webidl.css
js/core/templates/webidl-contiguous/attribute.html
js/core/templates/webidl-contiguous/callback.html
js/core/templates/webidl-contiguous/const.html
js/core/templates/webidl-contiguous/dict-member.html
js/core/templates/webidl-contiguous/dictionary.html
js/core/templates/webidl-contiguous/enum.html
js/core/templates/webidl-contiguous/interface.html
js/core/templates/webidl-contiguous/method.html
js/core/templates/webidl-contiguous/param.html
js/core/templates/webidl-contiguous/typedef.html
package-lock.json
package.json
tests/spec/core/webidl-spec.js

Merge IDL CSS classes

---

src/core/base-runner.js
src/core/biblio.js
src/core/data-include.js
src/core/data-transform.js
src/core/figures.js
src/core/link-to-dfn.js
src/core/linter.js
src/core/list-sorter.js
src/core/markdown.js
src/core/seo.js
src/core/structure.js
src/core/style.js
src/core/webidl-clipboard.js
src/w3c/conformance.js
src/w3c/rfc2119.js
src/w3c/seo.js
src/w3c/style.js

This removes all remaining callbacks from plugins and deprecates callbacks.

refactor: modernize all plugins

---

src/core/link-to-dfn.js
src/core/utils.js

refactor(core/link-to-dfn): remove jquery

---

src/core/dfn.js
src/core/link-to-dfn.js
src/core/pluralize.js
src/core/webidl.js
src/ui/dfn-list.js

refactor: vanilla elements in conf.definitionMap

---

.babelrc
package-lock.json
package.json

Easy enough and fun, especially [`"targets": "defaults"`](https://babeljs.io/docs/en/babel-preset-env#targets).
Fixes #1900

chore(package): upgrade to Babel 7

---

package-lock.json
package.json
src/core/webidl.js

 refactor(core/webidl): upgrade to webidl2.js 16 

---

src/core/webidl.js

`linkDefinitons()` that can be fully understood 👍

refactor(core/webidl): further split linkDefinitions()

---

package-lock.json
package.json
src/core/exporter.js
tests/spec/core/exporter-spec.js

chore(package): update hyperHTML to 2.19

---

.eslintrc.json
src/core/data-cite.js
src/core/markdown.js
src/core/ui.js
src/core/utils.js
src/core/webidl.js

refactor: use object shorthand, prefer append(), etc.

---

.eslintrc.json
src/core/figures.js
tests/spec/core/figures-spec.js

Not super easy to replace everything in once.

refactor(core/figure): remove some jQuery 

---

src/core/link-to-dfn.js
src/core/utils.js

Because I hate a single function with 150+ lines 🤣
This PR is a snapshot as more work is needed.

refactor(core/link-to-dfn): split functions

---

src/core/dfn-finder.js
src/core/dfn.js
tests/spec/core/dfn-finder-spec.js
tests/spec/core/link-to-dfn-spec.js

fix(core/dfn-finder): prevent duplicated definition registration

---

src/core/figures.js

refactor(core/figures): remove jQuery

---

src/core/structure.js

This change just removes a console error message without any behavior change. I have no idea how to add a test for this, because it's totally expected that nothing occurs when no sections.
Any ideas?

fix(core/structure): fix undefined property access error

---

src/core/base-runner.js
src/core/dfn-finder.js
src/core/dfn-map.js
src/core/dfn.js
src/core/link-to-dfn.js
src/core/pluralize.js
src/core/webidl.js
src/ui/dfn-list.js

refactor: modularize definitionMap

---

src/core/issues-notes.js
tests/data/issues/1540
tests/data/issues/1548
tests/spec/core/issues-notes-spec.js

This PR includes two fixes for regressions after #1969.

refactor(core/issues-notes): split functions and add JSDocs

---

tests/test-main.js

refactor(tests/test-main): remove redundant lines

---

tests/spec/core/biblio-spec.js
tests/spec/core/section-refs-spec.js
tests/spec/core/structure-spec.js
tests/spec/core/webidl-spec.js

refactor(tests/spec/core): use getElementById

---

src/core/best-practices.js
src/core/data-cite.js
src/core/data-tests.js
src/core/examples.js
src/core/exporter.js
src/core/figures.js
src/core/inlines.js
src/core/pluralize.js
src/core/utils.js
src/type-helper.d.ts
src/ui/save-html.js
src/ui/search-specref.js

@devanshbatra04 This is my previous work with some fixes added. I hope this can be a guide.

refactor: add ts-check

---

.gitignore
package.json
src/core/github.js
src/core/l10n.js
tests/spec/core/issues-notes-spec.js

fix(core/github): link GitHub at-risk issues

---

src/core/utils.js
tests/spec/core/link-to-dfn-spec.js

Closes #510, closes #1161 
I found that the issue is already fixed, so just adding a test.

test(core/link-to-dfn): ensure data-lt is preferred

---

.eslintrc.json

Hello @marcoscaceres sir. This is a PR to close #2012 .
I'm new to open source. Couldn't change the previous PR as I had deleted the forked repository :(

added eol to eslint

---

src/w3c/defaults.js

fix(w3c/defaults): expose conf.definitionMap to w3c specs

---

src/core/jquery-enhanced.js

This is to fix https://github.com/w3c/aria/issues/871.

fix(core/jquery-enhanced): set window.jQuery

---

package-lock.json
src/core/issues-notes.js
tests/spec/core/issues-notes-spec.js

@marcoscaceres  This fixes #2045 (div that are of class "note" should have a role="note" )

fix(core/issues-notes.js): add ARIA role "note" to notes

---

package-lock.json
package.json
src/core/biblio-db.js
src/w3c/style.js

Greenkeeper/eslint 5.13.0

---

src/w3c/templates/cgbg-headers.js
src/w3c/templates/cgbg-sotd.js
src/w3c/templates/headers.js
src/w3c/templates/show-link.js
src/w3c/templates/sotd.js
tests/spec/core/examples-spec.js
tests/spec/w3c/headers-spec.js

Looks like this is intended change from prettier. prettier/prettier#5771
Not sure why Travis didn't say anything for other PRs.

refactor: apply prettier changes

---

.travis.yml
package.json

test: fix eslint not globbing correctly on Linux

---

package.json
src/core/LinterRule.js
src/core/linter-rules/check-internal-slots.js
src/core/linter-rules/check-punctuation.js
src/core/linter-rules/local-refs-exist.js
src/core/linter-rules/no-headingless-sections.js
src/core/linter-rules/no-http-props.js
src/core/linter.js
src/w3c/linter-rules/privsec-section.js
tests/spec/core/linter-rules/check-internal-slots-spec.js
tests/spec/core/linter-rules/check-punctuation.js
tests/spec/core/linter-rules/local-refs-exist-spec.js
tests/spec/core/linter-rules/no-headingless-sections-spec.js
tests/spec/core/linter-rules/no-http-props-spec.js
tests/spec/w3c/linter-rules/privsec-section-spec.js

May help future linter contributions write correct types 😁
Closes #1670

refactor(core/linter-rules): add ts-check

---

src/core/data-cite.js
tests/spec/core/data-cite-spec.js

feat(core/data-cite): Include Spec title when expanding <a data-cite='' "></a>

---

.eslintrc.json
js/profile-w3c-common.js
src/core/biblio-db.js
src/core/biblio.js
src/core/data-include.js
src/core/linter-rules/check-charset.js
src/core/markdown.js
src/core/ui.js
src/core/utils.js
src/core/webidl-index.js
src/ui/dfn-list.js
src/w3c/headers.js
src/w3c/style.js
tests/headless.js
tests/spec/SpecHelper.js
tests/spec/core/data-include-spec.js
tests/spec/core/pluralize-spec.js
tests/spec/core/webidl-spec.js
tests/test-build.js
tests/test-main.js
tools/release.js
tools/respec2html.js
tools/respecDocWriter.js

This forces spaces after `//`, `/*` and before `*/`.

style: apply spaced-comment eslint rule

---

tests/specifications/ED-respec-test-20100224.html
tests/specifications/index.html
tests/specifications/snapshot-as-html_source.html

chore(tests): Geoffrey changed name to Sam

---

package-lock.json
package.json

Snyk is completely broken at the moment. It's good to run snyk during build, but running it during prepare is 🤷‍♂️.

chore(package): don't snyk during prepare

---

package-lock.json
package.json

fix(package): hljs cli now in main branch

---

src/core/utils.js
tests/SpecRunner.html
tests/spec/core/biblio-spec.js
tests/spec/core/structure-spec.js

fix(core/utils): treat introductory matter as non-normative

---

src/core/structure.js
tests/spec/core/section-refs-spec.js

fix(core/structure): add nbsp after §

---

src/core/render-biblio.js
tests/spec/core/biblio-spec.js

I made a mistake that messed up the branch I had made initial P.R on. :smile:  This P.R aims to fix everything and apply proper changes requested to resolve issue https://github.com/w3c/respec/issues/2084 . Thanks to all who review and @marcoscaceres for helping make requested changes.

Pull request to add localization strings and tests for module render-biblio.

---

tests/spec/core/xref-spec.js

Looks like something has changed from upstream.
Closes #2137

test(xref-spec): fix webauthn url

---

tools/builder.js

`npm run build:respec-w3c-common -- --debug` emits an unoptimized result.

feat(tools/builder): add debug mode

---

assets/webidl.css

Hide copy paste button while printing

---

src/core/inlines.js

@marcoscaceres as discussed, I have implemented the first stage of code refactor for `core/inlines.js`. Will be looking forward to a review from your side :)

refactor(core/inlines.js): split target code into sub functions

---

assets/webidl.css

P.R to fix the issue https://github.com/w3c/respec/issues/2144 
Thanks to @marcoscaceres and everyone for review.

fix copy-paste button visibility in spec print

---

src/core/xref.js
tests/spec/core/xref-spec.js

feat(core/xref): collect similar errors

---

src/core/xref.js

well that was easier than I expected..

feat(core/xref): Use respec.org for xref API 

---

package-lock.json
package.json
src/core/webidl.js
tests/spec/core/webidl-spec.js
tests/spec/core/webidl.html
tools/copydeps.js

Closes #2177 
Closes #2176 
Oops, didn't know you already opened a PR 😅

chore(package): update to webidl2@18

---

.eslintignore
.gitignore
js/profile-w3c-common.js
karma.conf.js
package.json
src/core/reindent.js
src/type-helper.d.ts

refactor: remove hljs config from profile

---

src/core/override-configuration.js

refactor(core/override-configuration): clean comments

---

src/core/data-abbr.js
tests/spec/core/data-abbr-spec.js

fix(core/data-abbr): normalize abbreviations

---

src/w3c/templates/show-people.js
tests/spec/w3c/headers-spec.js

fix(w3c/templates/show-people): put orcid after name

---

src/core/examples.js
src/core/figures.js
src/core/informative.js
src/core/issues-notes.js
src/core/linter-rules/check-charset.js
src/core/linter-rules/check-internal-slots.js
src/core/linter-rules/check-punctuation.js
src/core/linter-rules/local-refs-exist.js
src/core/linter-rules/no-headingless-sections.js
src/core/linter-rules/no-http-props.js
src/core/render-biblio.js
src/core/structure.js
src/core/ui.js
src/ui/about-respec.js
src/ui/dfn-list.js
src/ui/save-html.js
src/ui/search-specref.js
src/w3c/abstract.js
src/w3c/conformance.js
src/w3c/defaults.js
src/w3c/headers.js
src/w3c/l10n.js
src/w3c/linter-rules/privsec-section.js
src/w3c/linter.js
src/w3c/seo.js
src/w3c/style.js
src/w3c/templates/headers.js
src/w3c/templates/show-link.js
src/w3c/templates/show-logo.js

Accidentally omitted them in #2237 😅

refactor: add .js file extensions for remainings

---

package-lock.json
package.json
src/core/webidl-clipboard.js
tools/copydeps.js

Helpful for smaller build result and easier ES module migration.

refactor(core/webidl-clipboard): remove Clipboard dependency

---

assets/algorithms.css

`border-color` was not being used.
From: 
to this:

fix(assets/algorithms.css): fix assert border-color

---

src/geonovum/style.js
tests/spec/geonovum/style-spec.js

Small changes to geonovum styling (starting fresh from w3c develop)

(geonovum) update style and style test

---

src/core/inlines.js
tests/spec/core/xref-spec.js

fixes #2258 
Kinda ugly... can anyone think of a better solution?

Inline idl overmatch

---

src/core/inline-idl-parser.js
tests/spec/core/xref-spec.js

fix(core/inlines): fix rendering of enum types

---

src/core/inline-idl-parser.js
tests/spec/core/xref-spec.js

Closes https://github.com/w3c/respec/issues/2260

 feat(core/inlines): show error in inline idl parsing fails

---

src/core/xref.js
tests/data/xref/ambiguous.json
tests/data/xref/basic.json
tests/data/xref/cache-1.json
tests/data/xref/cache-2.json
tests/data/xref/data-cite-1.json
tests/data/xref/data-cite-2.json
tests/data/xref/data-lt.json
tests/data/xref/empty-data-cite-parent.json
tests/data/xref/inline-bibref.json
tests/data/xref/inline-idl-attributes.json
tests/data/xref/inline-idl-enum.json
tests/data/xref/inline-idl-methods.json
tests/data/xref/inline-idl-slots.json
tests/data/xref/inline-idl.json
tests/data/xref/inline-links.json
tests/data/xref/inline-locals.json
tests/data/xref/local-dfn.json
tests/data/xref/not_found.json
tests/data/xref/refs.json
tests/spec/core/xref-spec.js

Do not merge (release to be more accurate) until https://respec.org is updated.

feat(core/xref): use xref API v5

---

src/core/inlines.js

Broke Safari and Firefox, yay! 🥳

fix(core/inlines): RegExp syntax error 🔥

---

.travis.yml
karma.conf.js

test: add firefox to travis

---

tests/spec/w3c/headers-spec.js

Expectations were not being run on this test.

test(w3c/headers-spec): non-functioning tests

---

src/core/xref.js
tests/data/xref/data-cite-2.json
tests/data/xref/data-lt.json
tests/data/xref/inline-bibref.json
tests/data/xref/inline-idl-enum.json
tests/data/xref/inline-idl.json
tests/data/xref/refs.json

by requesting only unique queries

perf(core/xref): reduce payload size

---

src/core/xref.js

Closes https://github.com/w3c/respec/issues/2288

fix(core/xref): fetch from network on IDB cache error

---

src/core/caniuse.js

Closes https://github.com/w3c/respec/issues/2274

feat(core/caniuse): make title generic

---

src/core/xref.js

Closes https://github.com/w3c/respec/issues/2270

feat(core/xref): provide better hints if term is ambiguous

---

src/core/utils.js

Closes https://github.com/w3c/respec/issues/1635

fix(utils/fetchAndCache): avoid caching failed requests

---

src/core/biblio-db.js
src/core/data-abbr.js
src/core/data-include.js
src/core/examples.js
src/core/inlines.js
src/core/markdown.js
src/core/utils.js
src/w3c/headers.js

refactor: prefer .append() and DocumentFragment

---

src/core/markdown.js
src/core/utils.js
src/core/webidl.js
tests/spec/core/markdown-spec.js
tests/spec/core/utils-spec.js

Part of #2212, this would at least discourage further use of the function.

refactor(core/utils): transfer normalizePadding() to core/markdown

---

src/core/highlight-vars.js
tests/spec/core/highlight-vars-spec.js

fix(core/highlight-vars): only highlight own section's vars

---

src/core/examples.js
src/core/override-configuration.js
src/core/ui.js
src/ui/search-specref.js

refactor: remove redudant .entries() where not needed

---

package-lock.json
package.json

chore(package): update deps

---

src/core/anchor-expander.js

fix(core/anchor-expander): null check for matchingClosest

---

tests/spec/core/anchor-expander-spec.js

Forgot to `git add` these with the other PR 😅

tests(core/anchor-expander): tests for module

---

src/core/render-biblio.js
tests/spec/core/biblio-spec.js

closes #2334 
Tiny improvement:

fix(core/render-biblio): give inline refs a title attribute

---

src/core/github-api.js

#2200 added this but probably a mistake.

refactor(core/github-api): remove window.pub

---

src/w3c/headers.js

fix(w3c/headers): dont treat WD and FPWD as Rec Track docs

---

assets/datatype.css

https://github.com/w3c/webdriver/issues/1424

fix(assets/datatype): use CSS defaults for vars

---

src/core/caniuse.js
src/core/github-api.js
src/core/issues-notes.js
src/core/link-to-dfn.js
src/core/structure.js
src/core/utils.js
src/ui/search-specref.js

No need to write horizontally looooong types anymore 😁

refactor: use jsdoc type augmenting format

---

src/core/xref.js

fix(core/xref): solve typescript errors

---

src/core/webidl.js
tests/spec/core/webidl-spec.js

Also adding proper `data-dfn-type`.

feat(core/webidl): add data-export

---

package-lock.json
package.json
src/core/data-include.js
src/core/github-api.js
src/core/link-to-dfn.js
src/core/post-process.js
src/core/pre-process.js
src/core/webidl.js
src/w3c/headers.js
src/w3c/templates/cgbg-sotd.js
src/w3c/templates/headers.js
src/w3c/templates/sotd.js

I love this change :tada:
Closes #2387

chore(package): update dependencies

---

src/core/include-config.js
tests/spec/core/include-config-spec.js

sec(core/include-config): don't write githubToken, githubUser

---

package-lock.json
package.json
src/core/utils.js
src/core/webidl.js
tests/spec/core/webidl-spec.js

With some error style change:
Before:
After:

feat(core/webidl): point the failing IDL block

---

assets/respec2.css

Solving problem raised in https://github.com/w3c/respec/pull/2416#issuecomment-510440998.

refactor(assets/respec2): wavy by default

---

src/core/inlines.js
src/core/xref.js
tests/spec/core/inlines-spec.js

@sidvishnoi, we might want to do the same on the server: "Be conservative in what you send, be liberal in what you accept".

fix(core/xref): normalize data-xref-for before fetching

---

src/core/id-headers.js
tests/spec/core/id-headers-spec.js

fix(core/id-headers): always add header ids

---

src/core/dfn-finder.js
src/core/webidl.js

Closes #2444 
Looks simple enough.

refactor(core/dfn-finder): split findDfn and decorateDfn

---

src/core/biblio.js
src/core/data-cite.js

This bug caused local cache to be unexpectedly ignored.

fix(core/data-cite): pass key string instead of object

---

.babelrc
.eslintrc.json
package-lock.json
package.json
src/core/xref-db.js
src/core/xref.js
src/jsconfig.json
tests/.eslintrc.yml
tests/spec/core/webidl-spec.js
tools/builder.js

Helps #2187 to make caching parts compatible with Node.js.

refactor(core/xref): split its cache feature

---

src/core/inline-idl-parser.js
tests/spec/core/inlines-spec.js

Closes https://github.com/w3c/respec/issues/2466

enhancement(core/inlines): add {{ EnumContainer / "enum value" }} syntax

---

package-lock.json
package.json

chore(package): update webidl2 to version 23.5.1

---

src/core/dfn-finder.js
src/core/dfn-map.js
src/core/link-to-dfn.js
src/core/utils.js

Split from #2489 
Sorry to be too picky, but I had to do this... 🙄

refactor: use maps and sets

---

examples/basic.built.html
examples/basic.html
package-lock.json
package.json
src/core/dfn-finder.js
src/core/webidl.js
tests/spec/core/webidl-spec.js

Closes https://github.com/w3c/respec/issues/394 
Closes #2494

feat(core/webidl): support constructor linking

---

src/core/dfn-finder.js
tests/spec/core/webidl-spec.js

fix(core/dfn-finder): allow linking with different forms

---

src/core/inlines.js
tests/spec/core/inlines-spec.js

Closes https://github.com/w3c/respec/issues/2498

feat(core/inlines): Support aliasing with [=linking syntax=]

---

src/core/webidl.js

This shows autosuggestion like below:

feat(core/webidl): suggest IDL fix from autofix

---

src/core/webidl.js
tests/spec/core/webidl-spec.js

fix(core/webidl): whitelist for extended attribute linking

---

src/core/dfn-finder.js
tests/spec/core/webidl-spec.js

fix(core/dfn-finder): properly find constructor overloads

---

assets/respec2.css

fix(assets/respec2): make links white in .simple table

---

src/core/biblio-db.js
src/geonovum/style.js

Some things I failed to find in #2543.

chore: fix some nits

---

.eslintrc.json
package-lock.json
package.json
src/core/inline-idl-parser.js
src/core/mdn-annotation.js
src/w3c/templates/show-people.js

Maximizes es module compatibility.

refactor: force extensions for imports

---

src/core/webidl.js

Closes #2563
Can't test error messages yet, so just a fix.

fix(core/webidl): escape IDL code for fix suggestions

---

examples/starter.html

I was also confused by the behaviour described in #2580, so I think it would be good to add the conformance section to `starter.html`, so that anyone starting from that template will not run into this.

Add conformance section to starter.html.

---

src/core/caniuse.js
src/core/data-tests.js
src/core/mdn-annotation.js
src/ui/about-respec.js
src/w3c/templates/show-people.js

Extracted from #2548. Leads to more declarative and readable code 😁

refactor: prefer inline HTML over bind()

---

tools/dev-server.js

Closes https://github.com/w3c/respec/issues/2601
Works on my Ubuntu. Please do check on your respective systems.

chore(tools/dev-server): cleanup builds directory on exit

---

src/core/pluralize.js
src/core/utils.js
tests/spec/core/dfn-spec.js

Closes https://github.com/w3c/respec/issues/2566

enhancement(core/dfn): add support for `data-local-lt`

---

js/deps/marked.js
js/deps/rollup.config.js
karma.conf.js
src/core/import-maps.js

More and more ES modules in the world 🎉

refactor(src/import-maps): use marked es module

---

src/w3c/headers.js
src/w3c/templates/cgbg-headers.js
src/w3c/templates/headers.js

Fixes #2632  Removes bugTracker support

chore(w3c/headers): remove conf.bugTracker support

---

src/core/markdown.js

...and a bit of additional refactoring.
I'm not sure empty paragraphs still happen in the latest version of marked, at least it doesn't happen in wicg/serial. I don't think we should actively workaround marked bugs in ReSpec anyway...

refactor(core/markdown): drop paragraph removal

---

tools/release.js

Fixes https://github.com/w3c/respec/issues/2647

chore(tools/release): update package version before build

---

src/core/ui.js

Changed the aria-label from `Document errors` / `Document warnings`
to `_x_ ReSpec errors/warnings`

Changed the aria-label of error butons

---

src/w3c/headers.js
tests/spec/w3c/headers-spec.js

feat(w3c/headers): allow sotd to be overriden

---

src/w3c/conformance.js
tests/spec/w3c/conformance-spec.js

feat(w3c/conformance): allow override of conformance section

---

.github/workflows/pr-push.yml

Earlier:  4m 3s 
Now:  3m 46s 
It's something, but not a lot. Reason: cache restore takes ~15s (which might improve in future)

chore(ci): cache node modules

---

tools/release.js

1. always log what command is running. helps in debug and undo in case things go bad.
2. `--allow-same-version` should be an error.
3. Add  before `commit --amend`

chore(tools/release): fix associated commit

---

CHANGELOG.md
src/core/examples.js
src/core/informative.js
src/core/l10n.js

I am working on translating w3c using respec, and TOC is not rendered due to lack of I10n when I change to lang=ko.
So I have added translations into korean

Update l10n.js - Korean

---

tools/release.js

Fix release yet again :balloon:

chore(tools/release): fix staging before checkout

---

src/w3c/templates/show-people.js

feat(show-people): add Korean translation

---

src/core/xref-db.js

Specs stayed broken for longer than expected.

fix(core/xref): check for updates in 5min instead of 5h

---

assets/ui.css
src/ui/search-xref.js

As discussed in https://github.com/w3c/respec/pull/2709#discussion_r365702419

feat(ui/search-xref): add link to open UI in new tab

---

src/core/biblio-db.js
src/core/markdown.js
src/core/reindent.js
src/core/utils.js
src/core/webidl.js
src/core/xref.js
src/ui/search-specref.js
tests/spec/core/utils-spec.js

Closes https://github.com/w3c/respec/issues/2374

refactor: use Array@flat instead of utils@flatten

---

src/core/biblio.js
src/type-helper.d.ts

Would it make sense to add a global `.d.ts` file to annonate `Conf` type?

refactor(core/biblio): improve type support

---

src/core/xref.js

Related to https://github.com/marcoscaceres/respec.org/pull/62

fix(core/xref): adapt error hint URL to seach query

---

tools/release.js

Tried bumping version and found these 👀

fix(tools/release): Windows support

---

src/core/biblio-db.js

...and a fix: use array instead of a Set of objects

refactor(core/biblio-db): remove legacy warning

---

src/README.md

Typo in src/README.md

---

package-lock.json
package.json

chore(package): update rollup to version 2.0.2

---

assets/highlight.css

Changes:
- `#0184bb` to `#0b76c5`
- `#c18401` to `#9a6a01`
- `#4078f2` to `#336ae3`
- `#e45649` to `#ca4706`

fix(assets/highlight.css): improve color contrast

---

package-lock.json
package.json
tools/builder.js

Reduces W3C bundle size by 8KB

chore(tools/builder): minify CSS

---

src/w3c/headers.js
src/w3c/templates/sotd.js
tests/spec/w3c/headers-spec.js

fix(w3c/headers): indicate as recommended

---

src/core/inlines.js
src/core/render-biblio.js
tests/spec/core/inlines-spec.js

Closes https://github.com/w3c/respec/issues/2822

feat(core/inlines): allow custom text in inline cite

---

src/core/render-biblio.js
src/type-helper.d.ts

refactor(core/render-biblio): split long functions

---

assets/dfn-panel.css

As it breaks nu HTML validator

fix(assets/dfn-panel.css): remove scrollbar-width

---

src/w3c/templates/headers.js
tests/spec/w3c/headers-spec.js

Closes https://github.com/w3c/respec/issues/2828
Wiki: https://github.com/w3c/respec/wiki/modificationDate

feat(w3c/headers): add modificationDate config option

---

src/core/link-to-dfn.js

Splitting https://github.com/w3c/respec/pull/2508 into smaller parts..

refactor(core/link-to-dfn): extract findMatchingDfn function

---

src/core/utils.js
src/core/webidl.js
tests/spec/core/dfn-index-spec.js
tests/spec/core/dfn-spec.js
tests/spec/core/webidl-spec.js
tests/spec/core/webidl.html

From https://github.com/w3c/respec/pull/2844.
@saschanaz Can you validate that this is a correct test case?

fix(core/webidl): link Default toJSON with data-link-for

---

src/core/mdn-annotation.js
tests/spec/core/mdn-annotation-spec.js

Closes https://github.com/w3c/respec/issues/2860

feat(core/mdn-annotation): allow providing custom key

---

src/core/highlight-vars.js
tests/spec/core/highlight-vars-spec.js

Closes https://github.com/w3c/respec/issues/2866

fix(core/highlightVars): allow multiline variables

---

src/core/utils.js

This randomly bothered me :smile:

refactor(core/utils): de-duplicate code in showInlineError

---

.github/workflows/pr-push.yml

v2 is [claimed](https://github.com/actions/checkout/#whats-new) to be faster.
It is indeed faster! :shipit:

chore(ci): update checkout to v2

---

.github/workflows/pr-push.yml

See https://github.com/w3c/respec/pull/2872#issuecomment-630682553

chore(ci): cache ~/.npm instead of node_modules

---

.github/workflows/push.yml

Missed from https://github.com/w3c/respec/pull/2896

chore(ci/push): fix workflow, skip Chromium install

---

src/core/mdn-annotation.js

... and added typescript annotations
There is a scope for a large number of refactor/cleanups in this module. Should I do them here or separate PRs?

perf(core/mdn-annotation): avoid request to specmap.json

---

assets/mdn-annotation.css
src/core/mdn-annotation.js
tests/spec/core/mdn-annotation-spec.js

Note to reviewer:
- Commit log should help in review..
- Side-by-side diff is better here
- Ignore CSS changes for initial review

feat(core/mdn-annotation): use semantic markup, improve styles

---

src/core/xref.js
tests/spec/core/xref-spec.js

See https://github.com/w3c/manifest/pull/883#issue-424889006

fix(core/xref): give inline spec context least priority

---

src/core/dfn-panel.js
src/core/dfn-panel.runtime.js
tests/spec/SpecHelper.js
tests/spec/core/dfn-panel-spec.js
tools/builder.js

Cleanup of https://github.com/w3c/respec/pull/2820 as it had gotten too many changes already..

feat(core/dfn-panel): run in exported documents

---

assets/dfn-panel.css
src/core/dfn-panel.js
tests/spec/core/dfn-panel-spec.js

Closes https://github.com/w3c/respec/issues/2935

feat(core/dfn-panel): add marker if dfn is exported

---

src/core/mdn-annotation.js
tests/spec/core/mdn-annotation-spec.js

| before | after |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/8426945/83666749-0fd90580-a5eb-11ea-8aeb-80ead128e3df.png) | ![image](https://user-images.githubusercontent.com/8426945/83666768-18314080-a5eb-11ea-98f7-9104f04e7f16.png) |

fix(core/mdn-annotation): make marker size consistent

---

.eslintrc.json
package-lock.json
package.json
src/jsconfig.json

Closes #2947
Closes #2948 
Closes #2949 
Closes #2950 
Closes #2951 
Closes #2952 
Closes #2953

chore: update dependencies

---

src/core/issues-notes.js

refactor(core/issues-notes): rename hyperHTML to html

---

src/w3c/defaults.js
tests/spec/w3c/headers-spec.js

Fixes https://github.com/w3c/respec/issues/2904

fix(w3c/defaults): do not add W3C logo in unofficial specs

---

src/core/structure.js
tests/spec/core/structure-spec.js

Closes https://github.com/w3c/respec/issues/675
Found this useful while working on documentation website.

feat(core/structure): use data-max-toc to limit ToC per section

---

src/core/worker.js
worker/respec-worker.js

See https://github.com/w3c/respec/pull/2717#issuecomment-654163128

chore(core/highlight): remove .js extension to support brotli on server

---

src/core/markdown.js

Need to reuse this for https://github.com/w3c/respec/issues/3005#issuecomment-656100360

refactor(core/markdown): fix structure around processed element

---

.github/workflows/push.yml

Wait for https://github.com/marcoscaceres/respec.org/pull/95

chore(ci/push): report brotli size instead of gzip

---

src/core/utils.js
tests/spec/core/utils-spec.js

Fixes https://github.com/w3c/respec/issues/3021

fix(core/utils): case-insensitively match l10n language

---

src/core/structure.js
tests/spec/core/structure-spec.js

Closes https://github.com/w3c/respec/pull/2771

fix(core/structure): support more than 26 appendices

---

src/core/mdn-annotation.js
tests/spec/core/mdn-annotation-spec.js

Addressing feedback from @saschanaz (See https://github.com/w3c/respec/pull/2923#discussion_r433789098). Better late than never!

fix(core/mdn-annotation): improve engine support message

---

src/core/utils.js
tests/spec/core/utils-spec.js

Fixes https://github.com/w3c/respec/issues/3032

fix(utils/fetchAndCache): make Expires header locale independent

---

src/core/dfn.js
tests/spec/core/link-to-dfn-spec.js

Closes https://github.com/w3c/respec/issues/3037

feat(core/dfn): treat internal slots as idl

---

src/w3c/templates/headers.js

Closes https://github.com/w3c/respec/issues/3052

refactor(w3c/templates/headers): use l10n for headings

---

examples/basic.built.html
examples/basic.html
examples/starter.html
src/core/dfn-index.js
tests/spec/core/data-type-spec.js
tests/spec/core/dfn-finder-spec.js
tests/spec/core/dfn-index-spec.js
tests/spec/core/link-to-dfn-spec.js
tests/spec/core/markdown-spec.js
tests/spec/core/simple.html
tests/spec/core/webidl-spec.js
tests/spec/core/webidl.html

See https://github.com/heycam/webidl/pull/906
~@saschanaz should we wait for https://github.com/w3c/webidl2.js/pull/486 first? See tests _fail properly_ and then merge this, or fine to merge?~
Waiting on https://github.com/w3c/respec/pull/3078

chore: rename WebIDL void to undefined

---

package-lock.json
package.json
src/core/best-practices.js
src/core/data-tests.js
src/core/render-biblio.js
src/dini/conformance.js
src/dini/templates/headers.js
src/geonovum/conformance.js
src/w3c/conformance.js
src/w3c/templates/cgbg-headers.js
src/w3c/templates/cgbg-sotd.js
src/w3c/templates/headers.js
src/w3c/templates/sotd.js

Closes https://github.com/w3c/respec/pull/3095

style: update prettier and fix prettier issues

---

assets/respec.css
assets/ui.css

We removed dfn-list some time ago..

chore(assets/respec.css): remove unused CSS for dfn-list

---

assets/dfn-panel.css
src/core/dfn-panel.js
tests/spec/core/dfn-panel-spec.js

Closes https://github.com/w3c/respec/issues/3156
Demo: https://deploy-preview-3157--respec-pr.netlify.app/

feat(core/dfn-panel): add link to jump to IDL fragment

---

tools/respecDocWriter.js

Changes already approved in https://github.com/w3c/respec/pull/3173

chore(tools/respecDocWriter): remove unused code

---

package-lock.json
package.json

We've https://github.com/w3c/respec-hljs for this.

chore(deps): remove unused highlight.js

---

tests/spec/core/xref-spec.js

Data changed with https://github.com/sidvishnoi/respec-xref-route/pull/70

tests(xref): update test data

---

package-lock.json
package.json
tests/spec/core/markdown-spec.js
tools/dev-server.js

chore(deps): update dependencies

---

.github/workflows/pr.yml
.github/workflows/push.yml

See https://github.com/w3c/respec/pull/3306

fix(ci): manually set locale to workaround Firefox bug

---

examples/starter.html

This was quite out of date and had a few errors...

fix(examples/starter.html): user newer syntax/features

---

src/core/base-runner.js
src/core/caniuse.js

Closes https://github.com/w3c/respec/issues/2981
(Review commit by commit)

feat(core/base-runner): add a prepare pass

---

tests/test-build.js

refactor(tests/test-build): use fs.promises instead of promisify

---

src/core/anchor-expander.js
tests/spec/core/anchor-expander-spec.js

fix(core/anchor-expander): convert nested header links to spans

---

tools/respec2html.js
tools/respecDocWriter.js

Extracted from https://github.com/w3c/respec/pull/3342. Will prettify errors in next PR.

refactor(tools/respec2html): add a Logger class for logs

---

src/core/github.js
tests/spec/core/github-spec.js

Closes #3362 
Regression from #3334

fix(core/github): extraneous : in places

---

js/deps/rollup.config.js
package-lock.json
package.json
tools/builder.js

That explains why we never receive updates for them :smile:

chore(deps-dev): use updated rollup plugins

---

assets/ui.css
src/core/biblio.js
src/core/render-biblio.js
src/ui/search-specref.js
src/ui/search-xref.js

See https://github.com/marcoscaceres/respec.org/pull/180

refactor(ui/search-specref): embed iframe from respec.org

---

karma.conf.js

Cleanup karma.conf.js:
- Merge and reorder `files` patterns
- Remove comments as they're accessible via "jump to dfn" or karma website
- Add type checking
(Cleanup in preparation of unit testing support)

chore(karma.conf.js): cleanup

---

tools/dev-server.js

Karma, as it should've been.
In preparation of unit test support...

refactor(tools/dev-server): add promisified KarmaServer

---

src/w3c/headers.js

fix(w3c/headers): wgPatentPolicy may be falsy

---

tools/builder.js
tools/dev-server.js

Should've probably sent with https://github.com/w3c/respec/pull/3454

chore(tools/*): disallow unknown options

---

src/core/webidl.js

Fixes https://github.com/w3c/respec/issues/3442

fix(core/webidl): ensure loading of webidl.css

---

src/core/dfn-panel.js
src/core/dfn-panel.runtime.js
tests/spec/core/dfn-panel-spec.js

fix(core/dfn-panel): don't add  panel for data-cite

---

src/core/data-cite.js

Extracted from https://github.com/w3c/respec/pull/3495

refactor(core/data-cite): use switch case in linkElem

---

src/core/templates/show-people.js

Fixes https://github.com/w3c/respec/issues/3501

fix(templates/show-people): remove extraneous WS from ORCID link

---

src/core/linter-rules/wpt-tests-exist.js
tests/unit/core/linter-rules/wpt-tests-exist-spec.js

fix(lint/wpt-tests-exist): make separate warnings

---

tests/spec/core/biblio-db-spec.js
tests/spec/core/data-cite-spec.js
tests/spec/core/data-include-spec.js
tests/spec/core/dfn-spec.js
tests/spec/core/idl-index-spec.js
tests/spec/geonovum/style-spec.js
tests/spec/w3c/headers-spec.js
tests/spec/w3c/seo-spec.js
tests/spec/w3c/style-spec.js

Changed toBe(null) to toBeNull()

---

src/core/github.js

fix(core/github): file an issue, not bug

---

src/core/issues-notes.js
tests/spec/core/issues-notes-spec.js

Fixes https://github.com/w3c/respec/issues/3584

fix(core/issues-notes): invalid aria-label

---

src/core/inline-idl-parser.js
tests/spec/core/xref-spec.js

fix(core/inline-idl-parser): link interface contants

---

src/core/inlines.js
tests/spec/core/inlines-spec.js

fix(core/inlines): support [=deep/for/links=]

---

src/styles/respec.css.js

style(styles/respec): whitespace fixes

---

src/styles/caniuse.css.js
src/styles/highlight.css.js
src/styles/issues-notes.css.js
src/styles/webidl.css.js

Closes #3604 
Closes #3602 
Closes #3601 
Plus other changes by prettier, except top-level indentation.

style(styles/*): run through prettier

---

src/styles/caniuse.css.js
src/styles/dfn-panel.css.js

The cursor is confusing, as you can't click on the versions.

fix(styles/caniuse): use cursor: default

---

tests/karma.conf.base.js
tests/spec/karma.conf.js
tests/unit/karma.conf.js
tools/dev-server.js

Fixes https://github.com/w3c/respec/issues/3566
@marcoscaceres can you test your workflow locally? CI is OK.

chore(tools/dev-server): run unit tests, integration tests together

---

tests/spec/core/xref-spec.js

fix(tests/xref): CSS Values now level 4

---

src/w3c/defaults.js
src/w3c/headers.js
tests/spec/w3c/headers-spec.js

fix(w3c): ensure w3c logo is present on TR docs

---

.github/workflows/pr.yml
.github/workflows/push.yml
.github/workflows/regressions.yml

Instead of actions/cache, use recently added cache input of setup-node.
And also use shorter YAML syntax, for clarity.

chore(ci): use cache option of setup-node

---

tests/spec/core/xref-spec.js

This test has given us enough grief... it's time for it to go away.

tests(core/xref-spec): remove problematic test

---

package-lock.json
package.json
src/core/dfn-validators.js
src/core/import-maps.js
src/type-helper.d.ts
tests/karma.conf.base.js
tests/spec/core/validators-spec.js

Part 1 of adding support for definition types. 
This introduces the type validators.

feat(core/dfn-validators): add dfn type validators

---

src/w3c/headers.js

feat(w3c/headers): change updateableRec to CSS updateable-rec

---

src/w3c/defaults.js
src/w3c/headers.js
tests/spec/w3c/headers-spec.js

fix(w3c): show logos for w3c notes

---

src/core/caniuse.js
tests/spec/core/caniuse-spec.js

Now exports caniuse data to TR docs.

feat(core/caniuse): snapshot caniuse data

---

src/core/examples.js
tests/spec/core/examples-spec.js

Closes https://github.com/w3c/respec/issues/3784

fix(core/examples): don't add number to id when possible

---

src/w3c/headers.js
src/w3c/templates/sotd.js

fix(w3c): remove team-SUBM status

---

src/w3c/templates/headers.js

fix(w3c/headers): register 'beforesave' if actually run

---

src/w3c/templates/sotd.js
tests/spec/w3c/headers-spec.js

Aligns Respec with pubrules:
-  Note https://www.w3.org/pubrules/doc/rules/?profile=NOTE#stability
- REC https://www.w3.org/pubrules/doc/rules/?profile=REC#stability

Fixes Note and REC stability boilerplates

---

src/w3c/abstract.js
tests/spec/w3c/abstract-markdown.html
tests/spec/w3c/abstract-spec.js

fix(w3c/abstract): find abstract from markdown

---

src/w3c/headers.js
src/w3c/seo.js
tests/spec/w3c/seo-spec.js

fix(w3c/seo): update list of docs that required canonical link

---

src/styles/respec.css.js

fix(styles/respec.css): margin space

---

src/w3c/templates/headers.js

Added the German translation for multiple_alternates.

add German translation for multiple_alternates

---

src/aom/conformance.js
src/core/best-practices.js
src/core/dfn-index.js
src/core/figures.js
src/core/render-biblio.js

fix: create headings as h1

---

tests/spec/core/seo-spec.js

I don't know what we were thinking here lol!

tests(core/seo): fix racy tests

---

examples/basic.built.html
examples/basic.html

Fixes warnings shown on CI and and release.

docs(examples/basic): silence priv/sec error

---

src/w3c/templates/cgbg-headers.js
src/w3c/templates/headers.js
tests/spec/w3c/headers-spec.js

Feedback links are missing from WICG docs.

fix(w3c/cgbg-headers): show Feedback: links

---

src/core/ui.js
src/core/xref.js

<del>Not perfect... but at least it renders the list now. </del>
Seem to hold now for the cases I tested... works fine in terminal too.

fix(core/ui): check if should inline markdown or not

---

src/styles/respec.css.js

fix(styles/respec.css): better align section marker

---

src/w3c/templates/cgbg-headers.js
src/w3c/templates/headers.js
tests/spec/w3c/headers-spec.js

Oops, the subtitle was not being handled correctly... cgbg template strikes again :D

fix(w3c/cgbg-headers): handle subtitle correctly

---

src/w3c/headers.js
tests/spec/SpecHelper.js
tests/spec/w3c/headers-spec.js

feat(w3c/headers): error if w3cid is missing for recTrack docs

---

src/core/caniuse.js
src/styles/caniuse.css.js
tests/data/caniuse/FEATURE.json
tests/karma.conf.base.js
tests/spec/core/caniuse-spec.js

Closes #4042
With its breathtaking new design, the all new caniuse header is now 30% more flexy, conveying more information in fraction of the space. It's the best caniuse header we've ever built.

BREAKING CHANGE(core/caniuse): new browser compat header

---

src/core/caniuse.js
tests/spec/core/caniuse-spec.js

The icons might be moving to this URL instead....

fix(core/caniuse): update browser logos URL

---

src/styles/dfn-panel.css.js

Fixes https://github.com/w3c/respec/issues/4144

fix(styles/dfn-panel): quote font-family name to pass CSS validator

---

src/core/issues-notes.js

Fixes https://github.com/w3c/respec/issues/4139

fix(core/issues-notes): make label text color more accessible

---

src/styles/issues-notes.css.js

fix(styles/issues-notes): add 'closed' marker to closed issues

---

src/styles/ui.css.js

Fixes #4193 
Not sure if this requires a test and if so would it be under `tests/spec/core/ui-spec.js`?

fix(styles/ui): respect prefers-reduced-motion, cooler loading animation

---

src/core/caniuse.js
tests/spec/core/caniuse-spec.js

Fixes https://github.com/w3c/respec/issues/4091

fix(core/caniuse): set default browsers

---

src/core/algorithms.js
tests/spec/core/algorithms-spec.js

Closes https://github.com/w3c/respec/issues/4278

feat(core/algorithms): link `Assert:` to Infra spec dfn

---

src/w3c/templates/sotd.js

fix(w3c/sotd): remove stray trailing whitespace

---

tests/spec/SpecHelper.js
tests/spec/core/linter-rules/informative-dfn-spec.js

tests(linter/informative-dfn): update xref data

---

src/w3c/style.js

Fixes https://github.com/w3c/respec/issues/4411

fix(w3c/style): use correct stylesheet for Member-SUBM

---

src/w3c/headers.js
tests/spec/w3c/headers-spec.js

Fixes https://github.com/w3c/respec/issues/4412

fix(w3c/headers): fix "This Version" link for "Member-SUBM"

---

src/core/inlines.js

fix(core/inlines): fix RFC2119 `MAY` regex

---

src/core/inlines.js
src/core/link-to-dfn.js
tests/spec/core/link-to-dfn-spec.js

feat(core/link-to-dfn): support abstract-op dfn linking

---

src/core/dfn-index.js
tests/spec/core/dfn-index-spec.js

Fixes https://github.com/w3c/respec/issues/4437

fix(core/dfn-index): ignore spec titles from external index

---

src/core/data-cite.js
src/core/dfn-index.js
tests/spec/core/dfn-index-spec.js

Fixes https://github.com/w3c/respec/issues/4438

fix(core/dfn-index): include `dfn[data-cite]` in external index

---

src/core/render-biblio.js
src/w3c/headers.js
src/w3c/seo.js
tests/spec/w3c/headers-spec.js
tests/spec/w3c/seo-spec.js
tests/spec/w3c/style-spec.js

Removing PER status as it no longer exists.

---

src/core/highlight-vars.js
tests/unit/core/highlight-vars-spec.js

This matches what bikeshed does https://speced.github.io/bikeshed/#var-and-algorithms

fix(core/highlight-vars): scope highlighted var to `.algorithm` container

---

package.json
pnpm-lock.yaml
src/core/github.js
src/core/issues-notes.js
src/core/structure.js
src/w3c/headers.js
src/w3c/templates/headers.js
src/w3c/templates/sotd.js
tests/spec/w3c/headers-spec.js

1. Closes #4581
2. Closes #4583

chore(deps): update dependencies, pnpm, prettier

---

src/type-helper.d.ts
src/w3c/group.js

refactor(w3c/groups): improve docs + typescript

---

src/core/location-hash.js
tests/spec/core/location-hash-spec.js

Found these could time out on me when working over crappy internet.

refactor(core/location-hash): improve docs and TS usage

---

src/core/markdown.js
src/core/reindent.js
src/core/ui.js
src/core/utils.js

refactor(core/reindent): move reindent to utils.

---

package.json
pnpm-lock.yaml
src/core/markdown.js
tests/spec/core/markdown-spec.js

Closes https://github.com/w3c/respec/issues/4444

chore(deps): update marked

---

src/w3c/style.js

Extracted from https://github.com/w3c/respec/pull/3236

refactor(w3c/style): extract into functions, simplify code, nits

---

profiles/aom.js
profiles/dini.js
profiles/geonovum.js
profiles/w3c.js
src/core/dfn-contract.js
src/core/dfn.js

Fixes https://github.com/w3c/respec/issues/4323
Closes https://github.com/w3c/respec/pull/4344 (supersedes)

fix(core/dfn): add contractDefaults, dfnPointers before running linters

---

src/w3c/style.js

See https://github.com/w3c/htmldiff-ui/pull/13/

fix(w3c/styles): add `meta[type=color-scheme]` with `darkMode`

---

src/core/xref.js
tests/data/xref/refs.json

Based on https://github.com/w3c/respec-web-services/pull/178

fix!(core/xref): use new `/xref/search` endpoint

---

src/core/post-process.js
src/core/pre-process.js
src/core/utils.js
tests/spec/core/pre-process-spec.html
tests/spec/core/pre-process-spec.js

Closes https://github.com/w3c/respec/issues/4560

feat(core/{pre,post}-process): add `showWarning`, `showError` utils

---

src/type-helper.d.ts

fix(type-helper.d.ts): remove def of darkMode

---

package.json
pnpm-lock.yaml

1. Closes #4699
2. Closes #4701 
3. Closes #4702 
4. Closes #4703

chore(deps): update dependencies, pnpm

---

src/w3c/templates/sotd.js

fix(w3c/sotd): correct fragment identifier for proposed corrections

---

src/core/inlines.js

Fixes https://github.com/speced/respec/issues/4957

fix(core/inlines): don't process text in inline script, style

---

worker/respec-highlight.js

See https://github.com/speced/respec/issues/4934#issuecomment-2808725400

feat(respec-highlight): add yaml syntax highlighting
