speced/respec

js/w3c/permalinks.js
tests/spec/w3c/permalinks-spec.js

Issue #389 reported that the content attribute for permalinks was
being incorrectly populated with embedded apostrophes.  This change
escapes those.

Ensure that apostrophes in headers are escaped

---

js/w3c/headers.js
tests/spec/w3c/headers-spec.js

The new [automated publication workflow](http://www.w3.org/2014/08/pubworkflow.html) will rely on a new feature in [specberus](https://github.com/w3c/specberus/#emitting-metadata-about-the-document) to look up editors by their W3C ids.
This patch reads (optionally) that information from the document configuration

Allow to specify editors id in doc configuration

---

README.md
examples/respec-debug.js
js/ui/search-specref.js

As nodejitsu's been acquihired, they're closing down their service in about half a year, so went ahead and mirrored this on heroku until I figure out how to properly send HTTPS over a full domain name.

Update ReSpec to heroku URL.

---

js/core/webidl-oldschool.js

WebIDLProcessor.prototype.writeAsHTML is very long. This change split the function, to make it easy to read and modify.
This is a preliminary change for https://github.com/w3c/respec/issues/361.

Cleanup write as html

---

js/core/css/webidl-oldschool.css
js/core/templates/webidl/maplike.html
js/core/webidl-oldschool.js
tests/spec/core/webidl.html

This change add support for "[readonly] maplike<K, V>;" in an interface as
the grammar is recently added to WebIDL. #361

Add maplike support.

---

js/core/biblio.js

See https://webbluetoothcg.github.io/web-bluetooth/ for a spec broken by this issue, with the error message:
> Mixed Content: The page at 'https://webbluetoothcg.github.io/web-bluetooth/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://specref.jit.su/bibrefs?refs=RFC4122,BLUETOOTH41,BLUETOOTH-ASSIGNED-B…BLUETOOTH-ASSIGNED,BLUETOOTH-SUPPLEMENT4,dom,HTML,powerful-features,WebIDL'. This request has been blocked; the content must be served over HTTPS.

Fetch specref.jit.su over HTTPS

---

js/profile-w3c-common.js
js/ui/dfn-list.js

This is a simplistic implementation to add a UI component to show a list of definitions from the document.
I suspect that there will be scrolling issues in the modal, and it would be nice to link to the source of the definition, but this likely requires some magic I'm not familiar with to get out of the model and relocate to the definition.
I've often lost track of all of the definitions in a document, or need a way to find definitions in some other companion document for which I might not be an editor, so having a UI to provide a quick reference to definitions may be more generally useful. Of course, there could also be a "Table of Definitions" which could be added to the document, similar to a table of figures or the table of contents, but this would not be commonly used, as it's mostly …

Add UI to show a list of definitions.

---

js/core/templates/webidl-contiguous/dict-member.html
js/core/webidl-contiguous.js
js/webidl2.js
tests/spec/core/webidl-contiguous-spec.js
tests/spec/core/webidl-contiguous.html

This imports webidl2.js from darobin/webidl2.js#25, which hasn't been merged yet. We should probably wait to merge this PR until the current PRs from that repo have been accepted, and then re-import webidl2.js from there.
Also note @dontcallmedom's https://github.com/dontcallmedom/respec/commit/3bbe54f9adac0d72b962c836908f64901c80e9b9, which fixes this in oldschool mode. Since oldschool mode isn't deprecated yet, we should probably take both.

Support required dictionary members in contiguous-idl mode.

---

js/core/issues-notes.js
tests/spec/core/webidl-contiguous-spec.js
tests/spec/core/webidl-contiguous.html

Cloning the nodes breaks references in conf.definitionMap, so the <dfn>s that
link-to-dfn.js assigns IDs weren't the ones that actually wind up in the result
document.

Avoid cloning nodes in issues and notes.

---

js/core/link-to-dfn.js
js/core/templates/webidl-contiguous/attribute.html
js/core/templates/webidl-contiguous/callback.html
js/core/templates/webidl-contiguous/const.html
js/core/templates/webidl-contiguous/dict-member.html
js/core/templates/webidl-contiguous/dictionary.html
js/core/templates/webidl-contiguous/enum.html
js/core/templates/webidl-contiguous/exception.html
js/core/templates/webidl-contiguous/field.html
js/core/templates/webidl-contiguous/interface.html
js/core/templates/webidl-contiguous/method.html
js/core/templates/webidl-contiguous/serializer.html
js/core/templates/webidl-contiguous/typedef.html
js/core/utils.js
js/core/webidl-contiguous.js
tests/spec/core/dfn-spec.js
tests/spec/core/webidl-contiguous-spec.js
tests/spec/core/webidl-contiguous.html

* `[link-for]` used to break non-IDL links in its scope.
* It was difficult to link to members when their interface wasn't immediately obvious. Now `<a>Interface.member</a>` works.
* Now links point to declarations if no definition is available.
* Any `<code>` definition now causes its links to also be `<code>`.
This builds on #432.

Improve linking to and around WebIDL terms

---

js/core/webidl-contiguous.js
tests/spec/core/webidl-contiguous-spec.js
tests/spec/core/webidl-contiguous.html

This replaces `<dfn for="dotted" title="name">dotted.name</dfn>`.

Let people write `<dfn>dotted.name</dfn>` to define IDL members.

---

README.md

The new URL is: http://jasmine.github.io/

Update Jasmine External Link

---

examples/basic.html
js/core/figures.js
js/core/issues-notes.js
js/core/structure.js
js/profile-w3c-common.js
js/w3c/abstract.js
js/w3c/headers.js
js/w3c/l10n.js
js/w3c/templates/cgbg-headers.html
js/w3c/templates/cgbg-sotd.html
js/w3c/templates/headers.html
js/w3c/templates/sotd.html

Support localising string that are produced by the system, include Chinese (Simplified) translations, and start making use of them.
We have Chinese users for this.

L10N support + Simplified Chinese

---

js/core/contrib.js
js/profile-w3c-common.js

Fetches names of contributors from github and uses them to fill
in the content of elements with key identifiers:
`#gh-commenters`: people having contributed comments to issues.
`#gh-contributors`: people whose PR have been merged.
Spec editors get filtered out automatically.
/cc @marcoscaceres

This module simplifies acknowledging contributions made through GitHub.

---

js/core/css/webidl-oldschool.css
js/core/templates/webidl/iterable.html
js/core/webidl-oldschool.js
tests/spec/core/webidl-oldschool-spec.js
tests/spec/core/webidl.html

Add support for iterable to oldschool IDL
Also add missing tests for maplike

Add support for iterable to oldschool IDL

---

js/core/issues-notes.js

The current code creates "issue-undefined" when data-number is not set; when more than one of these exists, it creates invalid code, e.g. https://travis-ci.org/w3c/webrtc-pc/builds/67274495

Avoid undefined ids for issues

---

js/core/structure.js

We're getting problems from ReSpec generating spurious IDs, notably on `section` when the `hN` already has one. This should eliminate that behaviour.

don't generate a section ID if the heading has one

---

js/core/dfn.js
js/core/link-to-dfn.js
js/core/utils.js
tests/spec/core/dfn-spec.js
tests/spec/core/utils-spec.js

Added handling for aliases as per Bikeshed.  Specifically,
`<dfn title="foo|bar">my term</dfn>` is able to be referenced with
things like `<a>foo</a>` or `<a title="bar">my term</a>` or
`<a>bar</a>`.
This also ensures that the generated output is compatible with the
Bikeshed contract for external processors.  There is more work to do to
get that complete, but this is a good first step.
This is in general in reference to issue #344

Implemented aliases for definitions

---

js/core/utils.js
tests/spec/core/utils-spec.js

Some add-on code (used by PFWG and WPIG currently) call this utility
method on dfn elements again to get the title.  If there are aliases
for a dfn, these are moved into data-lt during the definition
processing phase, so a subsequent call will return the wrong list in
that case.  This fixes that (and improves the tests so we know it
works).

Makes getDfnTitles work when called again

---

js/core/utils.js
tests/spec/core/utils-spec.js

Addresses concerns from the user community about the use of the 'lt' attribute because it does 
not validate.

Change to prefer data-lt for referring to link-titles

---

js/w3c/headers.js
js/w3c/templates/headers.html
js/w3c/templates/sotd.html
tests/spec/w3c/headers-spec.js

This is a proposed fix for #458.
When the spec status is "Member-SUBM" or "Team-SUBM", ReSpec expected a
"Previous version" link that does not mean anything in this context, did not
set the proper companion logo next to the W3C logo and did not include the
right Status of This Document boilerplate.
Please note that the links in the SoTD boilerplate for Member submissions still
contain "@@@". That is normal since these links are set by W3C Team right before
the submissions is accepted, and cannot be computed a priori.
ReSpec still conserves the default copyright in that case, but users simply
have to use "overrideCopyright" to override that setting.
This commit contains a few regression tests.

Improved Member-SUBM and Team-SUBM spec status support

---

js/core/webidl-contiguous.js

This should address issue #464, but I don't have any specs with
webidl in them to verify that!  Can someone please take a close look?

Changed webidl generation to use data-lt attribute

---

js/w3c/headers.js
js/w3c/templates/sotd.html
tests/spec/w3c/headers-spec.js

cf https://github.com/w3c/specberus/blob/master/lib/rules/sotd/pp.js#L23

Adapt to specberus expectations for joint publications

---

js/core/include-config.js

(at least) when used with phantomjs, respec now fails due to the respec config export which tries and fails to serialize respecConfig.definitionMap which itself contains a list of DOM elements (non JSON-serializable in phantomjs)
This patches replaces the DOM content with the id of the relevant definition.

Fix config export with non-serializable content definitionMap

---

js/core/base-runner.js
js/core/include-config.js
tests/spec/core/include-config-spec.js

For whatever reason, .innerText means that when .toString() is called within the output function, the inner text doesn't show up. However, using .innerHTML means that it does show up.

using .innerHTML makes JSON reappear (closes #478)

---

js/ui/save-html.js

#487 broke respec2html.js because phantom apparently got confused with function binding (not sure why); this fixes this.
Incidentally, it would be great if running respec2html.js was part of the test suite.

Fix save-ui for respec2html

---

js/core/base-runner.js

ReSpec should not swallow the error stacks. Now we can see where errors happen, so long as an error is thrown.

Small improvement to error reporting

---

js/core/base-runner.js
js/core/include-config.js
js/profile-w3c-common.js

* exporting the intial config was having issues if the userConfig was before or after the respec.js file. This hopefully fixes that now.

Export config fixup

---

js/core/webidl-contiguous.js

This prevents respec from generating whitespaces in HTML id for methods.
e.g
https://w3c.github.io/requestidlecallback/#idl-def-window-requestidlecallback(idlerequestcallback,optional-unsigned%20long)

Prevent whitespaces in methodObject.idlId

---

js/w3c/headers.js
js/w3c/templates/headers.html
tests/spec/w3c/headers-spec.js

This allow an editor to select the W3C's software and document license.

Default to new doc+software license (closes #505)

---

js/core/examples.js
js/core/issues-notes.js
js/core/structure.js
js/core/webidl-contiguous.js
js/w3c/aria.js
js/w3c/headers.js
js/w3c/style.js
js/w3c/templates/cgbg-headers.html
js/w3c/templates/headers.html
tests/spec/core/structure-spec.js

Simple changes to load the new stylesheets and
implement some basic changes that make them work.
To enable in your respec document, set
useExperimentalStyles: true,
in your Respec Configuration area.
In response to issue #520

Made some initial changes to test new styles

---

js/w3c/style.js

Should replace https://github.com/w3c/respec/pull/528
@halindrome @marcoscaceres @tripu

Use www.w3.org for experimental style sheets

---

js/w3c/style.js

Missing the protocol otherwise. sorry.

Missing the protocol

---

js/core/webidl-oldschool.js

The WebIDL support creates `id` from the name of the attributes. If these attributes contain digits in their names, [`setID`](https://github.com/w3c/respec/blob/develop/js/core/webidl-oldschool.js#L121) removes them.
This is a problem for specs like [Vehicule Data](https://w3c.github.io/automotive/vehicle_data/data_spec.html). For instance:
```
readonly        attribute float?          batteryTempT0;
readonly        attribute float?          batteryVoltageT120;
readonly        attribute float?          batteryTempT120;
readonly        attribute float?          batteryVoltageESD30;
readonly        attribute float?          batteryTempESD30;
readonly        attribute float?          batteryVoltageESD450;
readonly        attribute float?          batteryTempESD450;
readonly        attribute …
```

WebIDL: setID removes digits from the id

---

tools/respec2html.js

Add --exclude-script to respec2html

---

js/core/webidl-contiguous.js

Breaks WebIDL Contiguous mode in Chrome/Edge
cf https://github.com/w3c/presentation-api/issues/232#issuecomment-168742148

[Urgent] Avoid assigning property to a string object (non-strict compatible)

---

js/core/templates/webidl-contiguous/enum-item.html
js/core/webidl-contiguous.js
tests/spec/core/webidl-contiguous-spec.js
tests/spec/core/webidl-contiguous.html

@dontcallmedom's recent commits were not enough to fix the definition of enumeration items. In practice, the template generated references using an "idl-def-" prefix, preserving the case and using a dotted notation, while definitions were made with a "dom-" prefix, lower case characters, and dash-separated parts.
This commit ensures that the references produced in the WebIDL definition correctly use the "dom-" prefix. It includes a regression test.

Fix enumeration values references in WebIDL contiguous mode

---

js/core/templates/webidl-contiguous/attribute.html
js/core/webidl-contiguous.js
tests/spec/core/webidl-contiguous-spec.js

It's already counted in qualifiers

Optimize space used for attributes in WebIDL contiguous

---

js/w3c/templates/sotd.html
tests/spec/w3c/headers-spec.js

At the request of @michael-n-cooper I added the
respec option overrideStatus.  If this option is true,
then the paragraph that starts "This document was published by..."
will be omitted from the generated output of the SotD.  Apparently
some working groups object to some of the wording and want to provide
their own.

Added support for overriding the publication status

---

js/profile-w3c-common.js
js/w3c/fixup.js
js/w3c/headers.js

- removed width = content-width from viewport
- add fixup.js

Align new TR design with latest requirements

---

js/w3c/fixup.js

See:
* [The error in the list](https://lists.w3.org/Archives/Public/public-tr-notifications/2016Feb/0034.html)
* [The message dumped in the spec produced (&ldquo;SyntaxError: Parse error&rdquo;)](https://labs.w3.org/spec-generator/?type=respec&url=https://w3c.github.io/preload/?specStatus=WD;shortName=preload;useExperimentalStyles=false)
* [This condition, which is always `true`](https://github.com/w3c/respec/blob/develop/js/w3c/fixup.js#L32)

Fix logic in <script src="fixup.js">

---

js/core/biblio.js
tests/SpecRunner.html
tests/spec/core/biblio-spec.js
tests/specifications/publishers.html

Publishers now show up when available in a bibliographical reference, after the author like so...

Teach ReSpec's references about publishers (closes #518)

---

tests/headless.js

This is causing headless.js to fail unnecessarily.

stop headless.js testing basic.built.html

---

tests/headless.js

These tests take about 30 seconds to run, so it's nice to see what is going on.

Improved progress reporting

---

js/w3c/templates/sotd.html
tests/.jshintrc
tests/spec/w3c/headers-spec.js

Bug291 no rec track should add note

---

js/core/examples.js
js/core/issues-notes.js
js/core/rdfa.js
js/core/structure.js
js/core/webidl-contiguous.js
js/w3c/aria.js
tests/spec/core/examples-spec.js
tests/spec/core/highlight-spec.js

Ensured that all of the experimental style code
is enabled all the time now that old styles are not
supported.
Replaces #588 - that wasn't going to merge cleanly.

Re-did style changes

---

js/w3c/style.js
tests/spec/w3c/style-spec.js

The requisite styles and logos are already in the
new location - this just enables their use.  
This supercedes PR #579

Code to switch CG and BG reports to new styles

---

tests/headless.js

Reverts some stuff that was already in the original version which I accidentally took out. At least we will be able to see now what is going on.

Fix (headless.js): pipe child stdout and stderr to parent

---

js/w3c/templates/cgbg-headers.html
js/w3c/templates/headers.html

Should probably be automatically switchable with the use
of useExperimentalStyles but that's not todays problem.
This should fix issues with passing pubrules.

Changed logo path to use new style location

---

tools/respec2html.js

Otherwise spec-generator can't generate properly the clipboard-apis spec.

Javascript errors shouldn't appear in the output

---

js/ui/save-html.js

If there is a toc-nav node when saving a snapshot, remove it.  It is not
part of the document. It was added by fixup.js.
Should address #644

Added code to remove toc-nav node (closes #644)

---

package.json
tools/release.js

* Adds epipebomb package, which swallows EPIPE errors.
* Adds a default timeout to `toExecPromise`, and the ability to override it.
* Increases timeout for npm publish.

Fix (release.js): Protect against EPIPE bombs from npmjs (closes #645).

---

js/w3c/templates/sotd.html
tests/spec/w3c/headers-spec.js

To fix issue #653.  This puts everything back the way it was.  'cause notes dont pass pubrules now.

Put note text back the way it was.

---

js/core/webidl-oldschool.js

Warn that webidl-oldschool is deprecated (#395)

---

js/ui/save-html.js

As mentioned in https://github.com/w3c/tr-design/pull/91#issuecomment-208467559, the generated snapshot shouldn't add the class 'toc-sidebar' to the `<body>`. It's added by JS only.
Shoud fix #644

Remove class 'toc-sidebar' from <body> when generating a snapshot

---

tests/headless.js

Feat (headless.js): improved progress reporting.

---

js/core/respec-ready.js
js/profile-w3c-common.js
tests/spec/core/ready-promise-spec.js
tools/respecDocWriter.js

Fix(respec-ready): s/respectIsReady/respecIsReady/ typo

---

js/core/beautify-options.js
js/core/css/github.css
js/profile-w3c-common.js
package.json
tools/builder.js

* adds to package dependencies: highlight.js and jsbeautifier
* adds default options for beautifier (beautify-options.js)
* tells builder to include highlighter and beautifier
* Sets appropriate paths in profile-w3c-common.js

Feat(global): add hightlighter and beautifier as deps

---

js/core/css/respec2.css

Context: the syntax highlighter uses ".hljs" as its CSS class - but the syntax highlighting themes all have their own custom backgrounds. This makes specs look ugly, so I'm forcing ReSpec to set the background to transparent.

Fix(respec2.css): Override code highlighter background

---

js/core/utils.js
tests/spec/core/utils-spec.js

* Fixes some edge cases that I missed previously for markdown.

Fix(utils): correctly calculate leftPad

---

js/core/markdown.js
karma.conf.js

Here we actually start teaching the markdown parser how to highlight markdown. This means we can do cool things like triple back tick  + language detection, just like in Github.

Feat(markdown): teach markdown how to highlight code

---

js/core/utils.js
tests/spec/core/utils-spec.js

Utility function that allows swapping a Node from one document to another. Useful for various incoming improvements.

Feat(utils): add makeOwnerSwapper()

---

js/core/utils.js
tests/.jshintrc
tests/spec/SpecHelper.js

Reduces jQuery dependency to just a polyfill for .append()

Fix (SpecHelper): reduce dependece on jQuery

---

js/core/markdown.js
js/core/utils.js
tests/spec/core/utils-spec.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/respec/785)

Fix whitespace issues

---

js/core/markdown.js
tests/spec/core/markdown-spec.js

Forgot to deal with spaces 👍 Serves me right for not adding test cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/respec/787)

Fix(markdown): Space before quote (closes #786)

---

js/core/pubsubhub.js
tools/builder.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/respec/790)

Fix uglify

---

js/ui/save-html.js

Changed the default URI for the diff tool to use https.
Addresses issue #808
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/respec/813)

Changed default diff tool URI to use https

---

package.json
tools/respec2html.js

V3 of command-line-args was a breaking change. Update fixes issues and makes a few enhancements.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/respec/815)

Feat(respec2html): upgrade to command-line-usage V3

---

js/core/base-runner.js
js/core/biblio.js
js/core/css/github.css
js/core/highlight.js
js/core/markdown.js
js/deps/highlight.js
js/profile-w3c-common.js
karma.conf.js
package.json
tests/spec/core/biblio-spec.js
tools/builder.js

hightlight.js is intended to be built and bundled. Previously, we were
using a pre-built version of hightlightjs. However, the bundle included
all the language options, which bloated ReSpec significantly.
This new version now downloads the hightlighter repo and builds a
custom highlighter specifically for ReSpec using HTML/XML, JS, CSS, HTTP and
markdown as options.
It also now includes highlight.js via a symlink to the generated file.
Additionally, I added an `npm run build` script, which builds both ReSpec
and the highlighter.
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/respec/830)

Hljs update

---

js/core/figures.js

Behaviour can be reproduced with multiple links created to a figure: without this change only the first one renders.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/respec/822)

Fix figures so more than one link can be made to figures

---

js/core/css/webidl-oldschool.css

drops the text shadow, darkens the .parameters background, explicitly
sets .parameters th color to white and .exceptions th to inherit/black
closes https://github.com/w3c/respec/issues/882

increase contrast for .parameters th and .exceptions th text

---

js/ui/save-html.js

* Help identify which version of ReSpec generated a document.

feat(save-html): Add meta tag generator (closes #805)

---

js/ui/save-html.js

close #791 (again)
the line it adds was mistaken removed in https://github.com/w3c/respec/commit/e5724439d4bcaba0aed60477facc5cd0d06eabd0
(this blocks echidna publications, so hopefully we can release this fix ASAP)

Move charset declaration at the top when saving

---

tools/respecDocWriter.js

This has caused puzzling errors in the spec generator
credits to @deniak for identifying the bug and fix

Ensure respec2html doesn't cache old respec versions in long-running processes

---

js/core/highlight.js
js/core/style.js
js/core/utils.js
tests/spec/core/utils-spec.js

* Removes code that Travis said was redundant
* Simplifies the swapper, but getting the owner document directly from insertion point

refactor(utils): ownerSwapper only takes Nodes (close #801)

---

package.json
tests/headless.js

This branch fixes some issues with running `npm install` and `npm test` on Windows. The test suite will run, but it fails on IE.
- ~~#957 is merged into this pull request (it depends on the `copydeps.js` script, otherwise `npm install` fails on Windows). If you want to merge this, please merge #957 first.~~
- The behavior for `&&` on Windows and POSIX systems is different. Windows runs expressions on both sides unconditionally, while POSIX systems only run the second expression if the first succeeds. Hopefully this hack won't cause us problems since the commands should succeed, but if it does we should refactor the multi-part npm scripts into more JS files.

Fixes for Windows testing

---

js/w3c/style.js

Small optimization, reduces FOUC a little bit.

Style optimization

---

js/w3c/templates/headers.html

Matching the expectation in
https://github.com/w3c/specberus/blob/master/lib/rules/headers/translations.js

Updated W3C translations link

---

tools/respecDocWriter.js

When using `respecDocWriter`, the `electron` process is not closed when the source provided doesn't return a HTTP 200 (eg. the document doesn't exist) or when the document is not a respec document.
That PR kills the process in the 2 use cases above.

[respecDocWriter] electron not closed properly if the document doesn't exist or is not a respec document

---

examples/webidl-contiguous.html
js/core/css/webidl-oldschool.css
js/core/webidl-contiguous.js
js/core/webidl-index.js
js/profile-w3c-common.js
tests/spec/core/idl-index-spec.js
tests/testFiles.json

Gathers all the WebIDL into a single section. Keeps all the links.

Add IDL-index support (closes #159)

---

js/core/webidl-contiguous.js

Currently, we don't support linking to "maplike", "setlike", "stringifier"

fix(webidl-contiguous): don't link special IDL things (closes #996)

---

js/core/data-cite.js
js/core/link-to-dfn.js
js/profile-w3c-common.js
tests/spec/core/data-cite-spec.js
tests/testFiles.json

This adds a new foundation feature to ReSpec, allowing authors to directly cite another SpecRef spec in inline text. This is currently very simple, on purpose... so we can build: 
```HTML
It's in the <a data-cite="!DOM">DOM spec</a>.
It's in the <a data-cite="HTML">HTML spec</a>.
```  
That automatically adds `href` attribute pointing to the DOM spec.  It also adds the reference to the References section in the right place.

feat(data-cite): add support for data-cite attribute

---

js/core/jquery-enhanced.js
js/core/templates/webidl-contiguous/compiled.js
js/core/templates/webidl-contiguous/enum-item.html
js/core/webidl-contiguous.js
tests/spec/core/webidl-contiguous-spec.js
tests/spec/core/webidl-contiguous.html

* link simple method() names (closes #1000)
* fix(webidl-contiguous): Link enum when empty string (closes #981)
* test(webidl-contiguous-spec): link simple method() names

feat(webidl-contiguous): link method() and enum ""

---

js/core/webidl-contiguous.js

Otherwise, respec creates a broken link

Use lowercase when linking to enum values

---

js/core/link-to-dfn.js
src/core/data-cite.js
tests/spec/core/data-cite-spec.js

This enables citing definitions in other specs:
```HTML
<p>The <a>bar</a>...</p> 
<p>The <dfn data-cite="!foo#bar">bar</a></p>
```
Which automatically:
* links "bar" to the external spec
* links the dfn to the external spec
* add the reference to the References section

feat: enable data-cite on dfn

---

karma.conf.js
tests/spec/SpecHelper.js

As we can't see the errors, it doesn't make sense to run Karma/Travis against the unbuilt version.

tests: run karma against build instead

---

.gitignore
js/core/css/respec2.css
js/core/ui.js
js/profile-w3c-common.js
js/ui/about-respec.js
js/ui/dfn-list.js
js/ui/save-html.js
js/ui/search-specref.js
src/core/aria.js
src/core/highlight.js
tools/release.js
tools/respecDocWriter.js

* document now signals when busy
* pre elements that are getting changed now signal when busy
* ReSpec pill is still not great... but less crappy: DOM ordering is not correct for tabbing. Correct roles and labels applied. We also notify when things menus and dialogs open and close. 
It's far from perfect, but it's hopefully a huge improvement.

feat: significantly improve ARIA support

---

js/w3c/templates/cgbg-headers.html

Allow for additional logos in the CG spec template
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/w3c/respec/821)

Allow additional logo in CG spec

---

js/core/link-to-dfn.js
js/core/webidl-contiguous.js
tests/spec/core/link-to-dfn-spec.js
tests/testFiles.json

fix: use monospace font for <a>s that link back to IDL

---

js/core/css/respec2.css

The acronym element was made redudant in HTML5, so this is no longer needed.

fix(respec2.css): remove acronym styles

---

src/core/markdown.js

I believe this same issue still exists for ampersands

Fix for ampersands in markdown

---

src/core/utils.js

Coincidentally, this fixes an off-by-one error in Safari.

refactor(core/utils): use native date parser

---

src/w3c/linter.js

* closes #1107
We should only about privacy and/or security sections for
REC track documents.

fix(w3c/linkter): privacy warn for non-rec track

---

src/core/include-config.js
src/core/override-configuration.js
src/w3c/headers.js
tests/spec/core/include-config-spec.js

closes #504. 
Exposes:
* `publishISODate`
* `generatedSubtitle`
* any query params added via the URL (e.g., ?foo=bar&baz=123).

feat: add URL query values to exported user config 

---

js/core/ui.js
js/ui/ui.css
karma.conf.js
src/core/biblio-db.js
src/core/biblio.js
src/core/data-include.js
src/core/figures.js
src/core/jquery-enhanced.js
src/core/markdown.js
src/core/rdfa.js
src/core/requirements.js
src/core/utils.js
src/core/webidl.js
src/w3c/abstract.js
src/w3c/headers.js
src/w3c/linter.js
src/w3c/style.js
tests/spec/core/override-configuration-spec.js
tests/spec/w3c/abstract-spec.js

Closes #1085. Noticeable changes: 
* core/utils - gains `markdownToHtml()` method. 
* core/rdfa - moved abstract processing into there. 
* w3c/abstract - no longer wraps text content into paragraphs (because that's gross).
Globally: 
* use native `array.includes()` to check for things.
* less jQuery here and there.

BREAKING CHANGE: use markdown for error/warn

---

karma.conf.js
tests/spec/SpecHelper.js

We use "about-blank.html" to simulate "about:blank", because
Edge won't let you access IndexedDB in about: URLs 🤷‍♂️.

tests: allow testing in Edge

---

src/core/webidl.js
tests/spec/core/webidl-spec.js
tests/spec/core/webidl.html

feat(core/webidl): handle multi-type generics

---

src/core/utils.js

This was triggering when parsing bad IDL, where stuff inside pre tags was being converted into actual nodes. Like:
```JS
Thing<Thing> foo;
```
Where `<Thing>` would become a DOM node, but we are expecting text nodes.

fix(core/utils): handle nulls when checking TextNodes

---

src/w3c/headers.js

Right now, respec complains if all of wg, wgUri, and wgPatentUri are arrays, when it should complain only if some but not all are
Bug was introduced in 0b706ce8ce3b524ba442bedd154dfb056503e131

Fix bug in detecting wrong configuration for multiple WGs

---

.travis.yml
karma.conf.js
tests/test-main.js

Travis' MacOS builds are taking about 3-8 hours to get queued, so they are not longer an viable option. Switching to Linux, but having to drop Firefox in the process. Firefox on CI environments is too slow and flaky - so it's too unreliable.

chore(.travis): use linux

---

package.json

It's my understanding that the current release of Respec requires Node.js &ge; 8. Is that so?
This makes that explicit in `package.json`.

Node 8 required

---

.gitignore
js/profile-w3c-common.js
src/core/list-sorter.js
tests/spec/core/list-sorter-spec.js
tests/testFiles.json

By using `data-sort="ascending"` or `"descending"`, ReSpec can
now sort definition lists (`dl`). This is nice for Dependency
sections, IDL member definitions, etc.
You can also just put `data-sort` and no value, and it will default
to "ascending".

feat: teach ReSpec to sort lists

---

js/w3c/templates/sotd.html
src/w3c/headers.js
tests/spec/w3c/headers-spec.js

Improve patent text on notes

---

package-lock.json
package.json

Fixes #1458 
It turns out that the recent update of uglify-es is the culprit.
(This includes #1459 so you will probably want to merge it first)

fix: roll back to uglify-es 3.2.2

---

tools/respecDocWriter.js

Nightmare doesn't support `timeout` or `userData` arguments so this PR maps them correctly.

Fix Nightmare API use

---

package-lock.json
package.json
tests/test-build.js
tools/builder.js
tools/respec2html.js

`package.json` forces Node.js 8+, we already use async functions elsewhere, so why not reduce a dependency 😁

Migrate to ES2017 async functions

---

package-lock.json
package.json

~~The last malfunctioning version was 3.3.9 so try 3.3.8.~~
The last known good version is 3.3.7, so use it rather than older 3.2.2.

chore(package): use uglify-es 3.3.7

---

package-lock.json
package.json
tools/respec2html.js
tools/respecDocWriter.js

[`puppeteer`](https://developers.google.com/web/tools/puppeteer/) is a first-party wrapper library of Chromium made by Google. It directly uses Chromium instead of Electron (which again uses Chromium), and has less dependencies (80 total dependencies for `nightmare` whereas 16 for `puppeteer`.)
This still requires a real browser (Chromium) but in a lighter way.
Ultimately, but not in this PR, we can use puppeteer-installed Chromium to be used in karma tests so that GPU-less CLI environments can use it easily.

refactor: use puppeteer instead of nightmare

---

.travis.yml
karma.conf.js

This enables `npm run karma -- --browsers FirefoxHeadless` to skip automatic browser detection.
Bonus: Using ChromeHeadless does not require xvfb :+1:

Skip detectBrowsers when explicitly passing browsers

---

src/core/webidl.js

as it has been removed from the spec.
Also includes several ES2015 refactorings for `registerHelpers()`, before we do #1136.

refactor: remove WebIDL array support 

---

tests/spec/core/linter-rules/no-headingless-sections-spec.js

jasmine-core 3.0 [defaults to running in unordered way](https://github.com/jasmine/jasmine/blob/master/release_notes/3.0.md) and this causes failure on no-headingless-sections tests:
```
Core Linter Rule - 'no-headingless-sections'
√ complains when a nested section doesn't have a heading
× returns error when heading is missing section
√ doesn't complain when sections do have a heading
```
```
Core Linter Rule - 'no-headingless-sections'
√ returns error when heading is missing section
√ doesn't complain when sections do have a heading
√ complains when a nested section doesn't have a heading
```
This PR clears `doc` before each test to prevent this failure.

fix: prevent unordered tests from conflicting

---

tools/release.js

The hb:build command is no longer available.

fix(tools/release): use build:components instead

---

examples/basic.built.html
examples/basic.html

Want to encourage use of `github:`, instead of setting config options
manually.

docs(examples): use github config option

---

src/core/webidl-index.js
tests/spec/core/idl-index-spec.js

For issue #1479 
The problem is appending only the first child.
Screenshot after changes: 
UPDATED SCREENSHOT

fix(core/webidl-index): support multiple idl blocks

---

src/core/link-to-dfn.js
tests/spec/core/link-to-dfn-spec.js

fixes: #1427 
I had already showed a GIF in https://github.com/w3c/respec/issues/1427#issuecomment-362926979 where I had added three `dfns` of `country` to cause the error
Please review marcosc

Link to duplicate dfns

---

.travis.yml

This `sudo: required` is still required for the karma tests, which is not related with the new `--disable-sandbox` option.

fix: re-add sudo required

---

src/w3c/headers.js

These were already always defined via the w3c defaults, so these checks are redundant.

refactor(w3c/headers): use w3c defaults

---

src/w3c/jsonld.js

Set JSON-LD `@langauge` from HTML `@lang`.
Fix `datePublished` `@type` to not use undefined `xsd` namespace.

jsonld uses undefined "xsd" namespace

---

js/profile-w3c-common.js
src/core/seo.js
src/w3c/jsonld.js
tests/spec/w3c/jsonld-spec.js

This makes jsonld get added after processing, so to not block critical content rendering. 
Additionally, it fixes the `description`, to use the one we already have in the document's head. The whitespace has been cleaned up nicely, and only uses the first paragraph of the abstract.

fix(w3c/jsonld): make async, used description

---

package-lock.json
package.json
tests/headless.js
tools/release.js
tools/respecDocWriter.js

Fixes #1522 
puppeteer `response.ok()` currently always returns `false` for local files (I filed https://github.com/GoogleChrome/puppeteer/issues/2116 for this), so this PR workarounds it.
Bonus: This removes `express` dependency.

fix(tools/respecDocWriter): allow local file requests

---

package.json
tools/builder.js
tools/respec2html.js

Closes #1565.
I don't think we have anything to change.

fix(package): update command-line-usage to version 5.0.2

---

tests/spec/SpecHelper.js
tests/spec/w3c/headers-spec.js

As suggested by @marcoscaceres, at #1576  the changes have been made. There can be multiple ways to incorporate the same. This is just one of them. 
Currently, the new format has been tried at a couple of places (visible [here](https://github.com/w3c/respec/pull/1576/files)). Please review. :smile:

Allow makeStandardOps() to take overrides: Fixes #1576

---

package-lock.json
package.json
src/core/webidl.js
tests/spec/core/webidl-spec.js
tests/spec/core/webidl.html

Fixes #1574.
There was no support for TypeWithExtendedAttributes things so this PR adds it.

fix(core/webidl): support extended attributes for IDL types

---

src/w3c/templates/headers.js
tests/spec/w3c/headers-spec.js

This now sets the document title based on the `h1`, so it avoid having to declare the title of the spec twice. ReSpec gets upset when they are different.

fix(w3c/templates/headers): doc.title must match conf.title

---

src/w3c/templates/headers.js

That [commit](https://github.com/w3c/respec/commit/a5e552c054d0f4994514b71f7d4ae5e5e6fb311b#diff-ebb1a497c097951bb868645bd73ade4f) broke the expected header.
Fix #1590

fix: restore whitespace between status and date

---

src/w3c/templates/sotd.js
tests/spec/w3c/headers-spec.js

Fixes #1494 .
The url for team submission comment requires the submission year (not the published year) along with the comment number (serial no of what comment it was in that year).  Idk how to get the comment number.

Remove @@@ from sotd

---

src/core/webidl.js

Some operations in WebIDL can be annoynous (e.g., strigifiers), so we shoulnd't warn about the when they have no name.
For example: 
```
interface Selection {
stringifier DOMString ();
}
```

fix(core/webidl): dont warn about nameless ops

---

src/core/base-runner.js

wpub loads a lot of stuff, so the issues and notes plugin can time out.

fix(core/base-runner): extend plugin life

---

src/core/figures.js
tests/spec/core/figures-spec.js

fixes: #923 
@marcoscaceres, I decided to create a new module name `core/images` as I think the code fits into no other existing modules. I may be wrong though

feat(core/images): add natural width and height to images(#923)

---

src/core/webidl.js
tests/spec/core/webidl.html

Based on https://github.com/heycam/webidl/pull/550 removes LegacyArrayClass. 
Also noticed the following had been removed from WebIDL:
-  legacycaller
-  legacyiterable

Remove IDL legacy things

---

src/core/exporter.js
src/ui/save-html.js
tests/spec/core/exporter-spec.js
tests/test-main.js
tools/respecDocWriter.js

basically moved export code to a separate file and made a little changes.
Reasons:
- Couldn't test exported html without including unneeded modules (core/ui etc)
Can test easily now as:
``` js
fit("lets access exported html", async() => {
const doc = await makeRSDoc(makeStandardOps());
await doc.respecIsReady;
const { exportDocument } = await new Promise(resolve => {
require(["core/exporter"], resolve);
});
const exportedHtml = await exportDocument("html", "text/html", doc);
// .. tests  
});
``` 
Please let me know if i broke something in between and the parameters that refactored functions need. :)

Refactor save html

---

tools/respecDocWriter.js

When running on TravisCI, we want to prevent the key being shown.

sec(tools/respecDocWriter): dont show URL params

---

tools/respecDocWriter.js

Version 20.10 introduced the `core/exporter` module, which is now used in `RespecDocWriter`. Problem is the spec on which RespecDocWriter runs may still reference an older version of ReSpec that does not have that module.
An example of a spec that has this problem today is [Media Capture and Streams](https://w3c.github.io/mediacapture-main/) which uses version 20.1.0. Running `RespecDocWriter` on it makes it crash badly (badly because the `Promise` that wraps the code to `require` does not get properly rejected when the module cannot be found, so the execution stays locked there with the error being reported to the console by RequireJS).
The writer checks the version of ReSpec and refuses to run on very old versions (lower than version 18). It still accepts to run on versions between 18 …

Make RespecDocWriter work with older versions of ReSpec

---

src/core/list-sorter.js

Use of `Math.random()` means the resulting selector looked like `#temp-0.924252548658087 > dt`, which is not a valid CSS selector due to the presence of a `.` (class selector), followed only by numbers (an `ident-token` cannot start with a digit:
https://drafts.csswg.org/css-syntax-3/#ref-for-typedef-ident-token%E2%91%A0
Using `${String(Math.random()).substr(2)}`, as in other places in Respec that create random IDs.

Fix temp ID syntax in list sorter

---

js/core/css/caniuse.css

Fix the following: when button loses hover, it hides the browsers. 
Intended behaviour: hide active browser list when list is out of hover.

Fix caniuse hover show/hide

---

tools/respecDocWriter.js

Because of Puppeteer 1.4 (https://github.com/GoogleChrome/puppeteer/issues/1939), `respecDocWriter` is incorrectly exiting with: 
```
Failed to load file:////respec/js/core/css/var.css: Cross origin requests are only supported for protocol schemes: http, data, chrome, https.
```
For every css file.

fix(tools/respecDocWriter): support Puppeteer 1.4 error reporting

---

src/core/link-to-dfn.js
src/w3c/headers.js

- Make CG template complain if `conf.wg` is not set (`pub("error")`)
- Prevent `linkTargets` from crashing when it encounters an empty `<a>`
- Closes #1666

fix: link-to-dfn module may report a TypeError

---

src/core/dfn.js
tests/spec/core/dfn-spec.js

Fixes following bugs in `dfn`:
- `textContent` shouldn't be in `data-lt`
- plural term should used for `dfn.id` to prevent breaking existing links

fix(core/dfn): improve backwards compat

---

src/core/biblio.js

When a reference has a link, the stringifyReference function wraps the
title in the link and adds a ". " to the end of it to separate it from
the rest of the reference text. But if it doesn't have a link, neither
the link nor the ". " are added, causing the title to run into the next
portion of the output. This commit adds the separator for this case.
There may be more elegant ways to handle but this fix seems
straightforward.

Add a period and space to unlinked references

---

src/core/best-practices.js
src/core/data-cite.js
src/core/data-transform.js
src/core/figures.js
src/core/highlight-vars.js
src/core/id-headers.js
src/core/issues-notes.js
src/core/linter-rules/no-headingless-sections.js
src/core/utils.js
src/core/webidl-index.js
src/w3c/informative.js
tests/spec/core/dfn-spec.js

as all browsers now treat NodeList as `@@iterable`, don't need to convert to array in some cases.

perf: dont create arrays unnecessarily

---

js/core/templates/webidl-contiguous/attribute.html
js/core/templates/webidl-contiguous/callback.html
js/core/templates/webidl-contiguous/const.html
js/core/templates/webidl-contiguous/dict-member.html
js/core/templates/webidl-contiguous/dictionary.html
js/core/templates/webidl-contiguous/enum-item.html
js/core/templates/webidl-contiguous/enum.html
js/core/templates/webidl-contiguous/extended-attribute.html
js/core/templates/webidl-contiguous/field.html
js/core/templates/webidl-contiguous/implements.html
js/core/templates/webidl-contiguous/includes.html
js/core/templates/webidl-contiguous/interface.html
js/core/templates/webidl-contiguous/iterable-like.html
js/core/templates/webidl-contiguous/line-comment.html
js/core/templates/webidl-contiguous/method.html
js/core/templates/webidl-contiguous/multiline-comment.html
js/core/templates/webidl-contiguous/param.html
js/core/templates/webidl-contiguous/typedef.html
package-lock.json
package.json
src/core/webidl-index.js
src/core/webidl.js
tests/spec/core/idl-index-spec.js
tests/spec/core/webidl-spec.js

...and replace `opt.ws` with the new trivia feature. It means that we lose the IDL formatting feature, and @marcoscaceres agreed to remove it in https://github.com/w3c/respec/issues/1559#issuecomment-371998009.
(This PR does not really support full whitespace conservation as the purpose here is to update without test breakage.)
Closes #1675 
Closes #1684 
Closes #1701

Update to webidl2.js 14

---

js/profile-w3c-common.js
src/core/biblio.js
src/core/render-biblio.js

Notes:
- splits into render-specific and pre-processing parts and make a single module do lesser work
- **Change**: always use latest biblio refs
- Refactor triggered in preparation of upcoming external references feature as the feature will dynamically modify `data-cite` attributes

 refactor(core/biblio): split into pre-processing and rendering parts

---

js/core/templates/webidl-contiguous/dict-member.html
src/core/webidl.js
tests/spec/core/webidl-spec.js
tests/spec/core/webidl.html

closes #1717
* only actual comments should be treated as comments
* type in template should be treated as HTML

fix(core/webidl): idl not rendering correctly

---

src/core/data-cite.js
src/core/utils.js
src/core/xref.js
tests/spec/core/xref-spec.js

- Updates error messages
One present issue that needs to be resolved is that the multiple warnings are emitted for same term. It also tells that our `disambiguate` algorithm is executing for each term (even when they are same). So, that fix is coming up next.

fix(core/xref): Improve error messages

---

js/core/css/respec2.css

#1683 
Added a little CSS on :target which lets one focus easily where the hash link lead to.
Here is the screenshot.

feat(core/css/respec): add :target highlight #1683

---

src/core/link-to-dfn.js
src/core/utils.js
src/core/xref.js
tests/spec/core/xref-spec.js

- presently only supports parent's `data-cite`, not self `data-cite`
**Update**: Also supports self `data-cite` as:
- if the term exists, url resolves to url fragment
- else: url resolves to spec itself. no warning is emitted

feat(core/xref): use data-cite to disambiguate

---

src/core/xref.js
tests/spec/core/xref-spec.js

Uses nearby `[[SPEC]]` to provide context as `specs` to search for (as a part of https://github.com/w3c/respec/issues/1662)
Maybe this should be enabled via a flag, not always. Why? Consider:
``` html
<section data-cite="html">Uses [[WEBIDL]] to create context for <a>object</a></section>
```
Above, the query for this term will contain `specs: ["html", "webidl"]`, which results in an ambiguity that can't be resolved unless (either):
- User removes `data-cite="html"` from parent or remove the nearby `[[WEBIDL]]` 
- Instead of `specs.push(...inlineContextSpecs)`, we do `specs = inlineContextSpecs`

feat(core/xref): use inline references to provide context

---

src/core/link-to-dfn.js
src/core/xref.js
tests/spec/core/xref-spec.js

All `dfn` are no longer looked up externally (bug). Now only the following types of terms are looked up externally:
- `a` for which no internal `dfn` was found
- `a[data-cite="spec"]`
- `dfn[data-cite="spec"]`
- `dfn.externalDFN`
Fixed and cleaned up a lot of tests in this PR
--- 
**Note to reviewer**:
Please see the `xref-spec.js` as full file instead of the diff. Lots of code movement and refactoring.

fix(core/xref): explicit external dfn lookup

---

src/core/webidl.js
tests/spec/core/webidl-spec.js
tests/spec/core/webidl.html

The [Browser Extensions](https://browserext.github.io/browserext/) spec is broken because of this. (...which still has `implements`, BTW!)

fix(core/webidl): unindentMarkup() should work with space-only lines

---

package-lock.json
src/core/base-runner.js
src/core/webidl.js

This:
1. removes deprecated `cb()` and an unused exposed promise `done`.
2. removes jQuery.

refactor(core/webidl): modernize run()

---

js/core/css/issues-notes.css
src/core/issues-notes.js
tests/spec/core/issues-notes-spec.js

Based on discussions https://github.com/w3c/hr-time/pull/59#issuecomment-408119539
Crossing out the issue number is fairly standard in bug tracking systems (e.g., bugzilla)

fix(core/issues-notes): don't remove closed issues

---

karma.conf.js
tests/spec/core/webidl-spec.js

... to save kittens!
Bonus: `npm run karma -- --grep (regex)` [as suggested](https://github.com/karma-runner/karma/issues/672#issuecomment-204620473).

refactor(tests/spec/core/webidl-spec): remove jQuery from ctor/const/attr tests

---

.eslintrc.json
.travis.yml
package.json
src/core/best-practices.js
src/core/caniuse.js
src/core/data-include.js
src/core/examples.js
src/core/github.js
src/core/highlight.js
src/core/issues-notes.js
src/core/structure.js
src/core/utils.js
src/core/webidl-clipboard.js
src/ui/dfn-list.js
src/ui/search-specref.js
src/w3c/headers.js
src/w3c/linter-rules/privsec-section.js
src/w3c/permalinks.js
src/w3c/rfc2119.js
src/w3c/seo.js
src/w3c/style.js
src/w3c/templates/cgbg-headers.js
src/w3c/templates/cgbg-sotd.js
src/w3c/templates/conformance.js
src/w3c/templates/headers.js
src/w3c/templates/show-link.js
src/w3c/templates/show-logo.js
src/w3c/templates/show-people.js
src/w3c/templates/sotd.js

This PR introduces `npm run lint` so that any Codacy errors can be prevented before opening a PR.
If you don't like some of the changes, now is the time to do a fine tune.

Force eslint

---

karma.conf.js

Currently only tests including "null" in their title are running because of this.

fix(karma.conf.js): grep causes incorrect skips

---

karma.conf.js
tests/spec/SpecHelper.js
tests/spec/core/data-include-spec.js
tests/spec/core/include-config-spec.js
tests/spec/core/informative-spec.js
tests/spec/core/location-hash-spec.js
tests/spec/core/override-configuration-spec.js
tests/spec/core/pre-process-spec.js
tests/spec/core/remove-respec-spec.js
tests/spec/core/requirements-spec.js
tests/spec/core/section-refs-spec.js
tests/spec/core/structure-spec.js
tests/spec/core/ui-spec.js
tests/spec/core/webidl-spec.js
tests/spec/w3c/headers-spec.js
tests/spec/w3c/permalinks-spec.js
tests/spec/w3c/seo-spec.js
tests/spec/w3c/style-spec.js

... and remove deprecated callbacks.

refactor: use await for makeRSDoc()

---

tests/spec/core/best-practices-spec.js
tests/spec/core/data-cite-spec.js
tests/spec/core/data-include-spec.js
tests/spec/core/dfn-spec.js
tests/spec/core/figures-spec.js
tests/spec/core/highlight-spec.js
tests/spec/core/highlight-vars-spec.js
tests/spec/core/idl-index-spec.js
tests/spec/core/link-to-dfn-spec.js
tests/spec/core/list-sorter-spec.js
tests/spec/core/markdown-spec.js
tests/spec/core/pre-process-spec.html
tests/spec/core/pre-process-spec.js
tests/spec/core/ui-spec.js
tests/spec/core/webidl-spec.js
tests/spec/core/xref-spec.js
tests/spec/w3c/headers-spec.js
tools/respecDocWriter.js

Maybe someone batch-converted jQuery into querySelector?

refactor: use getElementById whenever possible

---

tests/spec/core/webidl-spec.js

Tried removing `:contains` pattern this time:
```js
// original
expect($section.find("dfn:contains('docString')").attr("id")).toEqual( 
"dom-documented-docstring" 
);
// new
// Edit: Thanks @sidvishnoi
expect( 
section.querySelector("dfn#dom-documented-docstring").textContent 
).toEqual("docString");
```
This improves accuracy as the `:contains()` pattern didn't assert the exact value.
Edit: I'm so happy that I don't have to fix Codacy issues anymore, with the new `npm run lint -- --fix`.

refactor(tests/spec/core/webidl-spec): remove remaining jQuery

---

src/core/webidl.js
tests/spec/core/webidl-spec.js
tests/spec/core/webidl.html

closes #1768
This prevents the attribute's type from using the parent element's `data-link-for`, which was confusing the linker. Types always need to be defined at top level things (i.e., they are not "for" things), so this should work.

fix(core/idl): linking attribute id/type with same name

---

src/core/jquery-enhanced.js
src/core/link-to-dfn.js
src/core/utils.js

As a part of https://github.com/w3c/respec/issues/1699

 refactor(core/jquery-enhanced): migrate $linkTargets to vanilla js

---

src/core/webidl.js

We were accidentally setting the id of the `<pre>` element to `""`, which is causing the HTML validator to say the document is invalid (empty id values are invalid, apparently... which makes sense, I guess).

fix(core/webidl): only set pre id when needed

---

src/core/linter-rules/local-refs-exist.js
tests/spec/core/linter-rules/local-refs-exist-spec.js

Fixes #1808.
The URL was escaped earlier, breaking the `ID` to search for.

fix(lint/local-refs-exist): handle unicode characters in IDs

---

src/core/biblio.js
tests/spec/core/biblio-spec.js

This fixes a bug whereby if a non-normative reference had a different case from a normative one, ReSpec ended up adding the reference to both the normative and informative sections. This was making document invalid, because we were ending up with double definitions and two unique ids in the document.

fix(core/biblio): avoid dup refs when case differs

---

src/core/webidl.js
tests/spec/core/data-type-spec.js
tests/spec/core/webidl-spec.js
tests/spec/core/webidl.html
tests/testFiles.json

Given:
```HTML
<pre class=idl>
interface Foo {
attribute Bar bar;
DOMString toString();
};
</pre>
<dfn>Foo</dfn>
<dfn data-dfn-for="Foo">bar</dfn>
<dfn data-dfn-for="Foo">toString()</dfn>
```
The `<dfn data-dfn-for="Foo">bar</dfn>` gains:
* `data-type`: `Bar` 
* `data-idl`: `attribute` 
The `<dfn data-dfn-for="Foo">bar</dfn>` gains:
* `data-type`: `DOMString`, which is the return type.
* `data-idl`: `operation` 
Having these bits of information allow us to do interesting things - like type checking, chained linking, cute pop-ups showing the type, etc.

feat(core/data-type): auto assign IDL types to dfns

---

src/w3c/headers.js

This change adds support for specStatus: LS (Living Standard) and specStatus: LD (Living Document). That provides parity with the status levels of the same names available when using Bikeshed (see the related Bikeshed docs at https://tabatkins.github.io/bikeshed/#metadata-status).

Add support for Living Standard & Living Document

---

src/w3c/templates/cgbg-headers.js
tests/spec/w3c/headers-spec.js

The option was ignored for CG/BG documents. However, it may be useful in some cases where a CG is a joint work with another organization (The Web Media API CG is an example of a joint group with CTA).

Allow use of additionalCopyrightHolders for CG/BG documents

---

examples/basic.built.html
examples/basic.html
package-lock.json
package.json
tests/headless.js

Something in puppeteer 1.10.0 has caused a regression whereby the highlight worker doesn't respond. 
https://github.com/w3c/spec-generator/pull/135 
Although reproducible, it's unfortunately a heisenbug: If I enable puppeteers/chrome's devtools, the problem doesn't occur.  
Best solution appears to be to just roll back to 1.9.0.

fix(package): puppeteer 1.10.0 causes hightlighter to pause

---

src/core/issues-notes.js

Sending the username is redundant, if one can just send the token: 
https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/

feat(core/issues-notes): allow token only github Authorization

---

.eslintrc.json
package.json
src/w3c/headers.js
tools/release.js

Resolves https://github.com/w3c/respec/pull/1887#discussion_r232881824
`"linebreak-style": 0` is because we are using git which automatically cares line endings. I turned it off in #1777 but it has been revived by prettier and exploded Windows environments 🤣

refactor: use dot notation when possible

---

.eslintrc.json
js/core/css/webidl.css
src/core/link-to-dfn.js

Those are mostly for ancient non-contiguous IDL.

refactor: Remove unused CSS selectors

---

src/core/dfn-finder.js
src/core/webidl.js

findDfn() is an unreadable aircraft-carrier-sized function so this PR breaks it into pieces.
Some functions are still too long but should be more readable than before.

refactor: split findDfn() as dfn-finder module

---

js/core/templates/webidl-contiguous/extended-attribute.html
js/core/templates/webidl-contiguous/implements.html
src/core/dfn-finder.js
src/core/webidl.js

`implements` is gone, `ws` is also gone. Farewell!

refactor(core/webidl): remove remnants of implements/ws

---

src/core/webidl.js

Because shorter functions are easier to understand 👍

refactor(core/webidl): split linkDefinitions()

---

src/core/dfn-finder.js
src/core/webidl.js
tests/spec/core/webidl.html

This else branch is unreachable because the function terminates early when no `obj.dfn`.
https://github.com/w3c/respec/blob/054887afb5ff8018321114fd21eee317f5956b41/src/core/webidl.js#L97-L100

refactor(core/webidl): remove unreachable branch

---

src/core/dfn-finder.js
src/core/jquery-enhanced.js
src/core/utils.js
src/core/webidl.js

1. Remove `data-no-default` as nothing uses it
2. Remove the fourth argument from `addId` as nothing uses it.
3. Assign `data-lt` for empty enum value to handle it automatically
Currently we have three places to treat empty enum value in a special way (`util.getDfnTitles()`, `findNormalDfn()`, and `tryLink()`, respectively), and this PR removes one of them.

refactor(core/dfn-finder): lt for empty enum value

---

tools/builder.js

Currently we chooses source map from requirejs and ignores terser, causing broken source map. This fixes the issue.

fix(tools/builder): source map from terser

---

js/core/templates/webidl-contiguous/const.html
js/core/templates/webidl-contiguous/dict-member.html
js/core/templates/webidl-contiguous/extended-attribute.html
js/core/templates/webidl-contiguous/param.html
src/core/webidl.js
tests/spec/core/webidl-spec.js

Those are solely for testing purpose, which just tests their existence. We don't need them as we already checks the whole `<pre>` text content.
Related to #1917.

Remove styleless CSS classes, round 1

---

package-lock.json
src/core/dfn-finder.js
src/core/link-to-dfn.js
src/core/utils.js
src/core/webidl.js
tests/spec/core/utils-spec.js

I tried flattening arrays filled with `HTMLElement`s and then found the current `flatten()` also flattens `HTMLAnchorElement` (which is iterable)! This PR makes the function more align with the suggested [`Array.prototype.flat`](https://tc39.github.io/proposal-flatMap/).

refactor: array-only flatten(), etc.

---

src/core/data-cite.js
src/core/inlines.js
src/core/link-to-dfn.js
src/core/linter.js
src/core/utils.js
src/core/xref.js
src/w3c/templates/show-logo.js
tests/spec/core/xref-spec.js

Didn't know we already had `showInlineError()`! The function showed "warning" instead of "error" despite of its name, so this PR renames it as `showInlineWarning` and adds proper `showInlineError`.

Add showInlineError/Warning helper functions

---

tests/spec/core/webidl-spec.js
tests/spec/core/webidl.html

Closes #1795 
The support has been added by #1920 and this PR adds a test.

test(core/webidl): links for namespaces

---

jsconfig.json
src/core/link-to-dfn.js
tests/spec/core/link-to-dfn-spec.js
tests/spec/core/webidl-spec.js

Following #1948 
Adding jsconfig.json to correctly `@ts-check` latest ECMAScript native functions.

refactor(core/link-to-dfn): split functions

---

src/core/figures.js
tests/spec/core/figures-spec.js

fix(core/figures): use childNodes instead of <figcaption>

---

src/core/best-practices.js
src/core/examples.js
src/core/exporter.js
src/core/markdown.js
src/core/utils.js
src/core/webidl.js
src/w3c/headers.js
src/w3c/informative.js
src/w3c/style.js

`insertBefore()` is still useful but we now have better modern methods, which only requires a single argument and thus more readable.

refactor: avoid using insertBefore()

---

src/core/dfn-finder.js
src/core/dfn.js
tests/spec/core/dfn-finder-spec.js

This fixes https://github.com/w3c/respec/issues/1878#issuecomment-437748048:
>>Removing data-lt solves the issue but also removes gamepadhapticactuator.pulse()|gamepadhapticactuator.pulse. Is this expected?
>
>No. We should fix that.

fix(core/dfn-finder): always enumerate every alternative form for operations

---

src/core/issues-notes.js

I did most of the refactoring. However, there is this small makeID function, as far as I understand, it's for tracking #issue on the page. It is linked to global jQuery object.
But it's being used inside core/issues-notes.js. It further refers to another function somewhere in Utils. How do I proceed? @sidvishnoi @marcoscaceres 
refers to issue #1846

refactor(core/issue-notes): remove jquery

---

tests/spec/core/dfn-spec.js
tests/spec/core/informative-spec.js
tests/spec/core/section-refs-spec.js
tests/spec/core/structure-spec.js
tests/spec/core/utils-spec.js
tests/spec/w3c/conformance-spec.js

I am working on #1846 removing jquery from test files. ```w3c/headers-spec``` has a pretty huge number of occurences. Might as well do them in a separate PR. Meanwhile I would appreciate if you could review these files @saschanaz @sidvishnoi @marcoscaceres :smile:

refactor(tests/spec): remove jQuery

---

builds/respec-w3c-common.build.js.map
src/core/examples.js
src/core/utils.js
tools/builder.js

Should only be needed before a w3c-side fix for #2006.

fix: add a symlink for sourcemap

---

src/w3c/defaults.js
tests/spec/core/pluralize-spec.js
tests/spec/w3c/defaults-spec.js

We've been running with this for a few months in various specs and it's working pretty well, so feel confident enabling by default.

feat(w3c/defaults): enable pluralize by default

---

src/w3c/templates/headers.js

This way at least the base template string should be more readable...

refactor(w3c/templates): split as functions

---

src/core/examples.js
tests/spec/core/examples-spec.js

Fixes https://github.com/w3c/respec/issues/2034 
I have currently re-indented all children of `aside` tag. Please let me know if it is to be done only on the `pre` tags which are children of `aside`.

Reindent innerHTML of children of aside tag

---

src/core/structure.js
tests/spec/core/section-refs-spec.js

Removes extra whitespace that can occur in the titles (also refactor code a little bit).

fix(core/structure): trim section titles

---

src/w3c/templates/headers.js

See https://github.com/w3c/specberus/pull/805 and https://github.com/w3c/specberus/issues/797

Beihang homepage is now under https

---

src/core/reindent.js

Currently generating a warning, which causes ReSpec validator to "halt on warning".

fix(core/reindent): export module's name

---

package.json

As the feature has been reverted in highlight.js.

chore(package): revert to cli branch

---

assets/issues-notes.css

Box titles are getting uppercased. Also, there is a bunch of redundant stuff that's already provided by base.css around issues, notes, etc.

fix(assets/issue-notes): don't uppercase boxed titles

---

src/core/issues-notes.js
tests/spec/core/issues-notes-spec.js

This P.R aims to add localization in respect to issue https://github.com/w3c/respec/issues/2084 for the module `issues-notes.js`. Thanks to all who review and @marcoscaceres for great assistance. Is this time to start working on W3C modules as core modules are almost done?

 refactor(core/issues-notes): localize module 

---

src/core/pubsubhub.js
src/w3c/conformance.js
tests/about-blank.html
tests/spec/SpecHelper.js
tests/spec/core/examples-spec.js
tests/spec/w3c/conformance-spec.js
tests/spec/w3c/headers-spec.js

Also fixed a problem where `makeRSDoc()` doesn't run inline `<script>` because of timing problem. (ReSpec typically waits until all DOM elements including inline `<script>` load, but currently `makeRSDoc` inserts ReSpec and scripts after the document load.)
Fixes #2147

fix(w3c/conformance): always emit an end event

---

src/core/link-to-dfn.js

What's better here is:
1. more clear... 
1. avoid call to .closest()

fix(core/link-to-dfn): don't xref autofills (again)

---

src/core/inlines.js

I have done some minor optimizations in the inlines.js module.
1. Rather than using the JavaScript `shift()`, I have switched to simple array-indexing. Although JavaScript functions do not have an implementation standard, from what I read, most implementations would cause array re-indexing on each use of `shift()` which is somewhat inefficient.
2. I think that it is better to check for RFC 2119 keywords at the end - it is more efficient to check if a string starts with `{{{` or `[[` first than to run the entire regex expression on all strings. 
These are minor optimizations, because while they probably are efficient, I am not sure if it will make a difference beyond a few milliseconds - this depends how many inline keywords occur in a W3C spec in a practical scenario. 
There are 2 other …

refactor(core/inlines) : Minor optimizations

---

src/core/structure.js
tests/spec/core/structure-spec.js

fixes #2170 
The trimmed `textContent` should be compared to empty string.

(core/structure): Fixed checking for empty text anchors

---

tests/spec/core/examples-spec.js
tests/spec/core/figures-spec.js
tests/spec/core/issues-notes-spec.js

The localization tests recently added were outside the `describe()` block, so I have shifted them inside. I think I have shifted all of them.

Shifted localization tests into specification test suites

---

src/w3c/l10n.js

Added the `status_at_publication` string for Spanish language.
@marcoscaceres This also fixes the TypeError in tests, and yes, I see it was important to fix this error even though the test passed, because I discovered that without this, the "Status of This Document" section is not generated in Spanish documents.
While writing a test for (core/structure), I noticed a TypeError in the browser console, for the localization test. I found that all tests with Spanish language result in the same error while none of the other languages have a problem. The `status_at_publication`string was required by the SOTD template.

(w3c/l10n): Added string for es (Spanish)

---

src/core/data-cite.js
src/core/inlines.js
src/core/utils.js
src/core/xref.js
tests/spec/core/xref-spec.js

Found that this wasn't completely fixed. The citation order was getting out of whack.

fix(core/xref): normative refs always win

---

src/core/contrib.js
src/core/github-api.js

I came up with this strategy to use the request headers instead of a new endpoint https://github.com/w3c/respec/pull/2197#discussion_r268945469
We don't need to merge that PR if this is good.

Use Remaining Requests from GitHub Response Headers

---

assets/respec2.css
assets/ui.css

When clicking navigating to inline errors, or certain areas of interest, this makes the things "pop"... making them easier to find amongst other text.

feat(assets/respec2): make inline warnings visually pop

---

src/core/inlines.js
tests/spec/core/inlines-spec.js

Fixes #2208 
The new RegEx is:
```js
/\B\|\w[\w\s]*(?:\s*\:[\w\s&;<>]+)?\|\B/
```
Thanks to @sidvishnoi for the RegEx. This matches single letter variables, and also types with spaces. I have tested it on some possible variable types, and it does not seem to create any new issues.
In the variable type, the RegEx matches word characters (A-Z, a-z, 0-9, _) and whitespace characterss and the characters `&;<>`. 
I want to confirm if no other character occurs in a variable type. @saschanaz Could you take a look at this?

fix(core/inlines): Single letter variables don't get converted to var

---

assets/respec2.css

Fixes #2224 
To be reverted once https://github.com/w3c/tr-design/pull/176 is merged.
Fixes the issue for Firefox, and does not cause problems with Chrome.

fix(assets/respec2): offending elements don't display properly in Firefox

---

src/core/markdown.js
src/core/ui.js
src/core/utils.js

This is mainly to enable ES module system to load `core/utils` without requiring `marked`, and this anyway also looks more logical to me.

refactor(core/utils): transfer marked dependency to core/markdown

---

src/w3c/templates/headers.js

This is a continuation to #2251 fixing a small bug with the implementation, when both `h1` and `document.title` are present and `isPreview`, `prUrl`, and `prNumber` are set, then ReSpec emits a warning `The document's title and the "<title>" element differ.` due to whitespace being present.
Sorry for not testing this initially. 
I don't think I can have a test for this until #1084 is fixed.

fix(w3c/headers): mismatched title warning

---

src/core/inline-idl-parser.js

Now uses the regex directly from WebIDL https://heycam.github.io/webidl/#prod-string

fix(core/inline-idl-parser): enumValueRegex too restrictive

---

src/core/inlines.js
tests/spec/core/inlines-spec.js

Can now handle, for example, [= `link` element =]

feat(core/inlines): process code inside inline links

---

assets/var.css

Using border bottom causes everything to reflow on hover, as it adds an extra pixel... using text-decoration prevents this.

fix(assets/var): prevent reflow on var:hover

---

tests/spec/core/xref-spec.js

Fixes failing tests at https://travis-ci.org/w3c/respec/jobs/523446784#L903

tests(core/xref-spec): update broken link

---

src/core/inlines.js
tests/spec/core/inlines-spec.js

closes #2131 
Allow for `[[[#example-1]]]` and `[[[#figure-whatever]]]` and so on... 
The actual expansion is handled by individual modules.

 feat(core/inlines): allow [[[#...]]] to expand ids in doc

---

assets/mdn-annotation.css
src/core/mdn-annotation.js

Closes #2313 
I have increased the hit area and also the removed the `<details>` section so now browser support table opens up without an additional click. Tested on Firefox and Chrome. Please try it out.
> We should also improve the markup. When we shipped, we copied what the HTML Spec was doing... but the markup is less than ideal.
Does this mean refactoring of the implementation? Like using `addEventListener("click",..)` instead of the current implementation where the event handler is in the HTML itself?

fix(core/mdn-annotation): Improve user experience

---

src/core/anchor-expander.js
src/core/exporter.js
src/core/utils.js
tests/spec/core/exporter-spec.js

All comments are removed when exporting. 
`makeSafeCopy()` now returns the copied node, not just the children. 
core/utils now exports `removeCommentNodes()`

fix: remove all comment nodes when exporting

---

src/w3c/conformance.js
tests/spec/core/inlines-spec.js

Move to using the newer [rfc8174](https://tools.ietf.org/html/rfc8174) for conformance key worlds, which fixes ambiguity between "MUST" and "must".

fix(w3c/conformance): use BCP 14 (RFC8174) for conformance

---

src/core/examples.js

#2303 added it but soon #2326 made it redundant.

refactor(core/examples): remove redundant map

---

src/core/contrib.js
src/core/mdn-annotation.js
src/core/utils.js

`fetch()` can directly receive a url and headers, so no need to explicitly create a request first.

refactor(core): remove redundant `new Request()`

---

package.json
tools/copydeps.js

As I said in https://github.com/w3c/respec/issues/2359#issuecomment-495554972 I think this is an intermittent Chrome Canary bug (on which puppeteer depends).

chore(package): pin puppeteer to 1.16.0

---

src/core/biblio-db.js
src/core/biblio.js
src/core/linter-rules/no-http-props.js
src/core/linter.js
src/core/ui.js
src/core/utils.js
src/core/webidl-index.js
src/geonovum/l10n.js
src/ui/about-respec.js
src/ui/search-specref.js
src/w3c/l10n.js

Sometimes `.reduce()` is used only to prevent closure, causing lower readability and longer code.

refactor: replace uses of `array.reduce()`

---

examples/basic.html
src/core/webidl.js
tests/data/xref/inline-idl-enum.json
tests/data/xref/inline-locals.json
tests/spec/core/webidl-spec.js
tests/spec/core/xref-spec.js

I'd made a mistake in the WebIDL code, where I was putting `data-cite` on the container pre. This was causing linking to fail.

fix(core/webidl): link idl blocks contextually

---

src/core/link-to-dfn.js
src/core/render-biblio.js
src/core/webidl.js
tests/spec/core/webidl-spec.js

xrefs things like:
```
partial interface Element {};
partial mixin Whatever {};
partial dictionary SomeDictionary {};
```
To the right specs.

 fix(core/webidl): autolink IDL partial definitions

---

assets/ui.css
assets/webidl.css
src/core/webidl-clipboard.js

This simplifies the tree for crawlers e.g. TSJS-lib-generator.
Also removing redundant CSS properties.

refactor(core/webidl-clipboard): remove wrapper div

---

src/core/data-cite.js
tests/spec/core/data-cite-spec.js

Prevents specs stomping on each other's definitions by accident.

fix(core/data-cite): prevent re-export of exisiting dfns

---

tools/respecDocWriter.js

Prevents empty warning from browser warnings... same structure as errors:

fix(tools/respecDocWriter): filter browser warnings

---

src/core/webidl.js
tests/spec/core/dfn-finder-spec.js
tests/spec/core/webidl-spec.js

No more definition errors! Fixes #2316 
`<dfn>` by default uses bold font, not sure we want it in IDL text.

feat(core/webidl): allow self-defining IDL

---

assets/respec2.css

[base.css](https://www.w3.org/StyleSheets/TR/2016/base.css) was overriding broken links (`a.respec-offending-element`) and remove the squiggly underline. 
Not sure if adding `!important` is good idea or not.
^^ squiggly underline not shown

fix(assets/respec2): base.css removed underline from error links

---

package-lock.json
package.json

It seems 2.0 is just a mistake in #2445, 1.199.0 is now the latest version.
Fixes #2447 for now. I think `&&` makes more sense anyway...

chore(package): update snyk version

---

src/core/figures.js
tests/spec/core/anchor-expander-spec.js
tests/spec/core/figures-spec.js

Currently the whole module fails when there is no valid figcaption, because `getTableOfFiguresListItem` expects a caption element.

fix(core/figures): generate tof even when no figcaption

---

src/w3c/headers.js
src/w3c/templates/sotd.js
tests/spec/w3c/headers-spec.js

It should either emit correct link or nothing, not `the <a href='undefined'>undefined</a>`.

fix(w3c/headers): do not emit undefined wg link

---

src/core/xref.js

- [pre-filled form in first error](https://respec.org/xref/?term=event+handleria&types=_CONCEPT_&cite=dom%2Cfetch%2Chtml%2Cinfra%2Curl%2Cwebidl)
- [demo of some real errors at performance-timeline](https://respec-preview.netlify.com/?spec=https%3A%2F%2Fw3c.github.io%2Fperformance-timeline%2F&version=https%3A%2F%2Fdeploy-preview-2455--respec-pr.netlify.com%2Frespec-w3c.js)
Closes #2318, #2358, #2310

 feat(core/xref): delegate error hints to xref UI

---

karma.conf.js
tests/spec/core/ui-spec.js

Some tests are slower than expected, mainly because of network requests. This PR adds a way to be alerted.

chore(karma): report when too slow

---

src/core/biblio.js

Removing that line shouldn't make any change, as both `split.hasData` and `split.noData` are already processed.
Closes #2461

refactor(core/biblio): remove redundant request

---

src/core/inline-idl-parser.js
tests/spec/core/xref-spec.js

We didn't support {{ unrestricted double }} {{ long long }} and friends

fix(core/inline-idl-parser): better support IDL primitives

---

tools/respecDocWriter.js

Fix for #2477 adds an additional 1 second wait to ensure that all console errors are logged before closing the page/browser.
Also switches to use `await` for `browser.close();` as per the Puppeteer [examples](https://pptr.dev/).

Fix for race condition on page close (fixes #2477)

---

src/core/webidl.js
tests/spec/core/webidl-spec.js

IDL self-definition defines `data-dfn-for` but it's immediately overwritten by incorrect value (the name of itself instead of the parent's name). This PR fixes it.
(Found from https://w3c.github.io/editing/execCommand.html#methods-to-query-and-execute-commands-0)

fix(core/webidl): do not overwrite data-dfn-for

---

src/core/dfn-finder.js
src/core/link-to-dfn.js
src/core/webidl.js
tests/spec/core/webidl-spec.js

The second wave of refactors in #2489.

refactor(core/dfn-finder): move addAlternativeNames to decorateDfn

---

src/core/link-to-dfn.js
tests/spec/core/link-to-dfn-spec.js

fix(core/link-to-dfn): wrap as code for all linking formats

---

src/core/pluralize.js
tests/spec/core/pluralize-spec.js

Regression from https://github.com/w3c/respec/pull/2484, https://github.com/w3c/respec/pull/2489. Should fix https://github.com/w3c/respec/issues/2496#issuecomment-527560437
Makes sense as one won't be pluralizing IDL and concept-dfn can be lowercased.
[Fixes `json-ld-syntax`](https://respec-preview.netlify.com/?spec=https://w3c.github.io/json-ld-syntax/&version=https://deploy-preview-2505--respec-pr.netlify.com/respec-w3c-common.js). Will try to confirm if any exports break.

fix(core/pluralize): normalize to lowercase

---

tests/spec/core/xref-spec.js

had to update data as we were using mocks earlier
(this example was hard to find)

tests(core/xref): uses inline biblio for spec context

---

src/core/xref.js

Re-uses the term getting logic from `getRequestEntry`, but doesn't lowercase it (to preserve the original term).
Other way could be: keep original term in query always, and handle case-sensitivity check on back-end.
| before | after |
| --- | --- |
| ![before](https://user-images.githubusercontent.com/8426945/64322910-10535a00-cfe1-11e9-9932-36c3b2f0c9b6.png) | ![after](https://user-images.githubusercontent.com/8426945/64322865-fc0f5d00-cfe0-11e9-91c0-e4ad6641f8e9.png) |

fix(core/xref): preserve original term in error messages

---

src/w3c/templates/headers.js

@marcoscaceres Please review, and let me know if this requires additional changes.
Fixes #2352

fix(w3c/templates/headers): Switch default license for unofficial drafts to 4.0 (#2493)

---

src/w3c/templates/show-people.js
tests/spec/w3c/headers-spec.js

The W3C validator is complaining about the missing `datetime`, because the text content is in the wrong format.

fix(templates/show-people): add missing datatime attribute

---

assets/mdn-annotation.css

* Closes [issue 2540](https://github.com/w3c/respec/issues/2540)
* I took the icon links from the [same folder as other icons](https://resources.whatwg.org/browser-logos/)
* Thank you @marcoscaceres for pointing me towards this repo!

fix(assets/mdn-annotation.css): link to svgs to fix 404 opera and samsung icons

---

tools/copydeps.js

`errno` is different in Windows, so it's more safe to use `code` instead.

fix(tools/copydeps): gracely ignore when no folder

---

src/w3c/headers.js

docs(w3c/headers): w3c-software-doc is the default

---

src/w3c/seo.js
tests/spec/w3c/seo-spec.js

This exports a few more fields from Specref's data model to the JSON-LD export of the bibliography.
Closes #2584.

feat(w3c/seo): Improve JSON-LD export of citations

---

src/core/markdown.js
tests/spec/core/markdown-spec.js

Fixes https://github.com/w3c/respec/issues/2607
`getLanguageHint` in `core/highlight.js` expects languages without any prefix.
Alternative way to solve this could be to remove `"language-"` prefixes from classList, but this is one simpler (don't add `language-` prefix)

fix(core/markdown): syntax highlight in fenced blocks

---

src/core/markdown.js
tests/spec/core/markdown-spec.js

Fixes issue [#2596](https://github.com/w3c/respec/issues/2596).
Thanks for guiding me through respec's test workflow and also for general help, @marcoscaceres!

fix(core/markdown): more forgiving WebIDL language tag

---

src/core/utils.js
tests/spec/core/utils-spec.js

All the unused functions mentioned are commented out
[issue#2557](https://github.com/w3c/respec/issues/2557)

refactor(core/utils): remove unused utils functions

---

src/w3c/conformance.js

In  src/w3c/conformance.js, joinAnd has been replaced with htmlJoinAnd

refactor(w3c/conformance): use htmlJoinAnd

---

src/core/xref.js

Getting nearly ~200ms benefits in `core/link-to-dfn` (payment-request spec, all cached requests)
Before:
Now:

perf(core/xref): remove unused slow code

---

.github/FUNDING.yml

This way we can get a nice Sponsor button at the top of the GitHub page, [as parceljs has](https://github.com/parcel-bundler/parcel/blob/v2/.github/FUNDING.yml).

chore(.github): point OpenCollective in Sponsors

---

src/core/markdown.js
tests/spec/core/markdown-spec.js

Fixing a regression found in wicg/serial:
Lack of newlines before HTML end tags caused this.

fix(core/markdown): indent idl correctly after a list

---

src/core/best-practices.js
src/core/data-tests.js
src/core/examples.js
src/core/figures.js
src/core/github.js
src/core/informative.js
src/core/issues-notes.js
src/core/l10n.js
src/core/link-to-dfn.js
src/core/render-biblio.js
src/core/structure.js

We were doing l10n migration to modules wrong :fire:  
We were assuming if we have some translations for a language, we have all translations for that language.
This was taken into account when we had `core/l10n`, where we added default as `en` by Object spread.
Consider:
``` js
const localizationStrings = {
en: { key1, key2, key3 },
ja: { key1 } // we assumed `lang` as "ja" even when key2, key3 are undefined 
}
```
Also, a little refactor as we don't have to `const lang = defaultLang in l10n ? defaultLang : "en";` in every module.
Alternate approach considered: `{...en, ...[lang]}`. Decided to go against it as it creates a new clone (not sure how bad it could be though).
Proxy approach also allows us to show a missing translation/invalid key warning if we want to.

fix(core/l10n): fallback to 'en' for missing l10n keys

---

assets/dfn-panel.css
profiles/geonovum.js
profiles/w3c-common.js
profiles/w3c.js
src/core/dfn-panel.js
tests/spec/core/dfn-panel-spec.js

Closes https://github.com/w3c/respec/issues/1103 (finally! :tada:)
:sparkles: Check out the demo at respec-preview (in checks below or [here](https://deploy-preview-2626--respec-pr.netlify.com/)) :sparkles:
Markup and style are same as bikeshed for consistency.
Should we add a resize handler to reposition the panel?
// TODO

feat(core/dfn-panel): add panel with local dfn references

---

tests/spec/core/markdown-spec.js

Our wiki currently says:
> ## Known issues
> 
> In some cases, the markdown processor gets confused. For example, given: 
> 
> ```HTML
> <pre class="example">
> 1 * 2 * 3;
> </pre>
> ``` 
> 
> The "`*`"s get converted to an `<em>`. Obviously, that's not ideal. A workaround is to wrap the "*" in back-ticks, like this:
> 
> ```HTML
> <pre class="example">
> 1 `*` 2 `*` 3;
> </pre>
> ```
This is not true anymore, so this PR makes sure that won't happen.

test(core/markdown): <pre> should not parse as markdown

---

src/w3c/templates/cgbg-headers.js
src/w3c/templates/headers.js
tests/spec/w3c/headers-spec.js

This allows editors to provide their own copyright markup via:
```HTML
<p class="copyright">
My custom copyright.  
</p>
```
Closes #263
Closes #2243

feat: allow overriding copyright using HTML

---

src/core/ui.js

The menu buttons were being announced as: "Floppy disk export button"

fix(core/ui): hide menu icons from AT

---

src/core/id-headers.js
src/core/structure.js
tests/spec/core/id-headers-spec.js
tests/spec/core/structure-spec.js

Prefer `heading.id` for TOC linking and self linking.

feat(core/structure): prefer `heading.id` over `section.id`

---

src/w3c/templates/cgbg-sotd.js
src/w3c/templates/sotd.js

refactor(w3c/templates/cgbg-sotd): contain its own l10n strings

---

src/core/markdown.js
tests/spec/core/markdown-spec.js

Allows passing custom headings like:
``` markdown
Foo title {#foo}
================
```

feat(core/markdown): allow custom ID for headings

---

src/core/best-practices.js
src/core/data-tests.js
src/core/examples.js
src/core/figures.js
src/core/github.js
src/core/informative.js
src/core/issues-notes.js
src/core/l10n.js
src/core/link-to-dfn.js
src/core/render-biblio.js
src/core/structure.js
src/core/utils.js
src/w3c/templates/headers.js
src/w3c/templates/sotd.js
tests/spec/core/utils-spec.js

Came across this bug from https://github.com/w3c/respec/pull/2689
~TODO: Move this to utils and add tests~

fix(core/l10n): do not throw if l10n strings don't exist for lang

---

tools/release.js

`npm version --no-git-tag-version` does not create a commit (we believed it just didn't create tag, as name implies), so amending does not make sense.

chore(tools/release): create commit instead of amend

---

src/core/linter-rules/wpt-tests-exist.js
tests/spec/core/linter-rules/tests-exist-spec.js

The current rule doesn't work on github.org/web-platform-tests/wpt URLs

fix(core/linter-rules): extract correct name for WPT directory

---

assets/webidl.css
src/core/webidl-clipboard.js
src/core/webidl.js
tests/spec/core/webidl-spec.js

We had invalid markup... causing [errors with respec-validator](https://travis-ci.com/w3c/screen-orientation/builds/143352826#L705)

fix(core/webidl): use valid markup inside pre

---

src/core/inlines.js
tests/spec/core/inlines-spec.js
tests/spec/core/xref-spec.js

Closes https://github.com/w3c/respec/issues/2705
~Blocked on https://github.com/marcoscaceres/respec.org/pull/61~ Updated on respec.org
In future, https://github.com/w3c/respec/pull/2508 might also help.

feat(core/inlines): support linking element-attr types

---

tools/builder.js

Reduces uncompressed build size from 320KB to 284KB - thanks to Terser optimizing IIFE better.

chore(tools/builder): use IIFE and remove appendBoilerplate

---

src/core/utils.js

Can't remove this horrible function as [several specs already are using it](https://github.com/search?l=HTML&q=respec+oninclude+org%3Aw3c&type=Code) 🤦‍♀️

refactor(core/utils): no `arguments`

---

tests/spec/SpecHelper.js
tests/spec/core/markdown-spec.js

Finally had time to figure it out. That part was reverted by #2678.

test(core/markdown-spec): reenable custom id test

---

src/core/xref.js

On payment-request, the cite/spec context reduced from 1265 specs to 1023 specs and size of entire query reduced from 29833 bytes to 26215 bytes.
This also increases chances of getting common queries across specs on same domain - so we can use more cached results (though still rare).
The basic idea is to make `specs.flat().length` equal to `new Set(specs.flat()).size)`

perf(core/xref): remove duplicate cite context to reduce query size

---

src/w3c/templates/headers.js
tests/spec/w3c/headers-spec.js

Fixes https://github.com/w3c/respec/issues/2731

fix(w3c/headers): construct PR preview URL if `prUrl` is missing

---

src/core/xref.js

Providing `specsContext` that failed to resolve a term doesn't help the user in figuring out which spec actually contains the term. 
So, by not providing a false `specContext`, we properly delegate it to the xref UI.
As an example, instead of using https://respec.org/xref/?term=abort&cite=svg,appmanifest, which fail to resolve `abort`, we use https://respec.org/xref/?term=abort

fix(core/xref): remove false spec context from prefilled UI URL

---

tools/release.js

develop and gh-pages branch got out of sync somehow some time ago, causing GitHub Action failures (lint errors) on gh-pages branch. 
Lets hope this doesn't cause issues (merge conflict or something) in next release.
**PS: This PR is to gh-pages branch, not develop**

chore(tools/release): sync with `develop` branch

---

src/core/dfn-panel.js
src/core/inline-idl-parser.js
src/core/issues-notes.js
src/core/mdn-annotation.js
src/core/utils.js

Part of #2551
Remaining are all `conf.*HTML` or such, which will cause breaking changes when removed.

refactor: remove raw HTML insertions

---

src/dini/headers.js
src/w3c/headers.js
src/w3c/templates/cgbg-headers.js
src/w3c/templates/headers.js

This removes additional redundant `${[...]}` and also reduces `conf` pollution.
Partly also #2743.

refactor(w3c/headers): pass alternatesHTML as options

---

tools/release.js

These lines does nothing, as the generated builds are already committed.

refactor(tools/release): no need to checkout

---

src/core/override-configuration.js

Closes https://github.com/w3c/respec/issues/2374
@saschanaz Do you remember any other instances where we can use Object.fromEntries?

refactor(core/override-config): use Object.fromEntries

---

src/core/webidl-clipboard.js

refactor(core/webidl-clipboard): always use navigator.clipboard

---

src/core/list-sorter.js
src/core/structure.js
src/core/utils.js
tests/spec/core/structure-spec.js

Part of https://github.com/w3c/respec/issues/2374

refactor(core/utils): remove `children` util

---

assets/ui.css

When a warning/error contains a `<details>` (which in turn causes marked to wrap `li.textContent` in a `<p>`), the warning/error emoji is not aligned to the paragraph. Saw it first with WebIDL errors.
Without `display: inline`:
With `display: inline`:
(yes, I don't have native emoji support)

fix(assets/ui.css): align first paragraph to warning marker

---

assets/ui.css
profiles/w3c-common.js
profiles/w3c.js
src/core/a11y.js
src/core/utils.js
src/type-helper.d.ts
tests/spec/core/a11y-spec.js

Closes https://github.com/w3c/respec/issues/2777
- The linter API is not flexible enough with error reporting, so created a new core/a11y module.
- Axe is quite slow on W3C specs. Need to disable a lot of rules, or provide authors a way to select rules. Should be used locally only to fix issues, not on live versions.

feat(core/a11y): add axe-core integration

---

src/core/a11y.js
tests/spec/core/a11y-spec.js

Earlier, if one added `rules` option, it'll run even the ones we have disabled. One can still enable the rules we've disabled, but would need to be explicit.

fix(core/a11y): allow overriding rules while keeping disabled ones

---

assets/issues-notes.css
src/core/issues-notes.js

This resulted in same label text colors as on GitHub, satisfying color contrast guidelines. Also, code is smaller and simpler.

fix(core/issues-notes): fix issue label color contrast

---

src/w3c/templates/show-link.js
tests/spec/w3c/headers-spec.js

Fixes https://github.com/w3c/respec/issues/2789
[Preview `sdw/time` spec with fixes](https://respec-preview.netlify.com/?spec=https%3A%2F%2Fw3c.github.io%2Fsdw%2Ftime%2F&version=https%3A%2F%2Fdeploy-preview-2790--respec-pr.netlify.com%2Frespec-w3c-common.js)

fix(templates/show-link): render otherLinks without href as plain text

---

src/core/defaults.js
src/dini/defaults.js
src/w3c/defaults.js
tests/spec/core/pluralize-spec.js

Moved `pluralize: true` to `core/defaults` as it's enabled in all profiles anyway.
Also, removed a redundant test (we already have one with `pluralize: false`.

refactor(*/defaults): enable pluralize in core/defaults

---

karma.conf.js
package-lock.json
package.json
src/core/dfn-finder.js
src/core/examples.js
src/core/expose-modules.js
src/core/jquery-enhanced.js
src/core/linter-rules/check-charset.js
src/dini/conformance.js
src/dini/headers.js
src/dini/templates/headers.js
src/dini/templates/show-link.js
src/dini/templates/show-logo.js
src/dini/templates/show-people.js
src/w3c/conformance.js
src/w3c/headers.js
src/w3c/templates/cgbg-headers.js
src/w3c/templates/headers.js
src/w3c/templates/show-link.js
src/w3c/templates/show-logo.js
src/w3c/templates/show-people.js
src/w3c/templates/sotd.js
tests/support-files/hljs-testlang.js
tests/test-main.js
tools/respecDocWriter.js

Closes https://github.com/w3c/respec/pull/2799 (which uses prettier 2.0.0)

chore: update prettier, style changes

---

.github/workflows/pr-push.yml

Unfortunately, Snyk will run unnecessarily, but it's better than randomly failing tests.

chore(ci): fix node_modules caching issue

---

assets/dfn-index.css
profiles/w3c-common.js
profiles/w3c.js
src/core/data-cite.js
src/core/dfn-index.js
src/core/dfn-panel.js
src/core/xref.js
tests/spec/core/dfn-index-spec.js

Closes https://github.com/w3c/respec/issues/2560
[Demo with [payment-request]](https://respec-preview.netlify.com/?spec=https%3A%2F%2Fw3c.github.io%2Fpayment-request%2F&version=https%3A%2F%2Fdeploy-preview-2810--respec-pr.netlify.com%2Frespec-w3c.js&respecConfig=setTimeout%28%28%29+%3D%3E+document.body.insertAdjacentHTML%28%27beforeend%27%2C+%27%3Csection+id%3D%22index%22%3E%3C%2Fsection%3E%27%29%2C+0%29%3B)

feat(core/dfn-index): generate list of externally referenced terms

---

assets/dfn-index.css
src/core/dfn-index.js
src/core/dfn-panel.js
src/core/structure.js
tests/spec/core/dfn-index-spec.js

Closes https://github.com/w3c/respec/issues/2817
[Demo with [payment-request]](https://respec-preview.netlify.com/?spec=https%3A%2F%2Fw3c.github.io%2Fpayment-request%2F&version=https%3A%2F%2Fdeploy-preview-2819--respec-pr.netlify.com%2Frespec-w3c.js&respecConfig=setTimeout%28%28%29+%3D%3E+document.body.insertAdjacentHTML%28%27beforeend%27%2C+%27%3Csection+id%3D%22index%22%3E%3C%2Fsection%3E%27%29%2C+0%29%3B)
[Demo with [manifest]](https://respec-preview.netlify.com/?spec=https%3A%2F%2Fw3c.github.io%2Fmanifest%2F&version=https%3A%2F%2Fdeploy-preview-2819--respec-pr.netlify.com%2Frespec-w3c.js#index)
TODO:

feat(core/dfn-index): list local definitions

---

src/core/xref.js

As seen in https://github.com/w3c/respec/issues/2432#issuecomment-610114149, this was causing irrelevant error messages on linking failure. And as it threw, it showed unrelated error even with `data-no-xref`.
Demo:
- [with this fix](https://respec-preview.netlify.com/?spec=https%3A%2F%2Frawcdn.githack.com%2FMaps4HTML%2FHTML-Map-Element-UseCases-Requirements%2Ffa0ed305b36dafbb76814d6fc49d3eb6e6049e40%2Findex.html&version=https%3A%2F%2Fdeploy-preview-2821--respec-pr.netlify.com%2Frespec-w3c-common.js&respecConfig=delete+respecConfig.xref%3B)
- [without this fix](https://respec-preview.netlify.com/?spec=https%3A%2F%2Frawcdn.githack.com%2FMaps4HTML%2FHTML-Map-Element-UseCases-Requirements%2Ffa0ed305b36dafbb76814d6fc49d3eb6e6049e40%2Findex.html&version=https%3A%2F%2Fwww.w3.org%2FTools%2Frespec% …

fix(core/xref): do not throw in error reporting without spec context

---

src/core/data-cite.js
src/core/dfn-index.js
src/core/link-to-dfn.js

We can avoid passing conf to citeDetailsConverter, and have a unique instance which we can reuse. Simplifies code a bit.
Note to reviewer: Review commit by commit and ignore whitespace changes.

refactor(core/data-cite): do not require conf in citeDetailsConverer

---

src/core/biblio.js
src/core/data-cite.js
src/type-helper.d.ts

Making code further easier to understand. `data-cite` already does too much, and does a lot of unrelated work.
Note to reviewer: Review commit by commit. Split view with whitespace hidden recommended.

refactor(core/data-cite): split into smaller functions

---

src/core/dfn-map.js
src/core/link-to-dfn.js
src/core/utils.js

Part of https://github.com/w3c/respec/issues/2830
`findLinkTarget` was misleading as it mutated its `anchor` parameter.
Although `useLinkTarget` isn't a great name either - it's very much overloaded. Suggestions welcome.

refactor(core/data-cite): simplify linking

---

tests/spec/core/webidl-spec.js

This attribute was removed in https://github.com/heycam/webidl/pull/870 and one of our test was using it ([see failing test](https://github.com/w3c/respec/runs/608111600)).

test(core/webidl): remove legacy TreatNullAs

---

src/core/link-to-dfn.js
tests/spec/core/link-to-dfn-spec.js

Compare the effect [with this PR](https://respec-preview.netlify.app/?spec=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Fpage-visibility%2F62320d1091941e13862ed3d4e469e82afbb1f214%2Findex.html&version=https%3A%2F%2Fdeploy-preview-2868--respec-pr.netlify.app%2Frespec-w3c.js) to [without this PR](https://respec-preview.netlify.app/?spec=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Fpage-visibility%2F62320d1091941e13862ed3d4e469e82afbb1f214%2Findex.html&version=https://unpkg.com/respec@25.7.0/builds/respec-w3c.js) on [page-visibility]
Part of #2271

fix(core/link-to-dfn): link local dfn with foreign forContext

---

src/core/webidl.js
tests/spec/core/dfn-index-spec.js
tests/spec/core/webidl-spec.js
tests/spec/core/webidl.html

Note for anyone coming to search for this issue as a linker error:
Replace all occurrences of `default toJSON operation` with `default toJSON steps`.
See https://github.com/heycam/webidl/pull/882,
or in particular: https://github.com/heycam/webidl/commit/ea3af2cfb2a8204ac17da27c347d760ae12b4d0a#diff-ec9cfa5f3f35ec1f84feb2e59686c34dL11840

fix(core/webidl): default toJSON operation is now toJSON steps

---

.github/workflows/pr-push.yml

GitHub actions [already have](https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md) Chrome and Firefox installed, so we can skip our own install..
Cons: A rare risk of puppeteer API getting out of sync with installed Chrome/Firefox version.
Pros: Much faster CI (4m 26s to 3m 15s), smaller cache (157MB compressed to 35MB) (need cache purging to see - will be automatic in future, I checked with temporary manual cache purges)
What's next?
- We can now use `npm ci` :tada: 
- We can also remove `actions/setup-node`, as Node v12 is also installed.

chore(ci): skip puppeteer install

---

.github/workflows/pr-push.yml

As we have a package-lock, we can use it, and it's faster than `npm install`.

chore(ci): use npm ci instead of npm i

---

.github/workflows/pr-push.yml

No one has used it in past, so it just adds noise. GitHub might natively support this in future.

chore(ci): remove ci skip ability

---

assets/dfn-panel.css
src/core/dfn-panel.js

Reverts hot-fix from https://github.com/w3c/respec/pull/2846 (See https://github.com/w3c/respec/issues/2845)
Precursor to https://github.com/w3c/respec/pull/2820
This changes the markup for dfnPanel, mainly converts the caret to a `<span>` instead of `::before` as we cannot programmatically set position of `::before` without CSS variables - which aren't supported by nuHTML validator.

fix(core/dfn-panel): avoid using CSS variables

---

.github/workflows/pr.yml
.github/workflows/push.yml

Idea is:
- We run all tests for PRs (pr.yml). Good work.
- When merge the PR, all tests have already passed. Plus, we always sync with develop before merge, so things are unlikely to have changed.
- But to be sure, we still run fast tests when PR is merged, or when we release (push: gh-pages). To not waste CPU cycles, we:
- ignore lint -> not high priority.
- run karma only in Chrome, as Firefox is slower and there is unlikely any change since PR tests. We can also do the opposite: test more browsers on merge.
- We can run other jobs on merge, like https://github.com/w3c/respec/pull/2895/ or regression tests (See https://github.com/w3c/respec/issues/2874). These need not run on every PR synchronize event.

chore(ci): split into PR and push workflows

---

src/core/webidl.js
tests/spec/core/dfn-index-spec.js
tests/spec/core/webidl-spec.js
tests/spec/core/webidl.html

This is cherry-pick of a4d3b2680aa8ac0e8ad84b50de5406aa856b5689 and 42cc58e6ac0e661755352fa9cbbfdf37d0d83367
Without these, tests in w3c-common branch will keep failing.

fix(core/webidl): update outdated xref terms

---

src/core/dfn-index.js
tests/spec/core/dfn-index-spec.js

`addId` relies on checking IDs for collision in `ownerDocument`, but these `.index-term` are not in any document yet.
Demo with an old version of manifest spec:

fix(core/dfn-index): prevent id collision

---

tests/spec/core/xref-spec.js

`css-snappoints` now redirects to `css-scroll-snap`, so our [tests started to fail](https://github.com/w3c/respec/runs/712940053?check_suite_focus=true#step:6:873).
This PR:
- Removes a redundant test case
- Changes a test to test same thing, but with different term.

tests(core/xref): update tests for removal of css-snappoints

---

src/core/inlines.js
src/core/xref.js
tests/spec/core/inlines-spec.js

Closes https://github.com/w3c/respec/issues/2914 as backticks are already supported but `/` is not

fix(core/inlines): allow escaping forward-slash in terms

---

src/core/xref.js
tests/spec/core/xref-spec.js

This avoids the need to add `aliasOf` entries in `localBiblio`
It allows ReSpec to search and link using the same authored `data-cite`. Earlier, we could search using authored data-cite, but link was always based on `shortname`.
See: https://github.com/w3c/manifest/pull/878#discussion_r432331678

fix(core/xref): add data-cite as authored in spec context

---

assets/mdn-annotation.css

Removes some padding hackery. Figured out a `box-sizing: border-box` was missing

refactor(assets/mdn-annotation.css): simplify padding issues

---

src/core/dfn-panel.js

Missed this in https://github.com/w3c/respec/pull/2901
linter/local-refs-exist started complaining rightly.
It was generating dfn panels for all `.index-term` which included the following links:

fix(core/dfn-panel): do not generate panels in local dfn index

---

src/core/dfn-panel.js

There were some `dfn` inside IDL index, which didn't have an id, causing broken local reference.

fix(core/dfn-panel): do not generate panels for dfn without id

---

src/core/mdn-annotation.js

We already inject the panels in exported doc, styles were missing,

fix(core/mdn-annotation): inject CSS in exported docs

---

assets/dfn-panel.css

Firefox and Chrome treated `display: inline` with `position: relative` differently. 
I'll write a minimal case and see if it's a web-compat bug or I did something wrong.
Update: Minimal reproduction: https://codepen.io/sidvishnoi/pen/bGEGaeW?editors=1100
| Firefox | Chrome |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/8426945/83633497-afcc6a00-a5be-11ea-941a-c55491af6797.png) | ![image](https://user-images.githubusercontent.com/8426945/83633471-a2af7b00-a5be-11ea-8604-6ebf8083fce9.png) |

fix(assets/dfn-panel.css): fix caret position across browsers

---

assets/dfn-panel.css
src/core/dfn-panel.js
tests/spec/core/dfn-panel-spec.js

[Pubrules wanted](https://github.com/w3c/web-share/runs/738231021#step:3:53) an ID on each for `<h2>Referenced in:</h2>`. Falling back to less semantic `<b>` as generating ID on these headings doesn't make sense.
Need to prioritize on https://github.com/w3c/respec/issues/792 / https://github.com/w3c/respec/issues/639 now.

fix(core/dfn-panel): fix heading markup due to pubrules id rule

---

tests/spec/core/highlight-spec.js

respec-hljs got updated on server, causing a test to fail. Syntax highlight has changed a bit in new version.

test(core/highlight): sync with hljs on server

---

src/w3c/headers.js
src/w3c/templates/headers.js
tests/spec/w3c/headers-spec.js

Fixes https://github.com/w3c/respec/issues/1562
To skip adding a "Latest published version" link:
``` js
var respecConfig = {
specStatus: "ED",
latestVersion: null,
};
```

fix(w3c/headers): allow skipping latest published version in ED

---

src/w3c/templates/sotd.js

About [2 months ago ](https://github.com/w3c/specberus/issues/880), we noticed pubrules wasn't strictly checking the disclosure link for IG Notes and we fixed that issue.
Because of that bug, people were confused and they often used the `wgPatentURI` link which contains the deliverer id. This is no longer the case and we now need to rely on the `data-deliverer` attribute for IG Notes. I created a PR for specberus to look for that
attribute: https://github.com/w3c/specberus/pull/919

fix(w3c/sotd): require data-deliverer for IG Notes

---

src/core/link-to-dfn.js
tests/spec/core/link-to-dfn-spec.js

Fixes https://github.com/w3c/respec/issues/2984
Regex test: https://regex101.com/r/HcHnzO/3

fix(core/link-to-dfn): make current-spec regex more conservative

---

package.json

This will allow us to use respec as:
``` bash
npx respec -s src.html -o out.html
npx -p respec respec2html -s src -o out.html
```
and:
``` js
const { fetchAndWrite } = require("respec");
// instead of
const { fetchAndWrite } = require("respec/tools/respecDocWriter");
```

feat(package): better Node.js support

---

src/core/markdown.js
tests/spec/core/markdown-spec.js

``` markdown
``` js
console.log("hey!!");
```
```
becomes:
``` html
<pre class="example js">
console.log("hey!!");
</pre>
```
This might be a breaking change (nested `.example` if people already added their own `pre.example`).
A safer way might be to use DOM manipulation to convert `<pre><code class="lang">` to `<pre class="example lang"><code>`

feat(core/markdown): treat markdown code snippets as 'example'

---

src/core/data-include.js
src/core/markdown.js
tests/spec/core/data-include-spec.js

Closes https://github.com/w3c/respec/issues/3005
https://respec.org/docs/src.html finally looks like good!

fix(core/data-include): support markdown code blocks with unescaped html

---

.github/workflows/changelog.yml

It'll run automatically when we "release". We can also run it [manually](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/).
Takes around 15min to finish.
Changelog generation didn't fail in 5 attempts.
A sample run is available at: https://github.com/sidvishnoi/respec-xref-route/runs/855276492
May close https://github.com/w3c/respec/issues/2782 if we want to go this way.

chore(ci/changelog): automate changelog generation

---

src/core/base-runner.js

There is no plugin using the legacy signature, and it's been a while for this warning to exist.

refactor(core/base-runner): remove legacy plugin support

---

src/core/base-runner.js

As browser support is good enough for us, and Spectre/Meltdown mitigation is to limit the time resolution, I think we can remove these checks. 
Any reason where it might be safe to keep these checks?

refactor(core/base-runner): remove redundant canMeasure checks

---

.github/workflows/changelog.yml

Running on tag update didn't work (bad docs). As we push to gh-pages on release, we can generate changelog then instead.

chore(ci/changelog): generate on push to gh-pages

---

src/w3c/group.js

Gives direct link to the valid group names instead of needing to go to the docs.

fix(w3c/group): friendlier group error message

---

tools/respecDocWriter.js

also, `throw` instead of `process.exit()`

refactor(tools/respecDocWriter): simplify output write, avoid exit

---

tools/respecDocWriter.js

Remove the unnecessary `makeConsoleMsgHandler` factory.
Note to reviewer: Mostly whitespace changes.

refactor(tools/respecDocWriter): cleanup console handler

---

profiles/w3c-common.js
tests/spec/core/ui-spec.js
tests/spec/core/webidl-spec.js

Part of https://github.com/w3c/respec/issues/2889

chore: add deprecation message to w3c-common profile

---

src/core/exporter.js

It produced invalid HTML as such :man_facepalming: :
```html
<link rel="stylesheet" href="https://www.w3.org/StyleSheets/TR/2016/W3C-ED"></head>
<body></body>
<head></head><body class="h-entry" data-cite="WebIDL HTML INFRA URL WEBIDL DOM FETCH"><div class="head">
```

fix(core/exporter): don't add new line on head, body

---

src/w3c/templates/sotd.js

In an afterthought of https://github.com/w3c/respec/pull/3096, we decided to replace `conf.lsMode` with `conf.pubMode === "LS"`, as the latter may allow more options in future without a separate configuration type.

fix(w3c/sotd): replace lsMode with pubMode

---

src/w3c/templates/sotd.js

Closes https://github.com/w3c/respec/issues/3116
[Demo with [Navigation Timing]](https://respec-preview.netlify.app/?spec=https%3A%2F%2Fw3c.github.io%2Fnavigation-timing%2F&version=https%3A%2F%2Fdeploy-preview-3117--respec-pr.netlify.app%2Frespec-w3c.js)

fix(w3c/sotd): use correct patent policy URLs 

---

src/w3c/templates/sotd.js

Adapt to wording change in https://github.com/w3c/tr-design/pull/211
Allow the updateableRec notice to appear for any status per https://lists.w3.org/Archives/Public/spec-prod/2020JulSep/0031.html
Fix updateableRec inclusion per https://github.com/w3c/transitions/issues/266#issuecomment-693438178

fix(w3c/sotd): tweak update policy for non REC

---

src/w3c/group.js
tests/spec/w3c/group-spec.js

1. Improves error messages by using error response from the server.
2. Allow specifying group type to disambiguate groups with same shortname and different type. See https://github.com/marcoscaceres/respec.org/issues/114  (**Note**: Tests will fail until server is updated). Closes https://github.com/w3c/respec/issues/3120.
3. Show deprecation warning if `wg`, `wgURI`, `wgId`, `wgPatentURI`, and `wgPatentPolicy` are used instead of `group`.
Note to reviewer: Review each commit separately. Also, lets merge this as 3 separate commits.

(w3c/group): improve error messages, support group type, deprecate legacy options

---

tools/respec2html.js
tools/respecDocWriter.js

Facing too many timeout errors in CI ([example](https://user-images.githubusercontent.com/8426945/95108149-82542080-0758-11eb-95b6-4f5fda1ab0cf.png)). This PR adds a `--verbose` flag to the ReSpec CLI to show processing status and understand what step is actually taking time.
<details>
<summary>Sample run</summary>
```bash
$ ./tools/respec2html.js -s examples/basic.built.html -o /tmp/out.html --timeout 10 --verbose
[Timeout: 9999ms] Launching browser
[Timeout: 9886ms] Navigating to file:///path/to/examples/basic.built.html
[Timeout: 8259ms] Navigation complete.
[Timeout: 8257ms] Processing ReSpec document...
[Timeout: 6534ms] Processed document.
[Timeout: 5525ms] Done.
```
</details>

feat(tools/respec2html): add verbose flag

---

tests/headless.js
tools/respec2html.js
tools/respecDocWriter.js

- `fetchAndWrite` is deprecated (will be removed in future).
- `--out=""` CLI option no longer writes to stdout.
- `toHTML` is more structured and requires fewer arguments:
- `toHTML` does not write output unlike `fetchAndWrite`.
- `toHTML` returns processed HTML as well as errors & warnings.
- `toHTML` does not have `haltOnError` and `haltOnWarning` object parameter.
- `options.debug` in `toHTML` is renamed to `options.devtools`.
- Removed colors from errors and warnings returned from `toHTML` to make them easier to parse.
- ReSpec version being used is printed during processing.
```js
const { toHTML } = require('respec');
try {
const { html, errors, warnings } = await toHTML(src, options);
} catch (fatalError) {
console.error(fatalError);
}
```
- Use `--out stdout` to write to stdout.
- …

feat(tools/respecDocWriter): add improved toHTML() method

---

src/w3c/templates/headers.js

With the release of process 2020, we asked to specify the type of CR (Snapshot/Draft) in a `<h3>` following the `<h2>` in the headers. We've been asked to integrate this in a single header (https://github.com/w3c/specberus/issues/1006) instead.
We are going to [update pubrules to only check the `h2`](https://github.com/w3c/specberus/pull/1018) early next week so that PR is to prepare respec for that change.
/cc @fantasai @plehegar @jennyliang220

fix(w3c/headers): show CR type in <h2>

---

src/core/dfn-finder.js
tests/spec/core/dfn-finder-spec.js

This update fixes the generation of the `data-lt` attribute when an operation only has optional arguments.
The code added a `, ` prefix before the list of optional arguments, regardless of whether the operation had mandatory arguments as well, leading to names such as `methodName(, options)` instead of `methodName(options)` (see issue #3200).

fix(core/dfn-finder): Properly handle optional arguments in data-lt

---

.github/workflows/changelog.yml

This will get rid of `set-env` and `add-path` deprecation errors in GitHub pages (example: https://github.com/w3c/respec/actions/runs/378730123)

chore(ci/changelog): update create-pull-request to v3

---

package.json

Use `funding` as per [npm docs](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#funding). The `collective` one was used when we had `opencollective-postinstall` enabled.
Pretty sure it's not effective at all (does anyone even run `npm fund` to find projects in funding need!), but lets take our chances.

chore(package.json): use funding option

---

.gitignore
.vscode/settings.json

Everything is already in `.editorconfig` and `package.json`. Ignoring vscode setting respects people's preferences.

chore: gitignore vscode settings

---

src/core/anchor-expander.js
tests/spec/core/anchor-expander-spec.js

fix(anchor-expander): trailing ws when expanding headers

---

src/core/base-runner.js
src/core/include-config.js
src/core/override-configuration.js
src/core/post-process.js
src/core/pre-process.js

We can further refactor these to be imported directly into profiles, not sure if that's preferable.

refactor(core): run global plugins like regular plugins

---

src/core/ui.js
src/w3c/defaults.js
src/w3c/headers.js
src/w3c/templates/headers.js
tests/spec/w3c/defaults-spec.js
tests/spec/w3c/headers-spec.js

Closes #3064 
It no longer hard codes cc-by into the template, which was overriding license selection.

fix(w3c): improve license + unofficial status support

---

src/w3c/templates/cgbg-sotd.js
src/w3c/templates/sotd.js
tests/spec/w3c/headers-spec.js

Plus adds "subscribe" to mailing list link that was missing for everyone. Looks like: 
Closes #1636

fix(w3c/sotd): allow CGs to prefer github coms

---

tests/spec/core/markdown-spec.js

hljs was detecting the test block as "CSS".
Follow up: As we've access to highlight languages, we should probably use `highlight(lang, code)` instead of `highlightAuto(code, langSuggestions)`. Should also move respec-hljs into respec repo, to make such changes easier.

tests(core/markdown): workaround highlight.js lang detection bug

---

tools/dev-server.js

Looks like a small regression from #3317 ... was wondering how Sade determined the types. Now I know 🤣

fix(tools/dev-server): regression, browsers arg must be an array

---

assets/examples.css
assets/respec.css

Makes the `<pre>`s inside `.example` blocks a little darker, and matches what Bikeshed does: 
This is nice in the it better splits up code and text:

fix(assets/respec.css): darken pre background in examples

---

tools/respec2html.js

> (By the way, it would be useful if --help or --version gave some ReSpec version info). ― https://github.com/w3c/respec/issues/3292#issue-800749440

feat(tools/respec2html): add --version flag

---

src/core/pubsubhub.js
src/core/respec-global.js
tests/spec/core/respec-global-spec.js

Closes #1084
Extracted from https://github.com/w3c/respec/pull/3338
Will implement `dispatchEvent` stuff when we need it.

feat(core/respec-global): collect errors and warnings

---

assets/caniuse.css

also differentiate between partial support and disabled by default
Compare with payment-request: [before](https://respec-preview.netlify.app/?spec=https%3A%2F%2Fw3c.github.io%2Fpayment-request%2F&version=https%3A%2F%2Funpkg.com%2Frespec%4026.2.0%2Fbuilds%2Frespec-w3c.js) | [after](https://respec-preview.netlify.app/?spec=https%3A%2F%2Fw3c.github.io%2Fpayment-request%2F&version=https%3A%2F%2Fdeploy-preview-3371--respec-pr.netlify.app%2Frespec-w3c.js)

styles(caniuse): align styles with caniuse.com

---

tools/respec2html.js
tools/respecDocWriter.js

Remaining part of https://github.com/w3c/respec/pull/3342
Didn't provide `ReSpecError.details` yet, as it gets noisy. Will add sometime later as a followup (maybe behind a --log-level arg?).

feat(tools/respec2html): provide more detailed logs

---

src/dini/conformance.js
src/w3c/conformance.js

tools.ietf.org urls are being deprecated per https://mailarchive.ietf.org/arch/msg/tools-discuss/oYrAxb3KayPzZ4SNB1DVZTDPPNo/

fix(conformance): use datatracker for IETF urls

---

src/core/link-to-dfn.js
tests/spec/core/data-cite-spec.js

The `updateReferences()` function was being too generous with matching on shortname, meaning that webxr-gamepad-* was being seen as self citing.

fix(core/link-to-dfn): make shortName matching stricter

---

.github/workflows/pr.yml
package-lock.json
package.json
tests/test-build.js

- Fix fileExists check in `test-build.js` (`stats.fileExists()` is not a function)
- Remove chai dependency, use jasmine's matchers
- Cleanup `builds` dir after running `test:build`
- Run `test:build` in CI

tests(build): fix fileExists check, remove chai, run in CI

---

package.json
tests/headless.js

Less custom stuff is better I guess.
Logs aren't as pretty as before, but that can be fixed by using a different jasmine reporter (when jasmine makes it easier).

refactor(tests/headless): use jasmine instead of custom runner

---

tests/headless.js
tools/respec2html.js
tools/respecDocWriter.js

Closes https://github.com/w3c/respec/issues/2874 
``` bash
respec2html --src examples/basic.built.html -o /dev/null
respec2html --src examples/basic.built.html -o /dev/null --use-local
```

feat(respecDocWriter): use locally installed respec version

---

tests/spec/core/a11y-spec.js

To avoid tests failing due to timeout, which often requires restarting them.

tests(core/a11y): increase timeout

---

tools/dev-server.js

If `BROWSERS` or `--browser` is not set, devServer didn't start (blocked on await KarmaServer).

chore(tools/dev-server): run dev server before tests, help msg

---

tools/dev-server.js

There is no `colors.error` apparently.

fix(tools/dev-server): output red errors

---

profiles/w3c.js
src/core/defaults.js
src/core/linter-rules/a11y.js
src/type-helper.d.ts
src/w3c/defaults.js
tests/spec/core/linter-rules/a11y-spec.js
tests/spec/w3c/defaults-spec.js

- convert to linter-rule while supporting `conf.a11y` for backward compatibility.
- improve tests

refactor(core/linter-rules/a11y): convert core/a11y to linter rule

---

src/w3c/templates/sotd.js
tests/spec/w3c/group-spec.js

fix(w3c/templates/sotd): pluralize groups when noRecTrack

---

src/core/data-cite.js
src/core/xref.js

Somewhat high priority... this is what was causing those weird URL issues that we saw the other day where, for example, we ended up with urls like TR/foo/TR/foo#whatever.

fix(core/data-cite|xref): use xref hrefs when available

---

src/core/utils.js
tests/spec/core/anchor-expander-spec.js
tests/spec/core/utils-spec.js

fix(core/anchor-expander): don't copy attributes when expanding

---

src/core/ui.js

The plugin name itself is not very useful for regular users, but useful for debugging... so putting it last.

fix(core/ui): display plugin name after error msg

---

src/w3c/headers.js
tests/spec/w3c/headers-spec.js

fix(w3c/headers): don't add W3C to h2 for 'base' documents

---

src/w3c/style.js
tests/spec/w3c/style-spec.js

fix(w3c/style): misspelled finding-draft

---

src/w3c/templates/headers.js
tests/spec/w3c/headers-spec.js

Fixes https://github.com/w3c/respec/issues/3541

fix(w3c/templates/headers): show versions links for TAG docs

---

src/core/anchor-expander.js
src/core/inlines.js
src/core/utils.js

- Add JSDoc annotations to get better TypeScript and VSCode support.
- Remove some outdate comments.
- Minor fixes/improvements that TS help catch.

refactor(core/utils): add JSDoc TypeScript annotations

---

src/core/dfn-panel.js
tests/spec/core/dfn-index-spec.js

Fixes https://github.com/w3c/respec/issues/3592
Hotfix until we find a better solution.
We should probably use:
- `aria-controls`, or
- the `<dfn>term</dfn><button class="visually hidden">Show what links to this dfn: term</button>` approach.
I'll have to read more.

fix(core/dfn-panel): don't add title attribute to dfn

---

tools/release.js

Can't use `lockfileVersion` as it gets generated some stage later.

chore(tools/release): ensure npm 6 is used

---

src/core/inlines.js
tests/spec/core/inlines-spec.js

Fixes linking for `[^ /role ^]` attribute.

fix(core/inlines): link global element attributes

---

src/core/dfn.js
tests/spec/core/dfn-spec.js

Supports the following definition classes, to align with Bikeshed (per the contract):
* abstract-op
* attribute
* attr-value
* element
* element-state
* event
* http-header
* scheme
Adds one new one:
* media-type

feat(core/dfn): use class name for definition type

---

src/core/dfn.js
src/core/webidl.js
tests/spec/core/dfn-spec.js

Support for `<dfn class="no-export">`, giving control to Editors over things they might want to keep private.

feat(core/dfn): support "no-export" class

---

src/core/dfn-validators.js
tests/spec/core/validators-spec.js

Checks definitions that are supposed to be wrapped in quotes, like permissions.

feat(core/dfn-validators): export validateQuotedString()

---

src/core/web-monetization.js
tests/spec/core/web-monetization-spec.js

Adds configuration:  `monetization: {paymentPointer: string, removeOnSave: boolean}`.

feat(core/web-monetization): add object configuration

---

tests/spec/w3c/headers-spec.js

With new dt/dd being added by Process 2021, these are no longer assured to be in those particular positions. We shouldn't be relying on those positions anyway.

tests(w3c/headers): don't rely dt/dd order

---

src/core/github.js
src/w3c/defaults.js
tests/spec/core/github-spec.js

Also adds some additional URLs to `normalizedGHObj`, which are needed by Process 2021.

feat(core/github): add private excludeGithubLinks option

---

src/w3c/templates/headers.js
tests/spec/w3c/headers-spec.js

Links to a new W3C document that describes what spec status actually are...

feat(w3c/headers): links 'kinds of documents' for W3C documents

---

src/w3c/templates/headers.js
tests/spec/w3c/headers-spec.js

As part of 2021, we are wrapping the header in `<details>`. 
I'm setting it to be open by default for now, but eventually there will be a site-wide setting to remember if it should be open or closed.

fix(w3c/headers-spec): wrapped header in <details>

---

src/core/title.js
tests/spec/w3c/headers-spec.js

fix(core/title): handle line break in title

---

tools/respec2html.js

Caught in https://github.com/w3c/hr-time/pull/130
Will release ASAP.

fix(respec2html): correctly import marked

---

src/w3c/templates/sotd.js

fix(w3c/sotd): ensure right endorsement text is selected

---

src/core/id-headers.js

Moves the permalink to the end of the heading for screen readers. This makes the relevant information up-front and makes the document much more useful for screen reader users.
Does not fully resolve https://github.com/w3c/respec/issues/3898 but it does make the result much better with a very small change

fix: move permalink after the header text

---

src/w3c/headers.js

Pubrules is reporting that it expects https://www.w3.org/Consortium/Legal/copyright-documents when "document use" is used in the copyright.

pubrules-compliant uri for document license

---

src/styles/respec.css.js

fixes #3849
Renders as:
Can def live with that... getting a little bored with the current style tho. We should check if there is something more 2022.

fix(styles/respec): don't override hljs style

---

profiles/w3c.js
src/core/linter-rules/no-unused-dfns.js
src/w3c/defaults.js
tests/spec/core/linter-rules/no-unused-dfns-spec.js
tests/spec/w3c/defaults-spec.js

closes #904
Complains when something is defined but not used. Should have added this years ago. I already found a bugs in Payment Request.

feat(lint/no-unused-dfns): complain on unused dfns

---

src/core/utils.js
src/w3c/linter-rules/required-sections.js
tests/spec/w3c/linter-rules/required-sections-spec.js

Forgot that this would get upset if the document was not in English.

fix(w3c/linter-rules/required-sections): support other locales

---

src/w3c/seo.js

Recent Notes don't pass pubrules as they are missing the canonical link

fix(w3c/seo): add canonical link for Note and Registry track docs

---

src/w3c/defaults.js
src/w3c/group.js
src/w3c/headers.js
src/w3c/style.js
tests/spec/core/exporter-spec.js
tests/spec/core/override-configuration-spec.js
tests/spec/w3c/defaults-spec.js
tests/spec/w3c/headers-spec.js
tests/spec/w3c/linter-rules/required-sections-spec.js
tests/spec/w3c/seo-spec.js
tests/spec/w3c/style-spec.js

closes #3965
This prevents usage of W3C Rec Track status and W3C logo on documents that are not attached to a working group. 
The only exception is for "ED", which some groups sometimes use as "unofficial" before publishing. 
It means that everyone now needs to specify a `group` if they want to edit a Rec Track document.

BREAKING CHANGE: don't show logo or allow usage of W3C status if not in a W3C WG

---

tests/spec/core/validators-spec.js

This should hopefully fix the random validateMIME failures.

test(core/validators-spec): make tests less racy

---

package-lock.json
package.json
tests/karma.conf.base.js

pnpm uses Node's resolve algorithm, so some packages failed to resolve (npm flattens dependency tree, so all resolved fine there).
This PR is allowing development with pnpm for those who want to use it. npm will continue to work fine. If someone wants to use pnpm locally, they can:
```bash
rm -rf node_modules
pnpm import # imports package-lock.json and creates a pnpm-lock.yaml
pnpm install
```
When updating a dependency in `package-lock.json`, we can:
```bash
npm i --package-lock-only # this will not touch node_modules
pnpm import && pnpm install
```

chore: support development with pnpm

---

src/core/inlines.js

In German, the words KANN, SOLL and MUSS are different in plural, so I had to add them to the list.
I hope the umlaute are not a problem.

Adding German Translations for rfc2119Keywords

---

src/core/import-maps.js
src/core/markdown.js
src/core/ui.js

Markdown links inside hints stopped working... now fixed.

fix(core): render UI hints/error as inline markdown

---

src/styles/respec.css.js

Found that community group reports have a straight `<h2>` in the head.

fix(styles/respec.css): generalize to any h2 in head

---

tests/spec/core/simple.html
tests/spec/w3c/headers-spec.js

As part of the W3C's "Project ClearSpec", we are making it impossible to set wgPatentPolicy manually. As such, we can remove this test (everyone must use group).

tests(w3c/headers): stop testing wgPatentPolicy

---

.github/workflows/push.yml

Instead of exiting with error code, this will just print the status code. It'll still fail if server is down or if network fails etc.
This has been annoying as we couldn't re-run CI in case of intermittent failures. We can safely re-run CI on failure now.

chore(ci/push): don't fail if failed to PUT size

---

src/w3c/headers.js
tests/spec/w3c/headers-spec.js

fix(w3c/headers): always add History or FPWD

---

src/w3c/templates/cgbg-headers.js

CG/BG specs are currently missing the publication date and are missing link to the doc that describes the document type.

fix(w3c/cgbg-headers): link doc type and show pub date

---

src/w3c/templates/headers.js

fix(w3c/headers): remove doubled "in" in German translation

---

src/w3c/headers.js
src/w3c/linter-rules/required-sections.js
tests/spec/w3c/headers-spec.js
tests/spec/w3c/linter-rules/required-sections-spec.js

Also notes don't need a privacy and security considerations section. Only "specs" do.  
fixes #4064

fix(w3c/headers): W3CNotes are /TR/ docs

---

src/core/caniuse.js
tests/spec/core/caniuse-spec.js

Seems we might be missing UC browser on w3.org... but apart from that, all good :D

fix(core/caniuse): host logos at w3.org

---

src/core/inline-idl-parser.js

Otherwise, respec complains about unknown 'WebIDL' reference
See https://w3c.github.io/mediacapture-region/ where this manifests itself (cf https://github.com/w3c/mediacapture-region/pull/39#pullrequestreview-928481678)

hotfix(core/inline-idl-parser): use WebIDL in lowercase

---

src/w3c/templates/sotd.js

CR requires an end date which can be set with the `crEnd` option. However, that option is not taken into account.
That PR fixes the SOTD template to use the right option.

fix(w3c/sotd): use `crEnd` instead of incorrect `CREnd`

---

src/w3c/defaults.js

The TAG can now publish in TR, and intends to do so relatively regularly. This PR removes the restriction. This is blocking publication of an FPWD.

fix(w3c): allow trStatus specStatus for TAG

---

src/w3c/headers.js

The "This version" link is not generated properly for a Note produced by the TAG because the publication space only takes the documents on REC track into account.
That PR includes the other types of documents for /TR.

fix(w3c/headers): TR pub space applies to all TR statuses

---

src/core/mdn-annotation.js
src/styles/mdn-annotation.css.js

Closes https://github.com/w3c/respec/issues/4109
and remove IE 🎉 
---
`issueCount--`

fix(core/mdn-annotation): use logos from cdn.w3.org

---

src/styles/respec.css.js

Fixes #4163
Matches examples on tr-design, as well as Bikeshed. Monospace font is enough to distinguish code from rest of the content, different color is indeed distracting.

fix(styles/respec): don't give different color to `<code>`

---

src/core/issues-notes.js
tests/spec/core/issues-notes-spec.js

This changes the behaviour of the issues and notes selector to ignore any elements that have an SVG element as an ancestor. It does this by filtering the selected elements and looking to see if the `.closest` method returns null; if it is null, it means that the element is not within an SVG block; if it is not null, it is filtered out of the list of elements for further processing.
A simple unit test is included that checks to see if there are any `<div>` elements that are within an `<svg>` element (`<div>` is not a valid child of `<svg>`). If the selector is null it means the test passed.
Fixes #4238.

fix(core/issues-notes): ignore svg descendents from processing

---

src/core/utils.js
src/w3c/linter-rules/required-sections.js
tests/spec/core/utils-spec.js
tests/spec/w3c/linter-rules/required-sections-spec.js

Fixes https://github.com/w3c/respec/issues/4156
A full BCP 47 checker might be too much here.
Also add `getIntlDataForKey` util to test for translation availability.

fix(core/utils:`getIntlData`): match language subtag too

---

src/w3c/headers.js

Currently, it links to https://respec.org/docs/#%60w3cid%60 , which has a broken URI fragment. This PR tries to fix the issue.

fix(w3c/headers): fix broken link

---

src/w3c/templates/sotd.js

In languages that have no word separators, such as Chinese, the CSS [segment break transformation rules](https://www.w3.org/TR/css-text/#line-break-transform) can transform the segment break into a space, which might make the reader uncomfortable.
I also let ESLint and Prettier ignore this line, lest they think it's too long.

fix(w3c/sotd): remove spaces in Chinese

---

src/core/dfn-validators.js
src/core/dfn.js
src/core/inlines.js
tests/spec/core/dfn-spec.js
tests/spec/core/validators-spec.js

The code mistakenly used 'attribute' instead of 'element-attr'. It also didn't support linking to attributes defined inline in the spec.

fix(core/dfn): add support for defining `element-attr` dfns

---

src/w3c/headers.js

REC with candidate amendments should not need a revised end date.
Fix #4291

fix(w3c/headers): require `revisedRecEnd` with proposed amendments only

---

src/core/inline-idl-parser.js
src/core/link-to-dfn.js
src/core/webidl.js

* Skip searching in local definitions for links marked with data-xref-
* Be strict when looking for local definitions when the data-link-type is set

fix(core/link-to-dfn): better disambiguation b/w dfns of different types

---

src/core/link-to-dfn.js
tests/spec/core/link-to-dfn-spec.js

When a dfn has a comma-separated values of targets, any of the targets should be recognized as valid for an autolink; this is particularly important for links that use a microsyntax where it is not possible to list all the possible targets.

feat(core/link-to-dfn): support multiple `dfnFor`

---

profiles/w3c.js
src/core/linter-rules/informative-dfn.js
src/core/xref.js
src/w3c/defaults.js
tests/spec/core/linter-rules/informative-dfn-spec.js
tests/spec/core/xref-spec.js
tests/spec/w3c/defaults-spec.js

There are situations where making a normative reference to a definition in an informative section is either OK or unavoidable (e.g. because updating the referenced spec is unlikely to be possible). Moving the relevant check in a linter make it easier to silence either individual or all instances of the warning.
see also #4295

feat(linter-rules/informative-dfn): warn on refs to informative dfns

---

src/w3c/defaults.js
tests/spec/w3c/defaults-spec.js

The TAG can now produce REC-track docs, and in general tends to use a different method of drafting compared to what things were like ten years ago.
I added `ED` in this way rather than by adding it to eg. `tagStatus` or `trStatus` as that would break other things that those are used for.

feat(w3c): support specStatus "ED" for the TAG

---

src/w3c/templates/sotd.js

The parameter to specify the PR end date is `prEnd` instead of `PREnd`

fix(w3c/sotd): fix typo in `prEnd` variable

---

src/core/utils.js

While releasing, HTML validator shouted at me saying `datetime` isn't the right format. In fact, on my computer, the generated HTML was:
```html
<time class="dt-published" datetime="01/22/2023">22 January 2023</time>
```
This change is based on https://stackoverflow.com/a/58633686

fix(core/utils): ensure `ISODate` formats date correctly

---

src/core/utils.js
src/w3c/style.js

The W3C logo on respec source documents doesn't appear correctly on Chrome which reports the following warning/error:
* warning: A preload for 'https://www.w3.org/StyleSheets/TR/2021/logos/W3C' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.
* error: Access to image at 'https://www.w3.org/StyleSheets/TR/2021/logos/W3C' from origin 'https://w3c.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
MDN describes that the [preload `link` should match the credential mode](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/preload#cors-enabled_fetches) used to fetch the resource so I think it's missing the `crossorigin` attribute.

fix(w3c/style): add `crossorigin` attribute to W3C logo preload

---

tools/respec2html.js

Missed in https://github.com/w3c/respec/pull/4419

fix(tools/respec2html): prevent crash on `--version` flag

---

src/w3c/headers.js
src/w3c/templates/sotd.js

For **Notes**, use:
```
This Group Note is endorsed by the XXX Group, but is not endorsed by W3C itself nor its Members.
```
...resolves https://github.com/w3c/respec/issues/4425

fix(w3c/sotd): update stability tempate for NOTEs

---

tools/respec2html.js

Fixes https://github.com/w3c/respec/issues/4338
Changes behavior to:
`--haltonwarn` == fatal exit if any warnings or errors
`--haltonerror` == fatal exit if any errors (ignore warnings)

fix(tools/respec2html)!: make `--haltonwarn` halt on errors too

---

src/core/utils.js
src/core/xref.js
tests/spec/core/dfn-index-spec.js

A fix for #4430 : when the normalized text is rendered as html e.g. in `dfn-index.js` line 298 within `renderExternalTermEntry` using `html: text` this prevents creation of what the UA thinks are HTML elements from terms defined with angle brackets at the start and end.
An alternative fix could be to replace `html: text` with `text: text` but I think that would break cases where code blocks are deliberately put around the term in the index.
This fix seems to pass all the tests.
---
- Fixes #4430
- Fixes https://github.com/w3c/respec/issues/4324

fix(core/dfn-index): escape HTML/XML tags

---

src/core/caniuse.js
src/styles/mdn-annotation.css.js
tests/spec/core/caniuse-spec.js

To fix [some performance issues](https://github.com/w3c/w3c-website/issues/289), we are now hosting the assets on www.w3.org instead of cdn.w3.org.
That PR updates all occurences of cdn.w3.org.
/cc @plehegar

fix(core/caniuse, core/mdn): host browser logos on `www.w3.org`

---

src/w3c/templates/cgbg-headers.js

Fixes https://github.com/w3c/respec/issues/4449
https://github.com/w3c/respec/issues/4038 strikes again.

fix(w3c/cgbg-headers): render `otherLinks`

---

src/w3c/headers.js
tests/spec/w3c/seo-spec.js

The link to the software license has been updated since Jan 1.
It should now be:
https://www.w3.org/Consortium/Legal/2023/software-license
intead of
https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document  (see the status warning at the top)

fix(w3c/headers): update link for Software License

---

src/w3c/headers.js
tests/spec/w3c/headers-spec.js

After the [deployment of the new website](https://www.w3.org/news/2023/new-w3c-website-deployed/), most of the W3C URLs now have a trailing slash.
This is causing a problem when respec tries to fetch the history link for a spec as there's now a redirection and CORS is blocking the [HEAD](https://github.com/w3c/respec/blob/main/src/w3c/headers.js#L763) the check if the link exists.
That PR updates the history link to add the trailing slash

fix(w3c/headers): history link now has a trailing slash

---

tools/respecDocWriter.js

It doesn't seem necessary to generate a different user data directory for each document.
spec-generator relies on `RespecDocWriter` to generate snapshots from respec documents and the recent increase of requests completely filled up the tmp partition.

fix(respecDocWriter): use default `userDataDir`

---

tools/respecDocWriter.js

Fixes https://github.com/w3c/respec/issues/4538
Not sure when this got removed.

fix(tools/respecDocWriter): `handle.executionContext` is not a function

---

src/w3c/headers.js
src/w3c/templates/cgbg-headers.js
src/w3c/templates/headers.js
tests/spec/w3c/seo-spec.js

[Pubrules will soon require the new copyright links](https://github.com/w3c/specberus/pull/1783) to avoid redirects.
These changes also need to be sync'ed with bikeshed: https://github.com/speced/bikeshed-boilerplate/pull/53

fix(w3c/headers): update copyright links to avoid redirects

---

src/w3c/templates/sotd.js

Related to https://github.com/w3c/modern-tooling/issues/111

fix(w3c/sotd): switch to 2023-Nov process document

---

tools/respecDocWriter.js

In some cases, we may want to disable GPU hardware acceleration to save some resources.
That PR allows that by passing an additional option.

add option to disable GPU

---

examples/basic.html
src/styles/algorithms.css.js
src/styles/caniuse.css.js
src/styles/datatype.css.js
src/styles/dfn-panel.css.js
src/styles/examples.css.js
src/styles/highlight.css.js
src/styles/issues-notes.css.js
src/styles/mdn-annotation.css.js
src/styles/respec.css.js
src/styles/ui.css.js
src/styles/var.css.js
src/styles/webidl.css.js
src/type-helper.d.ts
src/w3c/style.js
tests/spec/w3c/style-spec.js

Closes https://github.com/w3c/respec/issues/2651
Disabled by default. Set `respecConfig.darkMode = true` to enable. 
Please provide feedback if you enable dark mode. You can add `?darkMode=true` to your ReSpec spec URL and toggle dark mode in system/browser to preview without making editorial changes.
This gives a "good enough" support for dark mode. Not all styles are perfected yet.
And some styles can't be overridden by the manual theme toggle (they only respect `@media (prefers-color-scheme: dark) {...}`).
I've tried to use W3C stylesheets's CSS variables wherever possible to avoid this, but at least styles for code syntax highlighting (including WebIDL), and definition panel aren't supported in that theme, so they won't fully respect the manual theme toggle.
---
If you want to try …

feat: dark mode

---

src/styles/respec.css.js

We should just let the W3C's base.css handle styling things on the page. That way we get consistent styling across all docs, and don't need to worry if base.css changes... and we can upstream styling issues to the W3C
Closes #4667

fix(styles/respec.css): defer default styles to W3C

---

tools/respecDocWriter.js

We no longer need to remove the network interception after first request. It used hang if there was a network request in a worker (in our case, respec-highlight). See https://github.com/puppeteer/puppeteer/issues/4208#issuecomment-2040324195
I'm thinking we can also avoid fetching stylesheets and images to make builds faster in CI.

fix(api:node): proxy all local scripts with useLocal, not just main

---

src/core/inlines.js
tests/spec/core/inlines-spec.js

Fixes https://github.com/w3c/respec/issues/4632

fix(core/inlines): allow quotes in inline var's types (for enums)

---

src/core/linter-rules/a11y.js

unpkg is down, and I'm not sure it's maintained. Tests are failing for a11y linter, and we get occasional timeouts. So, moving to "bigger player".

fix(core/linter/a11y): import axe from jsdelivr instead of unpkg

---

src/w3c/style.js
tests/spec/core/color-scheme.html
tests/spec/w3c/style-spec.js

Removes the opt in `respecConfig.darkMode` option, allowing HTML's  meta tag to be used instead.

fix!(w3c/style): override color-scheme with meta tag

---

src/core/inlines.js
tests/spec/core/inlines-spec.js

fix(core/inlines): support generic nullable type in inline var

---

tools/respec2html.js

Closes https://github.com/w3c/respec/issues/4718
`--disable-sandbox` is used enough already (searched GitHub), so adds alias without removing it.
Here's the mapping (making it work with our CLI args processing tool):
| Flag | `disableSandBox` | 
| --- | --- |
| no flags | false |
| `--disable-sandbox` | true |
| `--no-sandbox` | true |

feat(CLI): add `--no-sandbox` as alias to `--disable-sandbox`

---

src/core/xref.js

Fixes https://github.com/w3c/respec/issues/4696
Fixes https://github.com/w3c/respec/issues/4720
Compare: [old](https://respec-preview.netlify.app/?spec=https%3A%2F%2Fw3c.github.io%2Fscreen-orientation%2F&version=https%3A%2F%2Fdeploy-preview-4700--respec-pr.netlify.app%2Frespec-w3c.js) | [new](https://respec-preview.netlify.app/?spec=https%3A%2F%2Fw3c.github.io%2Fscreen-orientation%2F&version=https%3A%2F%2Fdeploy-preview-4724--respec-pr.netlify.app%2Frespec-w3c.js)

fix(core/xref): fix rendering of hint in ambiguous term error

---

src/w3c/templates/headers.js

See https://github.com/w3c/geolocation-api/pull/158#issuecomment-2149219993

fix(w3c/headers): don't crash on save if `.head details` doesn't exist

---

src/w3c/headers.js
src/w3c/templates/sotd.js

That PR updates the links of the Patent Policy and the Process Document now that they are under /policies.

fix(w3c): update Process and Patent Policy links

---

src/core/xref.js
tests/spec/core/xref-spec.js

Fixes #4787.
The URL of the spec may end with a filename but the code assumed that it would always be a path, and thus that resolving `./` against the URL of the spec would be a no-op. The code now makes sure resolve the URL of the spec against an empty string when the xref search does not return a more specific path.

fix(core/xref) : preserve the filename in URL

---

src/core/pubsubhub.js

Part of https://github.com/speced/respec/issues/4825
Instead of `rsError` being null (from global `window.onerror` listener), create rsError properly:

fix(core/pubsubhub): log errors from event handlers

---

src/w3c/templates/sotd.js

Update the stability text for Statements and Registries to follow the pubrules recommendation:
* https://www.w3.org/pubrules/doc/rules/?profile=STMT#stability
* https://www.w3.org/pubrules/doc/rules/?profile=RY#stability

fix(w3c/sotd): update stability text for STMT and RY

---

src/aom/conformance.js
src/dini/conformance.js
src/w3c/conformance.js

The current link redirects to this new link. To
avoid the redirect (which can take a while), link
to the original source.

fix(conformance): avoid redirect in BCP 14 link

---

src/styles/respec.css.js

Axe reports that bibliography references aren't accessible, as they are links but don't appear as such:
```
• Error: Links must be distinguishable without relying on color (https://dequeuniversity.com/rules/axe/4.8/link-in-text-block?application=axeAPI)
├── link-in-text-block
├── #glossary > dl > dd:nth-child(8) > cite > a
└── <a class="bibref" data-link-type="biblio" href="#bib-rfc3986" title="Uniform Resource Identifier (URI): Generic Syntax">rfc3986</a>
```
Rather than using an underline (since that would clash with the block notation of referencing), adding an italic text does make it appear visually distinct.

fix(styles/respec): make bibref links distinguishable for a11y

---

src/core/linter-rules/wpt-tests-exist.js

Fixes: https://github.com/speced/respec/issues/4966

fix(lint/wpt-tests-exist): ignore `?` when finding tests

---

src/w3c/templates/sotd.js

There's an open PR on pubrules to fix some errors with the W3C SotD (https://github.com/w3c/specberus/pull/1972).
That PR updates respec to follow the new requirements.
Note that we need to deploy it shortly after the new version of pubrules is released, hence the draft PR.

fix(w3c/sotd): update SotD requirements
